### PR TITLE
Add some missing braces to fix step-62.

### LINKED ISSUE #8049: Pull request 8019 leads to compilation problems in step-62
When compiling step-62, I get the following errors:
```
~/git-files/dealii_anates/examples/step-62/step-62.cc: In member function ‘void step62::ElasticWave<dim>::assemble_system(double, bool)’:
~/git-files/dealii_anates/examples/step-62/step-62.cc:965:24: error: ‘i’ was not declared in this scope
               cell_rhs(i) += quadrature_data.right_hand_side[i];
                        ^
~/git-files/dealii_anates/examples/step-62/step-62.cc:965:24: note: suggested alternative: ‘xi’
               cell_rhs(i) += quadrature_data.right_hand_side[i];

```
and 
```
~/git-files/dealii_anates/examples/step-62/step-62.cc: In member function ‘virtual std::complex<double> step62::PML<dim>::value(const dealii::Point<dim>&, unsigned int) const’:
~/git-files/dealii_anates/examples/step-62/step-62.cc:480:14: error: no match for ‘operator+’ (operand types are ‘int’ and ‘std::complex<double>’)
     return 1 + std::max(calculated_pml_x_coeff, calculated_pml_y_coeff) *
            ~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
                  std::complex<double>(0, 1);
```
Based on what I can see, those changes were introduced in https://github.com/dealii/dealii/pull/8019. Is that a problem in my configuration, or a general bug (especially the first error)?

### PR DESCRIPTION
**Pull request by drwells**
Fixes #8049. I do not have a complex PETSc installation so I cannot test this at the moment, but the bug is clear.

### CODE REVIEW

**Comment by masterleinad** [comment]
Thanks!

**Comment by drwells** [comment]
@bangerth mind if we just merge this for the same reason as in #8052 ? The tester didn't catch it before so its not going to catch it now.

**Comment by drwells** [comment]
Hm. I am going to take the liberty of merging this as-is since this program, AFAICT, is not actually compiled by any of the testers (otherwise we surely would have caught this usage error previously).

**Comment by bangerth** [comment]
Good call.
