### PR TITLE
Remove an unused function.

### PR DESCRIPTION
**Pull request by bangerth**
The function is static and in a .cc file, so there is no way the function
could be used anywhere else.

### CODE REVIEW

**Comment by masterleinad** [comment]
This function was used in the implementation of
```
TrilinosWrappers::MPI::Vector::reinit (const BlockVector &v, const bool import_data)
```
which is actually not deprecated. While working on #4356, I noticed that I removed that implementation accidentally and added it back in. Apparently, only
```
TrilinosWrappers::Vector::reinit (const BlockVector &v, const bool import_data)
```
was used in the testsuite and so this issue didn't show up in testing #4345.

**Comment by bangerth** [comment]
But then I don't understand how I can compile. This is in a .cc file, and it's a local static function (in an anonymous namespace), so it isn't exported out of the .cc file. If it's not used in this file, it can't be used anywhere else either.

So where *is* it used?

**Comment by Rombur** [comment]
@masterleinad are you sure? I did a grep and I couldn't find where the function was used.

**Comment by masterleinad** [comment]
@Rombur I am referring to the version of the file `source/lac/trilinos_vector.cc` before #4345 (
https://github.com/dealii/dealii/blob/44adb1d805e0e2e93d4bf5f747f2709133339b7c/source/lac/trilinos_vector.cc#L395). This should not have been removed.

@bangerth I just confirmed again that the test `mpi/blockvec_02` fails in #4356 with
```
 undefined reference to `dealii::TrilinosWrappers::MPI::Vector::reinit(dealii::TrilinosWrappers::MPI::BlockVector const&, bool)'
```
if I remove the definition although I can still compile the library.

**Comment by masterleinad** [comment]
[CDash](https://cdash.kyomu.43-1.org/testDetails.php?test=22939821&build=7155) confirms this. I'll fix the failing tests.

**Comment by masterleinad** [comment]
See #4360.

**Comment by bangerth** [comment]
So just to confirm, once #4360 is merged, the function I'm removing here is used again? If you agree, then please just close the current PR.

**Comment by masterleinad** [comment]
@bangerth Yes, exactly.
