### ISSUE TITLE
Compilation error with gcc 4.4.7

### ISSUE THREAD

**Issue by ian-r-rose** [dealii/dealii#806]
I ran into this compilation error trying to compile deal.ii using gcc 4.4.7: 

/home/ian.rose/dealii/build/source/grid/grid_generator.inst:45: error: using ‘typename’ outside of template

It appears to have been introduced with 2204ca401663ce0db9b547c0c03e196d02468850 , being some sort of issue with differences in the typename keyword between C++11 and C++03, though I don't really understand the issue.

**Comment by Rombur** [comment]
Ian,

can you delete the typename in grid_generator and see if it works ? I 
don't think that the typename is necessary here since it's a specialization.

Best,

Bruno

**Comment by bangerth** [comment]
Yes, the typename must go. @ian-r-rose : Are you set up with a current deal.II version for which you could create a pull request?

**Comment by ian-r-rose** [comment]
Yes, I am just waiting to make sure the compile works, and can submit a PR in a few minutes.

**Comment by bangerth** [comment]
@Rombur : Was this fixed?

**Comment by Rombur** [comment]
Yes, I merged the patch but I forgot to close the issue.

**Comment by bangerth** [comment]
OK, thanks.

**Comment by bangerth** [comment]
I totally missed this patch in my emails. My brain stores no recollection having seen this -- a reflection of my week, I guess :-(
