### PR TITLE
Default copy assignement in Tensor for non-Intel compilers

### PR DESCRIPTION
**Pull request by masterleinad**
In #5865, we explicitly defined the copy assignment operator so that ICC-15 can compile.
Now, `gcc-8` complains that `Tensor` is not trivially-copyable. Hence, let us just use the explicit copy assignment for Intel compilers.

### CODE REVIEW

File: include/deal.II/base/tensor.h [hunk 1]
```diff
@@ -212,7 +212,12 @@ class Tensor<0,dim,Number>
   /**
    * Assignment from tensors with same underlying scalar type.
    */
-  Tensor &operator = (const Tensor<0,dim,Number> &rhs);
+  Tensor &operator = (const Tensor<0,dim,Number> &rhs)
+#ifndef __INTEL_COMPILER
+    = default;
+  // ICC 15 doesn't allow this opy constructor to be defaulted.
```
Comment (jppelteret) [inline include/deal.II/base/tensor.h]: typo "copy"

File: include/deal.II/base/tensor.h [hunk 2]
```diff
@@ -212,7 +212,12 @@ class Tensor<0,dim,Number>
...
+  // see https://github.com/dealii/dealii/pull/5865.
+#endif
```
Comment (jppelteret) [inline include/deal.II/base/tensor.h]: Don't we need to add an
```
#else
;
#endif
```
otherwise we'd be missing the line terminator when `__INTEL_COMPILER` is defined?

Comment (jppelteret) [reply include/deal.II/base/tensor.h]: Perhaps since this function has a simple signature, may I suggest that we make this code block
```c++
#ifdef __INTEL_COMPILER
Tensor &operator = (const Tensor<0,dim,Number> &rhs);
#else
Tensor &operator = (const Tensor<0,dim,Number> &rhs) = default;
#endif
```
Then its a bit more clear what's going on, and the macro condition is the same here and later for the  definition.

Comment (masterleinad) [reply include/deal.II/base/tensor.h]: Fixed.

**Comment by tamiko** [comment]
I will run a buildtest on bob for this quickly so that we can merge.

**Comment by tamiko** [comment]
Passes the testsuite, https://cdash.kyomu.43-1.org/buildSummary.php?buildid=1477

**Comment by tamiko** [comment]
Wow. I think this doesn't compile with older clang (3.4.0). Let me check. http://www.math.clemson.edu/~heister/cib/dealii-tjhei-alpha/b509e726018ba3c8689158f0606867664039416e/log-clang

**Comment by drwells** [comment]
This is not compatible with sacado:

```
from ...dealii-dev/build/source/base/unity_1.cc:5:
...dealii-dev/include/deal.II/base/tensor.h: In instantiation of 'class dealii::Tensor<0, 1, Sacado::Rad::ADvar<double> >':
...dealii-dev/include/deal.II/base/tensor.h:408:60:   required from 'class dealii::Tensor<1, 1, Sacado::Rad::ADvar<double> >'
...dealii-dev/build/source/base/tensor.inst:331:8:   required from here
...dealii-dev/include/deal.II/base/tensor.h:220:11: error: 'dealii::Tensor<0, dim, Number>& dealii::Tensor<0, dim, Number>::operator=(const dealii::Tensor<0, dim, Number>&) [with int dim = 1
; Number = Sacado::Rad::ADvar<double>]' declared to take const reference, but implicit declaration would take non-const
   Tensor &operator = (const Tensor<0,dim,Number> &rhs) = default;
           ^~~~~~~~
...dealii-dev/include/deal.II/base/tensor.h: In instantiation of 'class dealii::Tensor<0, 1, Sacado::Rad::ADvar<float> >':
...dealii-dev/include/deal.II/base/tensor.h:408:60:   required from 'class dealii::Tensor<1, 1, Sacado::Rad::ADvar<float> >'
...dealii-dev/build/source/base/tensor.inst:336:8:   required from here
...dealii-dev/include/deal.II/base/tensor.h:220:11: error: 'dealii::Tensor<0, dim, Number>& dealii::Tensor<0, dim, Number>::operator=(const dealii::Tensor<0, dim, Number>&) [with int dim = 1
; Number = Sacado::Rad::ADvar<float>]' declared to take const reference, but implicit declaration would take non-const
...dealii-dev/include/deal.II/base/tensor.h: In instantiation of 'class dealii::Tensor<0, 1, Sacado::Rad::ADvar<Sacado::Fad::DFad<double> > >':
...dealii-dev/include/deal.II/base/tensor.h:408:60:   required from 'class dealii::Tensor<1, 1, Sacado::Rad::ADvar<Sacado::Fad::DFad<double> > >'
...dealii-dev/build/source/base/tensor.inst:341:8:   required from here
...dealii-dev/include/deal.II/base/tensor.h:220:11: error: 'dealii::Tensor<0, dim, Number>& dealii::Tensor<0, dim, Number>::operator=(const dealii::Tensor<0, dim, Number>&) [with int dim = 1
; Number = Sacado::Rad::ADvar<Sacado::Fad::DFad<double> >]' declared to take const reference, but implicit declaration would take non-const
```

**Comment by tamiko** [comment]
Yes, I realized as well: https://cdash.kyomu.43-1.org/buildSummary.php?buildid=1479
I have to calm down a bit and not merge wild-western style. Sorry for that. let's just revert.

**Comment by masterleinad** [comment]
> I have to calm down a bit and not merge wild-western style. Sorry for that. let's just revert.

Sorry for not checking with all dependencies enabled.

**Comment by drwells** [comment]
@masterleinad don't worry about it. This is such an innocuous looking change that I am amazed sacado has problems.

**Comment by tamiko** [comment]
@masterleinad @drwells We also have a week to figure out all necessary gcc-8 fixes. I suggest we make it a self-contained PR and test it with the full testsuite for `master`. We can then cherry-pick to the release branch when we feel confident about the changes.
