### ISSUE TITLE
Missing instantiations for `TrilinosWrappers::SparseMatrix::vmult` when compiling a user project linked against deal.II compiled with clang

### ISSUE THREAD

**Issue by tamiko** [dealii/dealii#17712]
When compiling the deal.II library itself with clang and a user project with gcc I run into a missing instantiation error:
```
mold: error: undefined symbol:
std::enable_if<is_same_v<dealii::LinearAlgebra::distributed::Vector<double, dealii::MemorySpace::Host>::value_type, double>, void>::type
dealii::TrilinosWrappers::SparseMatrix::vmult<dealii::LinearAlgebra::distributed::Vector<double, dealii::MemorySpace::Host> >(
    dealii::LinearAlgebra::distributed::Vector<double, dealii::MemorySpace::Host>&, 
    dealii::LinearAlgebra::distributed::Vector<double, dealii::MemorySpace::Host> const&) const
```

I can trigger a similar link error by compiling the user project with clang as well when switching to float:
```
mold: error: undefined symbol:
std::enable_if<is_same_v<dealii::LinearAlgebra::distributed::Vector<double, dealii::MemorySpace::Host>::value_type, double>, void>::type
dealii::TrilinosWrappers::SparseMatrix::vmult<dealii::LinearAlgebra::distributed::Vector<double, dealii::MemorySpace::Host> >(
    dealii::LinearAlgebra::distributed::Vector<double, dealii::MemorySpace::Host>&,
    dealii::LinearAlgebra::distributed::Vector<double, dealii::MemorySpace::Host> const&) const
```

The `vmult()` function is templated with `template <typename VectorType>`, so we must explicitly instantiate it. Judging from `source/lac/trilinos_sparse_matrix.cc` and `*.inst.in` it seems that we never explicitly instantiate the `vmult()` function?

Am I mistaken?

**Comment by kronbichler** [comment]
I agree, this looks strange. I think this goes back to #7180, where one commit makes this specific addition with `std::enable_if`. I think the problem is that we do instantiate the function with the signature `void`, but have the templated definition of the function with the signature `std::enable_if_v<...>` (that resolves to void eventually). To generate a clear ABI, we need to make the instantiations aware of the `enable_if_v` part I believe.

**Comment by masterleinad** [comment]
There defintely is https://github.com/dealii/dealii/blob/9d0a4890660f777214145e3b7de5d885f9bb8957/source/lac/trilinos_sparse_matrix.cc#L3043-L3046 which shoould complain if it can't find a template to instantiate.

**Comment by kronbichler** [comment]
Yes, that is correct, but I think the problem is the two different compilers, clang for deal.II, gcc for the application. (I'm not sure what the general expectation on this is.)

**Comment by masterleinad** [comment]
I'm seeing
```bash
$ nm -gU lib/libdeal_II.dylib | c++filt | grep "TrilinosWrappers::SparseMatrix::vmult" | grep "LinearAlgebra::distributed::Vector<double"
0000000003560034 T std::__1::enable_if<std::is_same_v<dealii::LinearAlgebra::distributed::Vector<double, dealii::MemorySpace::Host>::value_type, double>, void>::type dealii::TrilinosWrappers::SparseMatrix::vmult<dealii::LinearAlgebra::distributed::Vector<double, dealii::MemorySpace::Host>>(dealii::LinearAlgebra::distributed::Vector<double, dealii::MemorySpace::Host>&, dealii::LinearAlgebra::distributed::Vector<double, dealii::MemorySpace::Host> const&) const
00000000035611b4 T void dealii::TrilinosWrappers::SparseMatrix::vmult_add<dealii::LinearAlgebra::distributed::Vector<double, dealii::MemorySpace::Host>>(dealii::LinearAlgebra::distributed::Vector<double, dealii::MemorySpace::Host>&, dealii::LinearAlgebra::distributed::Vector<double, dealii::MemorySpace::Host> const&) const
```

**Comment by bangerth** [comment]
I think we should expect that names are mangled differently depending on how a type is specified, not only on what the type is. That is, `std::enable_if_t<true,int>` may be mangled differently than `int`. If declaration and definition use different ways to specify a type, that seems like a bug to me.

I think that the definition @masterleinad points to above is an explicit instantiation of this declaration in the `.h` file:
```
    template <typename VectorType>
    std::enable_if_t<
      std::is_same_v<typename VectorType::value_type, TrilinosScalar>>
    vmult(VectorType &dst, const VectorType &src) const;
```
and this definition in the .cc file:
```
  template <typename VectorType>
  std::enable_if_t<
    std::is_same_v<typename VectorType::value_type, TrilinosScalar>>
  SparseMatrix::vmult(VectorType &dst, const VectorType &src) const
```
The explicit instantiation should use the whole `std::enable_if_t` thing in exactly the way above, with `VectorType` replaced by the concrete vector type.

**Comment by tamiko** [comment]
@masterleinad I had to stare at it twice - but there is indeed a difference in name mangling:
```diff
-std::enable_if<std::is_same_v<dealii::LinearAlgebra::distributed::Vector<double, dealii::MemorySpace::Host>::value_type, double>, void>::type
+std::enable_if<is_same_v<dealii::LinearAlgebra::distributed::Vector<double, dealii::MemorySpace::Host>::value_type, double>, void>::type
 dealii::TrilinosWrappers::SparseMatrix::vmult<dealii::LinearAlgebra::distributed::Vector<double, dealii::MemorySpace::Host>>(
 dealii::LinearAlgebra::distributed::Vector<double, dealii::MemorySpace::Host>&,
 dealii::LinearAlgebra::distributed::Vector<double, dealii::MemorySpace::Host> const&) const
```

Fascinating.

**Comment by tamiko** [comment]
Oh, no :smile: 
The issue is that the variant:

_ZNK6dealii16TrilinosWrappers12SparseMatrix5vmultINS_13LinearAlgebra11distributed6VectorIfNS_11MemorySpace4HostEEEEENSt9enable_ifIXntsr3stdE9is_same_vINT_10value_typeEdEEvE4typeERSA_RKSA_

```
std::enable_if<!(std::is_same_v<dealii::LinearAlgebra::distributed::Vector<float, dealii::MemorySpace::Host>::value_type, double>), void>::type dealii::TrilinosWrappers::SparseMatrix::vmult<...>(..., ...)`
```
is not instantiated! (Note the `!`)

**Comment by masterleinad** [comment]
> Edit: Checked. Yes, this is precisely the issue:

So this just a incompatibility between `gcc` and `clang` and there is not much we can do about it?

**Comment by masterleinad** [comment]
> The second issue (compiling with clang again) is a separate bug: The symbol

Right. https://github.com/dealii/dealii/issues/17712#issue-2534562642 repeated the output from the first problem so I was a little confused but it makes sense given that we don't instantiate for mixed scalars.

**Comment by tamiko** [comment]
@masterleinad Yes. I will investigate and open a bug report for this.

Minimal reproducer:
```
#include <type_traits>

template <typename T>
typename std::enable_if<std::is_same_v<typename T::value_type, double>, void>::type foo() { }

struct bar { using value_type = double; };

template void foo<bar>();
```

**Comment by masterleinad** [comment]
> So you're saying that this compiles but doesn't link? That's a neat little example.

You are getting slightly different(?) symbols, see https://godbolt.org/z/vY338oo9r:
```
std::enable_if<is_same_v<bar::value_type, double>, void>::type foo<bar>():
```
for GCC and
```
std::enable_if<std::is_same_v<bar::value_type, double>, void>::type foo<bar>():
```
for clang.

**Comment by tamiko** [comment]
This seems to be a known issue: https://discourse.llvm.org/t/mangling-difference-between-gcc-and-clang/71364

**Comment by LemonBoy68** [comment]
Hi all,

I encountered a similar issue while compiling ASPECT with deal.II, both using the **Clang** compiler. The error is:

```md
undefined reference to 'std::array<std::pair<double, dealii::Tensor<1, 3, double> >, std::integral_constant<int, 3>::value> dealii::eigenvectors<3, double>(dealii::SymmetricTensor<2, 3, double> const&, dealii::SymmetricTensorEigenvectorMethod)'
```

It seems that the template function `dealii::eigenvectors<3, double>` is not instantiated for the specific types being used. Based on this issue's discussion, I suspect an explicit instantiation might be missing, similar to the problem with `TrilinosWrappers::SparseMatrix::vmult`.

Would an explicit instantiation of `dealii::eigenvectors<3, double>` solve this?

Thanks for any advice!

**Comment by bangerth** [comment]
@LemonBoy68 I tried to look into this, and it is complicated. The function in question was introduced in #4673. This was changed by @masterleinad in #6249 to work around a compiler issue in clang-6. But I think that the work-around really *is* necessary since I, too, observe that without the patch in #6249, you have to explicitly specify the template arguments (for reasons I don't actually understand). In any case, your best bet may be to also include `deal.II/base/symmetric_tensor.templates.h`. This should make the definition of the template available to the place where you use the function.
