### ISSUE TITLE
Compile error with get_fe_by_name

### ISSUE THREAD

**Issue by bangerth** [dealii/dealii#2873]
With gcc 4.4, I get the following compile error:
```
source/fe/fe_tools.inst:915:2: error: ambiguous template specialization ‘get_fe_by_name<1>’ for ‘dealii::FiniteElement<1, 1>* dealii::FETools::get_fe_by_name(const string&)’
/u/bangerth/p/deal.II/2/dealii/source/fe/fe_tools.cc:2560:3: error: candidates are: template<int dim, int spacedim> dealii::FiniteElement<dim, spacedim>* dealii::FETools::get_fe_by_name(const string&)
/u/bangerth/p/deal.II/2/dealii/source/fe/fe_tools.cc:2650:3: error:                 template<int dim> dealii::FiniteElement<dim, dim>* dealii::FETools::get_fe_by_name(const string&)
[...]
```
This is because we instantiate `get_fe_by_name` with only one template argument, but have these two functions in lines 2560 and 2650 of `fe_tools.cc`:
```
  template <int dim, int spacedim>
  FiniteElement<dim, spacedim> *
  get_fe_by_name (const std::string &parameter_name)
...
  template <int dim>
  FiniteElement<dim> *
  get_fe_by_name (const std::string &parameter_name)
  {
    return get_fe_by_name<dim,dim> (parameter_name);
  }
```

What's not quite clear to me is why we have the second one at all. It's not declared in the `fe_tools.h` file, so it's not visible to users. In other words, the compile error could be avoided altogether by just removing the second file and its instantiation.

@masterleinad -- I think you worked in this area last. Any insight?

**Comment by bangerth** [comment]
The issue was introduced with #2856.

**Comment by masterleinad** [comment]
Yes, this seems to be following me.

**Comment by masterleinad** [comment]
@bangerth I guess this can be closed.

**Comment by bangerth** [comment]
Yes, thanks @masterleinad , for fixing the issue.
