### ISSUE TITLE
Compilation error with PETSCSCALAR=std::complex

### ISSUE THREAD

**Issue by tamiko** [dealii/dealii#3199]
Something between merge b18df5d and d356c5d broke the petsc-scalar complex build [1]. But I am at a loss to find it.

[1] http://cdash.kyomu.43-1.org/viewBuildError.php?buildid=1702

**Comment by davydden** [comment]
`git bisect`?

**Comment by bangerth** [comment]
Somewhere in a new function we use a vector of doubles for individual entries where we should be using a vector of value_type of the global vector. I bet it is in the function that does the parallel extrapolation.  @masterleinad?

**Comment by tamiko** [comment]
Ah, yes. I should have scrolled down a bit and read the error message:
```
/.../dealii/include/deal.II/lac/petsc_vector_base.h:1251:31: error: cannot convert ‘PetscScalar {aka std::complex<double>}’ to ‘double’ in assignment

             *(values_begin+i) = *(ptr+index-begin);
                               ^
In file included from /.../dealii/include/deal.II/lac/block_vector.h:23:0,
                 from /.../dealii/source/fe/fe_tools_extrapolate.cc:22:
/.../dealii/include/deal.II/lac/block_vector_base.h: In instantiation of ‘void dealii::BlockVectorBase< <template-parameter-1-1> >::extract_subvector_to(ForwardIterator, ForwardIterator, OutputIterator) const [with ForwardIterator = const unsigned int*; OutputIterator = double*; VectorType = dealii::PETScWrappers::Vector]’:
/.../dealii/include/deal.II/dofs/dof_accessor.templates.h:3419:3:   required from ‘void dealii::DoFCellAccessor<DoFHandlerType, lda>::get_dof_values(const InputVector&, ForwardIterator, ForwardIterator) const [with InputVector = dealii::PETScWrappers::BlockVector; ForwardIterator = double*; DoFHandlerType = dealii::DoFHandler<2>; bool level_dof_access = false]’
/.../dealii/include/deal.II/dofs/dof_accessor.templates.h:3389:18:   required from ‘void dealii::DoFCellAccessor<DoFHandlerType, lda>::get_dof_values(const InputVector&, dealii::Vector<number>&) const [with InputVector = dealii::PETScWrappers::BlockVector; number = double; DoFHandlerType = dealii::DoFHandler<2>; bool level_dof_access = false]’
/.../dealii/source/fe/fe_tools_extrapolate.cc:563:15:   required from ‘void dealii::FETools::internal::ExtrapolateImplementation<<anonymous>, <anonymous> >::get_interpolated_dof_values(const typename dealii::internal::p4est::types<dim>::forest&, const typename dealii::internal::p4est::types<dim>::tree&, const typename dealii::internal::p4est::types<dim>::locidx&, const typename dealii::DoFHandler<dim, spacedim>::cell_iterator&, const typename dealii::internal::p4est::types<dim>::quadrant&, const InVector&, dealii::Vector<number>&, std::vector<dealii::FETools::internal::ExtrapolateImplementation<<anonymous>, <anonymous> >::CellData>&) [with InVector = dealii::PETScWrappers::BlockVector; number = double; int dim = 2; int spacedim = 2; typename dealii::internal::p4est::types<dim>::forest = p4est; typename dealii::internal::p4est::types<dim>::tree = p4est_tree; typename dealii::internal::p4est::types<dim>::locidx = int; typename dealii::DoFHandler<dim, spacedim>::cell_iterator = dealii::TriaIterator<dealii::DoFCellAccessor<dealii::DoFHandler<2>, false> >; typename dealii::internal::p4est::types<dim>::quadrant = p4est_quadrant]’
/.../dealii/source/fe/fe_tools_extrapolate.cc:1023:39:   required from ‘void dealii::FETools::internal::ExtrapolateImplementation<<anonymous>, <anonymous> >::compute_cells_in_tree_recursively(const typename dealii::internal::p4est::types<dim>::forest&, const typename dealii::internal::p4est::types<dim>::tree&, const typename dealii::internal::p4est::types<dim>::locidx&, const typename dealii::DoFHandler<dim, spacedim>::cell_iterator&, const typename dealii::internal::p4est::types<dim>::quadrant&, const InVector&, std::vector<dealii::FETools::internal::ExtrapolateImplementation<<anonymous>, <anonymous> >::CellData>&, std::vector<dealii::FETools::internal::ExtrapolateImplementation<<anonymous>, <anonymous> >::CellData>&, std::vector<dealii::FETools::internal::ExtrapolateImplementation<<anonymous>, <anonymous> >::CellData>&) [with InVector = dealii::PETScWrappers::BlockVector; int dim = 2; int spacedim = 2; typename dealii::internal::p4est::types<dim>::forest = p4est; typename dealii::internal::p4est::types<dim>::tree = p4est_tree; typename dealii::internal::p4est::types<dim>::locidx = int; typename dealii::DoFHandler<dim, spacedim>::cell_iterator = dealii::TriaIterator<dealii::DoFCellAccessor<dealii::DoFHandler<2>, false> >; typename dealii::internal::p4est::types<dim>::quadrant = p4est_quadrant]’
/.../dealii/source/fe/fe_tools_extrapolate.cc:970:45:   required from ‘void dealii::FETools::internal::ExtrapolateImplementation<<anonymous>, <anonymous> >::compute_cells(const dealii::DoFHandler<dim, spacedim>&, const InVector&, std::vector<dealii::FETools::internal::ExtrapolateImplementation<<anonymous>, <anonymous> >::CellData>&, std::vector<dealii::FETools::internal::ExtrapolateImplementation<<anonymous>, <anonymous> >::CellData>&, std::vector<dealii::FETools::internal::ExtrapolateImplementation<<anonymous>, <anonymous> >::CellData>&) [with InVector = dealii::PETScWrappers::BlockVector; int dim = 2; int spacedim = 2]’
/.../dealii/source/fe/fe_tools_extrapolate.cc:1246:25:   required from ‘void dealii::FETools::internal::ExtrapolateImplementation<<anonymous>, <anonymous> >::compute_all_non_local_data(const dealii::DoFHandler<dim, spacedim>&, const InVector&) [with InVector = dealii::PETScWrappers::BlockVector; int dim = 2; int spacedim = 2]’
/.../dealii/source/fe/fe_tools_extrapolate.cc:1318:34:   required from ‘void dealii::FETools::internal::ExtrapolateImplementation<<anonymous>, <anonymous> >::extrapolate_parallel(const InVector&, const dealii::DoFHandler<dim, spacedim>&, OutVector&) [with InVector = dealii::PETScWrappers::BlockVector; OutVector = dealii::PETScWrappers::BlockVector; int dim = 2; int spacedim = 2]’
/.../dealii/source/fe/fe_tools_extrapolate.cc:1615:9:   required from ‘void dealii::FETools::extrapolate(const dealii::DoFHandler<dim, spacedim>&, const InVector&, const dealii::DoFHandler<dim, spacedim>&, const dealii::ConstraintMatrix&, OutVector&) [with int dim = 2; InVector = dealii::PETScWrappers::BlockVector; OutVector = dealii::PETScWrappers::BlockVector; int spacedim = 2]’
/.../build-AwNMBxKw/source/fe/fe_tools_extrapolate.inst:1606:32:   required from here
```

**Comment by masterleinad** [comment]
I will have a look.

**Comment by bangerth** [comment]
I'm pretty sure this function
```
    template <int dim,int spacedim>
    template <class InVector,typename number>
    void
    ExtrapolateImplementation<dim,spacedim>::
    get_interpolated_dof_values (const typename dealii::internal::p4est::types<dim>::forest    &forest,
                                 const typename dealii::internal::p4est::types<dim>::tree      &tree,
                                 const typename dealii::internal::p4est::types<dim>::locidx    &tree_index,
                                 const typename DoFHandler<dim,spacedim>::cell_iterator        &dealii_cell,
                                 const typename dealii::internal::p4est::types<dim>::quadrant  &p4est_cell,
                                 const InVector                                                &u,
                                 Vector<number>                                                &interpolated_values,
                                 std::vector<CellData>                                         &new_needs)
```
should actually read
```
    template <int dim,int spacedim>
    template <class InVector>
    void
    ExtrapolateImplementation<dim,spacedim>::
    get_interpolated_dof_values (const typename dealii::internal::p4est::types<dim>::forest    &forest,
                                 const typename dealii::internal::p4est::types<dim>::tree      &tree,
                                 const typename dealii::internal::p4est::types<dim>::locidx    &tree_index,
                                 const typename DoFHandler<dim,spacedim>::cell_iterator        &dealii_cell,
                                 const typename dealii::internal::p4est::types<dim>::quadrant  &p4est_cell,
                                 const InVector                                                &u,
                                 Vector<typename InVector::value_type>       &interpolated_values,
                                 std::vector<CellData>                                    &new_needs)
```
(i.e., lose its `number` template argument). This will require redesigning the `CellData` structure which currently unconditionally stores `double` argument, when that should really be the data type of the input vector.
