### PR TITLE
Retire jammy testers. Update CUDA testers to noble.

### PR DESCRIPTION
**Pull request by marcfehling**
The 22.04/jammy images will be deprecated starting September 17th, 2026 and will be fully unsupported on April 17th, 2027[^1].

Our configuration already covers 24.04/noble and 26.04/resolute, so I think it is fair to let go of the 22.04/jammy jobs. This patch retires the jammy images and upgrades to resolute where possible.

The CUDA testers currently run on jammy. They require the backports repository which is not available on resolute (yet), so I updated the testers to noble instead in a separate commit. I also updated to clang 22 and CUDA 12.8, which is the latest fully supported version for clang 22[^3]. I followed nvidia's instructions for network installations[^2]. I also had to update Kokkos and picked the same version number we bundle with, which seemed to work. @masterleinad, @tjhei -- Please have a look!

The recently released clang 23 fully supports CUDA 13.2[^5]. We could also make this configuration work with an update to Kokkos 5[^4] in the future. I suggest to stick to clang 22 for the moment.

Part of #19184.

[^1]: https://github.com/actions/runner-images/issues/14254
[^2]: https://docs.nvidia.com/cuda/cuda-installation-guide-linux/#network-repo-installation-for-ubuntu
[^3]: https://github.com/llvm/llvm-project/blob/release/22.x/clang/include/clang/Basic/Cuda.h
[^4]: https://github.com/kokkos/kokkos/pull/8298
[^5]: https://github.com/llvm/llvm-project/blob/release/23.x/clang/include/clang/Basic/Cuda.h

### CODE REVIEW

**Comment by marcfehling** [comment]
I also hope that the updated configuration of the cuda repository will resolve the recent issues during the `modules` stage.

**Comment by masterleinad** [comment]
> I also had to update Kokkos and picked the same version number we bundle with, which seemed to work.

We require at least Kokkos 4.0 with GPU support and I'm not sure we are testing with that version anywhere else (even if it's just testing compilation). What kind of issues did you run into?

**Comment by marcfehling** [comment]
> What kind of issues did you run into?

I could not configure deal.II with Kokkos as cmake (version 3.31.6 on noble) had some issue importing a target `CUDA::cuda_driver`. I believe you fixed that in Kokkos 4.4.00 with https://github.com/kokkos/kokkos/pull/7062.

This is the cmake error I get:
```
-- Defining target: interface_kokkos
--     VERSION:             4.0.1
--     IMPORTED TARGETS:    Kokkos::kokkos
--     copying Kokkos::kokkos into interface_kokkos ...
--     copying Kokkos::kokkoscore into interface_kokkos ...
--     copying Kokkos::kokkoscontainers into interface_kokkos ...
--     copying Kokkos::kokkosalgorithms into interface_kokkos ...
--     copying Kokkos::kokkossimd into interface_kokkos ...
--     copying Kokkos::CUDA into interface_kokkos ...
--     copying Kokkos::LIBDL into interface_kokkos ...
--     copying CUDA::cuda_driver into interface_kokkos ...
CMake Warning (dev) at cmake/macros/macro_copy_target_properties.cmake:63 (get_target_property):
  Policy CMP0111 is not set: An imported target missing its location property
  fails during generation.  Run "cmake --help-policy CMP0111" for policy
  details.  Use the cmake_policy command to set the policy and suppress this
  warning.

  IMPORTED_LOCATION not set for imported target "CUDA::cuda_driver".
Call Stack (most recent call first):
  cmake/macros/macro_define_interface_target.cmake:143 (copy_target_properties)
  cmake/macros/macro_configure_feature.cmake:248 (define_interface_target)
  cmake/configure/configure_30_kokkos.cmake:22 (configure_feature)
  cmake/macros/macro_verbose_include.cmake:16 (include)
  CMakeLists.txt:140 (verbose_include)
This warning is for project developers.  Use -Wno-dev to suppress it.

CMake Error at cmake/macros/macro_copy_target_properties.cmake:83 (message):
  Undefined imported target name "CUDA::cudart_static_deps" present in
  interface of target "CUDA::cuda_driver".
Call Stack (most recent call first):
  cmake/macros/macro_define_interface_target.cmake:143 (copy_target_properties)
  cmake/macros/macro_configure_feature.cmake:248 (define_interface_target)
  cmake/configure/configure_30_kokkos.cmake:22 (configure_feature)
  cmake/macros/macro_verbose_include.cmake:16 (include)
  CMakeLists.txt:140 (verbose_include)


-- Configuring incomplete, errors occurred!
```

**Comment by marcfehling** [comment]
I checked a few more configurations using github actions on my fork.

- I can configure and compile deal.II with Kokkos 4.4.01 and CUDA 12.8 successfully. If you are fine with it, we can use this configuration.

- With Kokkos 4.4.01 and CUDA 12.5, I get an error during compilation of deal.II with nvcc. Seems fine with clang though.
```
/usr/lib/gcc/x86_64-linux-gnu/13/include/amxtileintrin.h(42): error: identifier "__builtin_ia32_ldtilecfg" is undefined
    __builtin_ia32_ldtilecfg (__config);
    ^

/usr/lib/gcc/x86_64-linux-gnu/13/include/amxtileintrin.h(49): error: identifier "__builtin_ia32_sttilecfg" is undefined
    __builtin_ia32_sttilecfg (__config);
    ^

2 errors detected in the compilation of "/home/runner/work/dealii/dealii/source/numerics/vector_tools_point_gradient.cc".
make[2]: *** [source/numerics/CMakeFiles/object_numerics_debug.dir/build.make:261: source/numerics/CMakeFiles/object_numerics_debug.dir/vector_tools_point_gradient.cc.o] Error 2
```

- With Kokkos 4.3.01 and CUDA 12.5 or 12.8, I cannot configure Kokkos in both nvcc and clang testers
```
-- Could not find nvcc executable in path specified by CUDAToolkit_ROOT=/usr/local/cuda
CMake Error at /usr/local/share/cmake-3.31/Modules/FindPackageHandleStandardArgs.cmake:233 (message):
  Could NOT find TPLCUDA (missing: FOUND_CUDART FOUND_CUDA_DRIVER)
```

**Comment by tjhei** [comment]
See https://github.com/dealii/dealii/issues/17401 (use bundled boost)

**Comment by masterleinad** [comment]
> * I can configure and compile deal.II with Kokkos 4.4.01 and CUDA 12.8 successfully. If you are fine with it, we can use this configuration.

I wouldn't support a (minimum) version that we can't (don't) test. If that means we need to make 4.4.01 the minimum, that's fine with me.

**Comment by marcfehling** [comment]
I downgraded the cmake version from 3.31.6 to 3.28.3. Then Kokkos 4.0.01 works fine with CUDA 12.8. I suggest to use this configuration instead of requiring a new minimum for Kokkos.

https://github.com/kokkos/kokkos/issues/7050 reported issues with CMake >=3.29.0, however I could confirm they already appear with >=3.28.4.

Are you okay with CUDA 12.8 as the latest supported version on clang? The oldest version nvidia provides on noble is 12.5, but we would need to force using the bundled boost as @tjhei pointed out.

**Comment by masterleinad** [comment]
> I downgraded the cmake version from 3.31.6 to 3.28.3. Then Kokkos 4.0.01 works fine with CUDA 12.8. I suggest to use this configuration instead of requiring a new minimum for Kokkos.

I prefer that solution.

> Are you okay with CUDA 12.8 as the latest supported version on clang? The oldest version nvidia provides on noble is 12.5, but we would need to force using the bundled boost as @tjhei pointed out.

Yeah, I don't think we need to woory about Cuda+Clang as much.

**Review by masterleinad — APPROVED** [review]
