### PR TITLE
Remove code deprecated in 9.8

### PR DESCRIPTION
**Pull request by masterleinad**
### Important License and other information

As a contributor to this project, you agree that all of your contributions to deal.II will
 - be governed by the [<b>Developer Certificate of Origin version 1.1</b>](https://developercertificate.org/), and
 - be made available to the project under the terms of the [<b>Apache License 2.0</b>](https://spdx.org/licenses/Apache-2.0.html) with [<b>LLVM Exception</b>](https://spdx.org/licenses/LLVM-exception.html), and
 - separately under the terms of the [<b>GNU Lesser General Public License v2.1 or later</b>](https://spdx.org/licenses/LGPL-2.1-or-later.html).
See the [deal.II license file](https://github.com/dealii/dealii/blob/master/LICENSE.md) for details.

 Furthermore, by submitting this pull request, you confirm that:
- You have read and agree to abide by the [Code of Conduct](https://github.com/dealii/dealii/blob/master/CODE_OF_CONDUCT.md).
- You have read the [contributing guidelines](https://github.com/dealii/dealii/blob/master/CONTRIBUTING.md).

### CODE REVIEW

File: tests/fe/rt_normal_02.cc [hunk 1]
```diff
@@ -106,9 +106,9 @@ evaluate_normal_component(const DoFHandler<2> &dof_handler,
                 (QProjector<2>::DataSetDescriptor::face(
                   ReferenceCells::Quadrilateral,
                   f,
-                  cell->face_orientation(f),
-                  cell->face_flip(f),
-                  cell->face_rotation(f),
+                  internal::combined_face_orientation(cell->face_orientation(f),
+                                                      cell->face_rotation(f),
+                                                      cell->face_flip(f)),
```
Comment (drwells) [inline tests/fe/rt_normal_02.cc]: Why not use `cell->combined_face_orientation(f)` here and elsewhere?

Comment (masterleinad) [reply tests/fe/rt_normal_02.cc]: I wasn't aware that there is a better replacement. 🙂

File: tests/fe/rt_normal_02.cc [hunk 2]
```diff
@@ -120,10 +118,7 @@ evaluate_normal_component(const DoFHandler<2> &dof_handler,
                 (QProjector<2>::DataSetDescriptor::face(
                   cell_n->reference_cell(),
                   neighbor,
-                  internal::combined_face_orientation(
-                    cell_n->face_orientation(neighbor),
-                    cell_n->face_rotation(neighbor),
-                    cell_n->face_flip(neighbor)),
+                  cell->combined_face_orientation(f),
```
Comment (drwells) [inline tests/fe/rt_normal_02.cc]: I think this needs to be `neighbor`.

File: tests/fe/rt_normal_02.cc [hunk 3]
```diff
@@ -120,9 +118,7 @@ evaluate_normal_component(const DoFHandler<2> &dof_handler,
                 (QProjector<2>::DataSetDescriptor::face(
                   cell_n->reference_cell(),
                   neighbor,
-                  cell_n->face_orientation(neighbor),
-                  cell_n->face_flip(neighbor),
-                  cell_n->face_rotation(neighbor),
+                  cell->combined_face_orientation(f),
```
Comment (masterleinad) [inline tests/fe/rt_normal_02.cc]:
```suggestion
                  cell->combined_face_orientation(neighbor),
```

File: tests/fe/rt_normal_02.cc [hunk 4]
```diff
@@ -120,9 +118,7 @@ evaluate_normal_component(const DoFHandler<2> &dof_handler,
                 (QProjector<2>::DataSetDescriptor::face(
                   cell_n->reference_cell(),
                   neighbor,
-                  cell_n->face_orientation(neighbor),
-                  cell_n->face_flip(neighbor),
-                  cell_n->face_rotation(neighbor),
+                  cell->combined_face_orientation(neighbor),
```
Comment (kronbichler) [inline tests/fe/rt_normal_02.cc]: Do we also need
```suggestion
                  cell_n->combined_face_orientation(neighbor),
```
to make this equivalent to the previous code?

**Comment by bangerth** [comment]
Can you rebase to get the stuck Jenkins tester going again?

**Comment by bangerth** [comment]
I'm afraid you'll have to rebase again :-( Is this ready to merge?

**Comment by masterleinad** [comment]
> I'm afraid you'll have to rebase again :-( Is this ready to merge?

Yes. The only deprecation this doesn't remove is the one introduced in https://github.com/dealii/dealii/pull/19971 since we don't have a replacement yet.

**Comment by bangerth** [comment]
Not sure what exactly is going on here:
```
/jenkins/workspace/dealii-mpi_PR-20090/include/deal.II/grid/tria_accessor.h:4218:3: error: ‘void dealii::CellAccessor<dim, spacedim>::set_neighbor(unsigned int, const dealii::TriaIterator<dealii::CellAccessor<dim, spacedim> >&) const’ cannot be overloaded with ‘void dealii::CellAccessor<dim, spacedim>::set_neighbor(unsigned int, const dealii::TriaIterator<dealii::CellAccessor<dim, spacedim> >&) const’
 4218 |   set_neighbor(const unsigned int                               face_no,
      |   ^~~~~~~~~~~~
/jenkins/workspace/dealii-mpi_PR-20090/include/deal.II/grid/tria_accessor.h:4145:3: note: previous declaration ‘void dealii::CellAccessor<dim, spacedim>::set_neighbor(unsigned int, const dealii::TriaIterator<dealii::CellAccessor<dim, spacedim> >&) const’
 4145 |   set_neighbor(const unsigned int                               i,
      |   ^~~~~~~~~~~~
[280/863] Building CXX object source/numerics/CMakeFiles/object_numerics_debug.dir/cell_data_transfer.cc.o
```

File: include/deal.II/grid/tria_accessor.h [hunk 5]
```diff
@@ -4133,6 +4133,18 @@ class CellAccessor : public TriaAccessor<dim, dim, spacedim>
...
+   * Set the neighbor @p i of this cell to the cell pointed to by @p pointer.
+   *
+   * This function shouldn't really be public (but needs to for various
+   * reasons in order not to make a long list of functions friends): it
+   * modifies internal data structures and may leave things. Do not use it
+   * from application codes.
+   */
+  void
+  set_neighbor(const unsigned int                               i,
+               const TriaIterator<CellAccessor<dim, spacedim>> &pointer) const;
```
Comment (bangerth) [inline include/deal.II/grid/tria_accessor.h]: This is probably the cause for the error. I don't think you wanted to add this function overload as part of a patch removing stuff :-)

Comment (bangerth) [reply include/deal.II/grid/tria_accessor.h]: Indeed, that function already exists in the `protected` part of the class. Just removes these lines here.

File: include/deal.II/sundials/arkode.h [hunk 6]
```diff
@@ -153,59 +153,6 @@ namespace SUNDIALS
...
-       *
-       * Error parameters:
-       *
-       * @param absolute_tolerance Absolute error tolerance
-       * @param relative_tolerance Relative error tolerance
-       */
-      DEAL_II_DEPRECATED_WITH_COMMENT(
-        "Use another constructor and ARKStepper::AdditionalData to initialize "
-        "with the ARKStepper relevant parameters instead.")
-      AdditionalData(
```
Comment (bangerth) [inline include/deal.II/sundials/arkode.h:191]: I wonder whether we made a mistake here. These functions were only deprecated after 9.7 and before 9.8, in #19282. We should have early-deprecated things then. Can you undo all of the changes to the SUNDIALS wrappers in `include/deal.II/sundials/` and `source/sundials/`?

@vovannikov FYI

File: tests/sundials/arkode_repeated_solve_in.prm [hunk 7]
```diff
@@ -9,7 +9,5 @@ end
 
 subsection Running parameters
   set Initial step size                      = 1e-6
-  set Maximum number of nonlinear iterations = 10
-  set Maximum order of ARK                   = 5
```
Comment (bangerth) [inline tests/sundials/arkode_repeated_solve_in.prm:13]: Undo this as well then.

**Review by bangerth — COMMENTED** [review]
Looks good to me with the exception of the SUNDIALS changes where we made a mistake in deprecating instead of early-deprecating.

File: include/deal.II/grid/tria_accessor.h [hunk 8]
```diff
@@ -4133,6 +4133,18 @@ class CellAccessor : public TriaAccessor<dim, dim, spacedim>
...
+
```
Comment (masterleinad) [inline include/deal.II/grid/tria_accessor.h]:
```suggestion
```

**Review by marcfehling — APPROVED** [review]
Would you also add a short changelog entry like in #18709?

**Review by kronbichler — APPROVED** [review]

**Comment by masterleinad** [comment]
> Would you also add a short changelog entry like in #18709?

Let me do that in a follow-up that also documents https://github.com/dealii/dealii/pull/20082.
