### ISSUE TITLE
bessel_j undeclared

### ISSUE THREAD

**Issue by VictorEijkhout** [dealii/dealii#9134]
[deallog.zip](https://github.com/dealii/dealii/files/3914666/deallog.zip)
I'm trying to build with gcc 7.1

```
In file included from /admin/build/admin/rpms/stampede2/BUILD/dealii-9.1.1/source/base/function_lib.cc:20:0:
/admin/build/admin/rpms/stampede2/BUILD/dealii-9.1.1/include/deal.II/base/std_cxx17/cmath.h: At global scope:
/admin/build/admin/rpms/stampede2/BUILD/dealii-9.1.1/include/deal.II/base/std_cxx17/cmath.h:37:14: error: 'std::cyl_bessel_j' has not been declared
   using std::cyl_bessel_j;
              ^~~~~~~~~~~~
/admin/build/admin/rpms/stampede2/BUILD/dealii-9.1.1/include/deal.II/base/std_cxx17/cmath.h:38:14: error: 'std::cyl_bessel_jf' has not been declared
   using std::cyl_bessel_jf;
              ^~~~~~~~~~~~~
/admin/build/admin/rpms/stampede2/BUILD/dealii-9.1.1/include/deal.II/base/std_cxx17/cmath.h:39:14: error: 'std::cyl_bessel_jl' has not been declared
   using std::cyl_bessel_jl;
              ^~~~~~~~~~~~~
```

Do you want the log file which is only 19k lines?

**Comment by masterleinad** [comment]
You have
> cmake -VV -DCMAKE_INSTALL_PREFIX=/home1/apps/gcc7_1/impi18_0/dealii/9.1.1 -DDEAL_II_WITH_CXX11=ON -DDEAL_II_WITH_CXX14=ON '-DDEAL_II_CXX_FLAGS_DEBUG=-std=c++14 -g -march=broadwell -mtune=knl -I/opt/intel/compilers_and_libraries_2018.2.199/linux//include -O0' '-DDEAL_II_CXX_FLAGS_RELEASE=-std=c++14 -g -march=broadwell -mtune=knl -I/opt/intel/compilers_and_libraries_2018.2.199/linux//include -O2' -DDEAL_II_WITH_MPI=ON -DMPICH_IGNORE_CXX_SEEK=ON -DDEAL_II_COMPONENT_MESH_CONVERTER=ON -DDEAL_II_WITH_BOOST=ON -DBOOST_DIR=/opt/apps/gcc7_1/boost/1.64 -DDEAL_II_WITH_GSL=ON -DGSL_INCLUDE_DIR=/opt/apps/gcc7_1/gsl/2.3/include -DGSL_LIBRARY_DIR=/opt/apps/gcc7_1/gsl/2.3/lib '-DGSL_LIBRARY=/opt/apps/gcc7_1/gsl/2.3/lib/libgsl.so;/opt/apps/gcc7_1/gsl/2.3/lib/libgslcblas.so' -DHDF5_DIR= -DDEAL_II_WITH_PETSC=ON -DDEAL_II_WITH_SLEPC=ON -DPETSC_DIR=/home1/apps/gcc7_1/impi18_0/petsc/3.11/ -DPETSC_ARCH=skylake -DDEAL_II_WITH_P4EST=ON -DP4EST_DIR= -DDEAL_II_WITH_TRILINOS=ON -DTRILINOS_DIR=/home1/apps/gcc7_1/impi18_0/trilinos/12.18.1/ /admin/build/admin/rpms/stampede2/BUILD/dealii-9.1.1/dealii-9.1.1 /admin/build/admin/rpms/stampede2/BUILD/dealii-9.1.1

for configuring `deal.II`. Since you didn't set `DEAL_II_WITH_CXX17=OFF` and `gcc-7.1` supports C++17, this results in `DEAL_II_WITH_CXX17=ON`. On the other hand, you are setting version flags (`-std=c++14` manually) and we end up with different effective flags for the feature check and at build time. 
Just don't do that. It should work once you remove the explicit version flags in `DEAL_II_CXX_FLAGS*`.

I would also expect not to see the issue in the current developer version since we ware not relying on feature checks.

**Comment by Rombur** [comment]
Looks like deal.II was configured with c++ 17 but it is not compiled with the c++17 flag.

**Comment by bangerth** [comment]
@VictorEijkhout -- has this been resolved?

**Comment by VictorEijkhout** [comment]
Probably. I'm still struggling with oher issues. Let's close this.
