### ISSUE TITLE
sundials 4.x support

### ISSUE THREAD

**Issue by davydden** [dealii/dealii#7597]
deal won't build with `sundials 4.0`:

```
In file included from /Users/davydden/spack/var/spack/stage/dealii-develop-5vwbosjcavai5ao5mccewnakp3wupaz6/dealii/source/sundials/arkode.cc:19:
In file included from /Users/davydden/spack/var/spack/stage/dealii-develop-5vwbosjcavai5ao5mccewnakp3wupaz6/dealii/include/deal.II/sundials/arkode.h:38:
/Users/davydden/spack/opt/spack/darwin-mojave-x86_64/clang-10.0.0-apple/sundials-4.0.1-5za3vcazzodfej5awpcbaxjp6amhpntq/include/arkode/arkode_impl.h:27:10: fatal error: 'arkode_adapt_impl.h' file not found
#include "arkode_adapt_impl.h"
         ^~~~~~~~~~~~~~~~~~~~~
1 error generated.
```

@gardner48 commented on https://github.com/spack/spack/issues/10321#issuecomment-453765062

> Historically Sundials *_impl.h files were installed to allow for interfacing user supplied linear solvers with Sundials packages but with the new SUNLinearSolver API added in v3.0 *_impl.h files no longer need to be installed and will not be installed in future releases. This issue did not show up with v3.2.1 as ARKode was restructured in v4.0.0 which added new *_impl.h files.

**Comment by masterleinad** [comment]
I am not sure how this is a `deal.II` issue. `ArkodeMem` for example is only defined in `arkode/arkode_impl.h` and that header includes files that are not installed.

**Comment by davydden** [comment]
Maybe we can’t use ArkodeMem anymore? I guess those headers should have never been installed in 4.x in the first place, perhaps @gardner48 could further clarify this?

**Comment by gardner48** [comment]
Yes that right. In versions of Sundials before v3.0 it was necessary know how ARKodeMem is defined in order to set internal function pointers for providing an external linear solver. Starting with v3.0 we added the SUNLinearSolver API and it's no longer necessary to reach into the ARKode memory structure to provide an external linear solver. So the ARKodeMem structure returned by `ARKStepCreate` (previously `ARKodeCreate`) should be treated as `void *` and the `*_impl.h` files do not need to be installed. Will we be updating the build system to not install these files in a later release.

The reason this problem shows up specifically for the `deal.II` interface to ARKode but not IDA or KINSOL is the ARKode package was essentially rewritten for v4.0 to support different time stepper modules. This update added several new `*_impl.h` files that are not installed. When the IDA and KINSOL `*_impl.h` files are not installed in a future release this same issue will show up for those packages as well.

**Comment by masterleinad** [comment]
This is non-trivial and there is no high demand for it. Let's move it to the next milestone.

**Comment by tamiko** [comment]
@luca-heltai @masterleinad *ping* Is this on someone's radar at the moment?

**Comment by masterleinad** [comment]
Not on mine.
