### PR TITLE
Add more static asserts for sensible template parameters

### PR DESCRIPTION
**Pull request by kalj**
Adding compile time checks of template parameters to `Triangulation` and `FiniteElement`. See #3621.

### CODE REVIEW

**Comment by kronbichler** [comment]
@kalj there seem to be compile errors due to the static assert in the triangulation. Could you please have a look here:
http://www.math.clemson.edu/~heister/cib/dealii-tester-alpha/cb51f066de3f992d081cb571ff992b91f81c2a51/log-clang

**Comment by kalj** [comment]
That's interesting. It chokes on the following three lines at the end of `tria.h` (note the very confusing comment):

```
// -------------------------------------------------------------------
// Explicit invalid things...
template <>
const Manifold<2,1> &Triangulation<2, 1>::get_manifold(const types::manifold_id) const;
template <>
const Manifold<3,1> &Triangulation<3, 1>::get_manifold(const types::manifold_id) const;
template <>
const Manifold<3,2> &Triangulation<3, 2>::get_manifold(const types::manifold_id) const;
```
Does anyone know why those are there? 

There are matching, equally puzzling implementations at the end of `tria.cc`. It seems this was introduced in commit 9079b697 due to some issue with `FlatManifold` where `TriaAccessor` actually needed those invalid combinations. Ping @tamiko.

**Comment by kalj** [comment]
Related issue: #56

**Comment by bangerth** [comment]
Sigh. I learn something new every day. 

But much has changed since #56. Can you try to just remove the offending lines and see what happens?

**Comment by kalj** [comment]
Tried that, but then I got compilation errors on line 398 and 476 in `source/fe/mapping_q_generic.cc`, where `internal::MappingQ1::compute_shape_function_values` is explicitly implemented for `dim` 1 to 3. That then refers to types like `dealii::MappingQGeneric<3, 2>` which after a long chain ends up in `include/deal.II/grid/tria_boundary.h` and `include/deal.II/grid/manifold.h` from where iterators in `Triangulation<3,2>` are referred.

It turns out this is an internal function in that file which are only ever call from line 857, where they are explicitly guarded in an if statement checking for `dim==spacedim`, so the situation is avoidable. If I do some reshuffling into explicitly specialized functions, I manage to avoid the error.

However, I then run into other errors which I am looking into now.

Life is indeed interesting.

**Comment by kalj** [comment]
Several errors were generated because other explicit instantiations in `.inst.in` files were not conforming to this condition (`dim<=spacedim`). The causes were `FunctionManifold` and `ChartManifold` which both adds another parameter `chartdim` which according to the documentation (line 849 in `include/deal.II/grid/manifold.h`) should never be larger than `dim`. If I introduced criteria for this in `manifold.inst.in` and for `FunctionManifold` in `manifold_lib.inst.in` respectively, many errors went away. However, another error occurs since `ChartManifold` stores a `FlatManifold<dim,chartdim>` internally (line 1032 in `include/deal.II/grid/manifold.h`) which clearly gives rise to an invalid combination of parameters if `chartdim < dim`. As it looks now, it is unclear to me if that is ever a valid case, or if we can extend the condition in the instantiation to `dim <= chardim <= spacedim`. Does anyone with more insight into the Manifold stuff know about this?

**Comment by bangerth** [comment]
I don't remember the manifold things well enough, and don't have the bandwidth this week to look into this given that I'm on the other side of the globe. @luca-heltai -- do you remember?

I think that we ought to get rid of all instantiations where `dim>spacedim`. If you have individual changes that separately already work and that get us in this direction, feel free to submit them as separate pull requests to already get them out of the way. This would allow us to focus on the real issues without having to conflate things with changes that are related in nature, but ultimately unrelated to the problem you describe above.

**Comment by luca-heltai** [comment]
I remember this happening when the compiler was trying to return a reference to a never-built invalid object. I remember @tamiko giving a nice suggestion in that case... 

Anyway, to answer to one of the questions above, `dim <= chartdim <= spacedim` is in general false. A `chartdim = 1` is perfectly valid in `dim = 2` (it is a chart describing a line, for example in a boundary description in two dimensions). 

The condition that should be checked is `dim <=spacedim && chartdim <= spacedim`. In particular also the condition `chartdim > dim` is valid (think of a surface embedded in a euclidean space, where you describe the *embedding* space, rather than the *embedded* one...).

Can you be more specific in the errors you hit?

**Comment by kalj** [comment]
I just pushed some commits but I'll submit them as separate pull requests as @bangerth suggests.

**Comment by kalj** [comment]
@luca-heltai If I only enforce `dim<=spacedim && chartdim <= spacedim` I get lots of errors like these:
```
In file included from [...]/include/deal.II/grid/manifold.h:28:0,
                 from [...]/source/grid/manifold.cc:17:
[...]/include/deal.II/grid/tria.h: In instantiation of ‘class dealii::Triangulation<2, 1>’:
[...]/source/grid/manifold.cc:328:1:   required from ‘class dealii::Manifold<2, 1>’
[...]/include/deal.II/grid/manifold.h:634:7:   required from ‘class dealii::FlatManifold<2, 1>’
[...]/include/deal.II/grid/manifold.h:1032:36:   required from ‘class dealii::ChartManifold<2, 2, 1>’
[...]/source/grid/manifold.inst:184:17:   required from here
[...]/include/deal.II/grid/tria.h:3460:3: error: static assertion failed: The dimension <dim> of a Triangulation must be less than or equal to the space dimension <spacedim> in which it lives.
   static_assert (dim<=spacedim,
```
If I added `dim <= chartdim` all errors go away. I assume you made a typo; are you saying that this should be sharpened to `dim < chartdim`?

**Comment by luca-heltai** [comment]
Please, fix the indentation...

**Comment by luca-heltai** [comment]
The condition `chartdim < dim` should be possible. In fact, there are classes in the library that make use of it. For example:

https://dealii.org/8.4.1/doxygen/deal.II/classOpenCASCADE_1_1ArclengthProjectionLineManifold.html

This is a line description (`chartdim = 1`) in `dim = 2` and `spacedim = 3`.

**Comment by kalj** [comment]
@luca-heltai I have some trouble wrapping my head around this, but if I understand you right, both `Manifold<2,1>` and `Manifold<1,2>` make sense? Then we need to reconsider the condition for `Triangulation`, since `Manifold<dim,spacedim>::get_new_point_on_line` refers `Triangulation<dim,spacedim>::line_iterator`.

**Comment by luca-heltai** [comment]
`Triangulation<2,1>` should never be instantiated. `Manifold<X,spacedim>` never uses `X` internally.

The instantiations are there for invalid objects (like line_iterator<2,1>). In fact they are derived from 

https://www.dealii.org/8.4.1/doxygen/deal.II/classInvalidAccessor.html

The problem is that somewhere a **Triangulation** is instantiated. The accessors themselves 

InvalidAccessors<structdim,dim,spacedim>, are valid objects for all `structdim`, `dim`, and `spacedim`, that should not be built (they throw exception upon build), but that are instantiated.

Somewhere, somebody is creating a `Triangulation`:

`/include/deal.II/grid/tria.h: In instantiation of ‘class dealii::Triangulation<2, 1>’:`

This should not happen. But invalid objects like the ones above are perfectly fine.

**Comment by luca-heltai** [comment]
`Triangulation<dim,spacedim>::line_iterator` is a typedef for an invalid accessor. It does not require instantiatin of a Triangulation. If static checks require instantiations, then we have a problem.

**Comment by bangerth** [comment]
In order to find out what the typedef `Triangulation<dim,spacedim>::line_iterator` is, you need to look into (instantiate) the surrounding class :-)

If that is an invalid operation, the only way around it I can see is to not use the `Triangulation<dim,spacedim>::line_iterator` typedef, but use what the `Triangulation` class uses to define the typedef:
```
class Triangulation {
  ...
  typedef dealii::internal::Triangulation::Iterators<dim, spacedim> IteratorSelector;
  typedef typename IteratorSelector::line_iterator        line_iterator;
```
In other words, in those places where we currently use `Triangulation<dim,spacedim>::line_iterator`, we could just use `dealii::internal::Triangulation::Iterators<dim, spacedim>::line_iterator` and similarly for the other iterator classes. This should work around the issue.

Of course, the original sin was to make the `Manifold` class dependent on the triangulation at all. It is a geometric concept, independent of a mesh, and should have been independent of the `Triangulation` class. It is too late for this, I'm afraid.

**Comment by bangerth** [comment]
On 11/23/2016 07:27 AM, Karl Ljungkvist wrote:
> @luca-heltai <https://github.com/luca-heltai> I have some trouble wrapping my
> head around this, but if I understand you right, both |Manifold<2,1>| and
> |Manifold<1,2>| make sense?

That can't make sense, right? You can't have a 2-dimensional manifold in a 
one-dimensional space...

**Comment by kalj** [comment]
Just to elaborate on what @bangerth just said: Then I understand that `dim>chartdim` is a logical case for `ChartManifold`. But internally, a `FlatManifold<dim,chartdim>` is used as a member, and that would be a `dim`-dimensional manifold embedded in `chartdim` dimensions. I get the impression that a `Manifold` conceptually always has `dim<spacedim`, correct?

**Comment by kalj** [comment]
Alright, I tried making the replacements @bangerth suggested (`Triangulation<X,Y>::Z_iterator` -> `internal::Triangulation::Iterators<X,Y>::Z_iterator`). However, the problem is that the `TriaAccessor` underlying each iterator is then instantiated for the invalid template parameters, and these internally store a pointer to a `Triangulation`.

The error now looks like this:
```
[..]/include/deal.II/grid/tria.h: In instantiation of ‘class dealii::Triangulation<3, 1>’:
[..]/include/deal.II/grid/tria_accessor.templates.h:1181:61:   required from ‘dealii::Point<spacedim>& dealii::TriaAccessor<<anonymous>, <anonymous>, <anonymous> >::vertex(unsigned int) const [with int structdim = 2; int dim = 3; int spacedim = 1]’
[..]/source/grid/manifold.cc:318:27:   required from ‘void dealii::Manifold<dim, spacedim>::get_normals_at_vertices(const face_iterator&, dealii::Tensor<1, spacedim> (&)[dealii::GeometryInfo<structdim>::vertices_per_face]) const [with int dim = 3; int spacedim = 1; dealii::Manifold<dim, spacedim>::face_iterator = dealii::TriaIterator<dealii::TriaAccessor<2, 3, 1> >; dealii::Manifold<dim, spacedim>::FaceVertexNormals = dealii::Tensor<1, 1, double> [4]]’
[..]/source/grid/manifold.cc:697:1:   required from here
[..]/include/deal.II/grid/tria.h:3460:3: error: static assertion failed: The dimension <dim> of a Triangulation must be less than or equal to the space dimension <spacedim> in which it lives.
```
I still don't fully understand if these instantiations are actually used, or if it is just an artifact of how types are used?

**Comment by luca-heltai** [comment]
Manifold does **not** depend on the mesh. We should get rid of all the backward dependent concepts (get_new_point_on_XXXX) that were there for backward compatibility with Boundary classes. I think it is time we do this step.

The only necessary thing is the `get_new_point(points,weights)`

**Comment by luca-heltai** [comment]
The `dim` template parameter in the `Manifold` class is never used, except in the backward compatible interfaces. Conceptually a Manifold is a collection of points equipped with a metric. The `dim` parameter was necessary because of backward compatibility requirements with `Boundary` classes. We were not (or better... I was not) able to write these classes without having the `dim` parameter as well...

**Comment by luca-heltai** [comment]
Storing a (empty) pointer to non instantiated class is perfectly valid, so I don't fully understand why Triangulation<2,1> keeps getting instantiated...

**Comment by kalj** [comment]
@luca-heltai The troubles appeared when we introduced the `static_assert` inside the class declaration. I guess that makes the type itself invalid, including a references or pointers to that type or anything inside it.

**Comment by kalj** [comment]
@luca-heltai That's interesting. There are a decent number of references to `get_new_point_on_*`, but if all can essentially be replaced by some boilerplate code + `get_new_point`, then it should be fairly doable.

**Comment by luca-heltai** [comment]
I think the real problem is here:

~~~
template <int structdim, int dim, int spacedim>
Point<spacedim> &
TriaAccessor<structdim, dim, spacedim>::vertex (const unsigned int i) const
{
  return const_cast<Point<spacedim> &> (this->tria->vertices[vertex_index(i)]);
}
~~~

this function is called by `get_normals_at_vertices` with an invalid iterator for some flat manifolds. Of course an invalid tria accessor would trigger the instantiation of an invalid triangulation (this->tria) from here:

~~~
template <int dim, int spacedim>
void
Manifold<dim, spacedim>::
get_normals_at_vertices (const typename Triangulation<dim, spacedim>::face_iterator &face,
                         FaceVertexNormals &n) const
{
  for (unsigned int v=0; v<GeometryInfo<dim>::vertices_per_face; ++v)
    {
      n[v] = normal_vector(face, face->vertex(v));
      n[v] /= n[v].norm();
    }
}
~~~

we cannot call this for invalid iterators. In the past, invalid objects were instantiated and threw errors upon construction. Now you don't want to construct them anymore... This is clearly better, but it makes dimension independent programming much more intricated... 

We should throw an error as the default implementation, since the only cases  that make sense are already implemented...

**Comment by bangerth** [comment]
I don't think I have the time to track this down fully, but I found it helpful in looking at stuff to add the static-assertion also to class `Manifold`.

**Comment by bangerth** [comment]
Just to clarify and emphasize a comment made earlier on by @kalj : The issue is that we have
```
template <int dim, int spacedim=dim, int chartdim=dim>
class ChartManifold : public Manifold<dim,spacedim>
{
  ...
  const FlatManifold<dim,chartdim> sub_manifold;
};
```
Conceptually, `ChartManifold<dim,spacedim,chartdim>` is a manifold (of dimension `dim`, though that is immaterial) that lives in `spacedim` dimensional space, and that is parameterized by charts of dimension `chartdim`. 

It is clear that we need `chartdim>=dim` because otherwise we cannot span the entire manifold. But, as has been pointed out, we do not know any relationship between `spacedim` and `chartdim`. In any case, this would call for the following in class `ChartManifold`:
```
    // explicitly check for sensible template arguments
  #ifdef DEAL_II_WITH_CXX11
    static_assert (dim<=spacedim,
                   "The dimension <dim> of a ChartManifold must be less than or "
                   "equal to the space dimension <spacedim> in which it lives.");
    static_assert (dim<=chartdim,
                   "The dimension <chartdim> of a ChartManifold must be greater than or "
                   "equal to the dimension <dim> of the manifold it describes.");
  #endif
```

At present, this is violated by the following in `manifold_lib.inst.in`:
```
for (deal_II_dimension : DIMENSIONS; deal_II_space_dimension :  SPACE_DIMENSIONS; deal_II_chart_dimension :  DIMENSIONS)
{
#if deal_II_dimension <= deal_II_space_dimension
#if deal_II_chart_dimension <= deal_II_space_dimension
    template class FunctionManifold<deal_II_dimension, deal_II_space_dimension, deal_II_chart_dimension>;
#endif
#endif
}
```
I think this should actually read like this:
```
for (deal_II_dimension : DIMENSIONS; deal_II_space_dimension :  SPACE_DIMENSIONS; deal_II_chart_dimension :  DIMENSIONS)
{
#if deal_II_dimension <= deal_II_space_dimension
#if deal_II_dimension <= deal_II_chart_dimension
    template class FunctionManifold<deal_II_dimension, deal_II_space_dimension, deal_II_chart_dimension>;
#endif
#endif
}
```

Would you agree with this reasoning, @luca-heltai ?

**Comment by luca-heltai** [comment]
@bangerth , actually no. As I pointed out before, `chartdim` can be smaller than `dim` if the manifold you are using, for example, describes curves. This Manifold can be used for dim =1,2,3, and for dim<=spacedim=1,2,3. 

Any Triangulation wishing to use the description of  a line, can attach a `ChartManifold<dim,spacedim,1>` to edges (dim = 3), faces (dim = 2) or cells (dim = 1). `ChartManifold` will internally instantiate a `const FlatManifold<dim,chartdim> sub_manifold` (where the `dim` is irrelevant and never actually used).

The problem comes from the attempt at being backward compatible. There are functions which were defined in Boundary (such as get_new_point_on_XXX, or get_normals_at_vertices) that require instantiating a Triangulation. The only real issue is the one I pointed to @kalj. 

The fix I suggested above does not change anything of what is implemented in the library (we have no Manifold capable of describing normals at vertices of faces in dim != spacedim, and the cases <2,2> and <3,3> are implemented already as a specialization). This function should really be implemented by  developers of new Manifold classes, and no general solution can work.

This is the most reasonable solution:
~~~
template <int dim, int spacedim>
void
Manifold<dim, spacedim>::
get_normals_at_vertices (const typename Triangulation<dim, spacedim>::face_iterator &,
                         FaceVertexNormals &) const {
    Assert (false, ExcPureFunctionCalled());
}
~~~

None of the Manifold in the library will be affected by this (only some of the manifolds we have for dimension <2,3> in our group).

**Comment by bangerth** [comment]
> Any Triangulation wishing to use the description of a line, can attach a
> |ChartManifold<dim,spacedim,1>| to edges (dim = 3), faces (dim = 2) or cells
> (dim = 1). |ChartManifold| will internally instantiate a |const
> FlatManifold<dim,chartdim> sub_manifold| (where the |dim| is irrelevant and
> never actually used).

Hm. It is unfortunate that a 1d line embedded in 3d still needs to say that 
dim==2 if it wants to describe edges of a 2d triangulation embedded in 3d :-( 
We really did get this wrong.

I did try to replace the replace the declaration of `sub_manifold` from
   FlatManifold<dim,chartdim>
to
   FlatManifold<chartdim,chartdim>
This seems to work, but I haven't completely tested it. Would such a change 
find your favor? It avoids the unfortunate instantiations of class Manifold.

**Comment by luca-heltai** [comment]
If that works, and no tests fails, than that is the correct solution. As soon as we remove all the backward compatibility functions, I'll make a full restyling of the Manifold class, dropping the first template parameter (as it ought to be).

**Comment by bangerth** [comment]
Can you please rebase this to current master? I think this should now work.

**Comment by kalj** [comment]
Done!

**Comment by bangerth** [comment]
Great, thanks!
