### ISSUE TITLE
New failing tests / new build failures

### ISSUE THREAD

**Issue by tamiko** [dealii/dealii#4880]
Recent changes introduced a lot of failing tests [1] and build errors [2].

Can someone please have a look?

[1] https://cdash.kyomu.43-1.org/viewTest.php?onlydelta&buildid=10203

[2] https://cdash.kyomu.43-1.org/viewBuildError.php?onlydeltap&buildid=10218

**Comment by drwells** [comment]
I opened an equivalent issue at the same time: lets go with this one.

Here is what I get:

```
/usr/include/boost/archive/detail/oserializer.hpp:310:22:   [ skipping 23 instantiation contexts, use -ftemplate-backtrace-limit=0 to disable ]
/usr/include/boost/archive/detail/interface_oarchive.hpp:70:9:   required from
‘Archive& boost::archive::detail::interface_oarchive<Archive>::operator<<(const T&)
[with T = dealii::parallel::GridTools::internal::CellDataTransferBuffer<1, unsigned int>;
Archive = boost::archive::binary_oarchive]’
/home/drwells/Documents/Code/CPP/dealii-dev/include/deal.II/distributed/grid_tools.h:210:21:
required from ‘std::vector<char> dealii::parallel::GridTools::internal::CellDataTransferBuffer<dim, T>::pack_data() const
[with int dim = 1; T = unsigned int]’
/home/drwells/Documents/Code/CPP/dealii-dev/include/deal.II/distributed/grid_tools.h:346:28:
required from ‘void dealii::parallel::GridTools::exchange_cell_data_to_ghosts
(const MeshType&, std::function<boost::optional<T>(const typename
MeshType::active_cell_iterator&)>, std::function<void(const typename MeshType::active_cell_iterator&, const DataType&)>)
[with DataType = unsigned int; MeshType = dealii::hp::DoFHandler<1, 1>;
typename MeshType::active_cell_iterator = dealii::TriaActiveIterator<dealii::DoFCellAccessor<dealii::hp::DoFHandler<1, 1>, false> >]’
/home/drwells/Documents/Code/CPP/dealii-dev/source/hp/dof_handler.cc:935:19:
required from ‘static void dealii::internal::hp::DoFHandler::Implementation::communicate_active_fe_indices(dealii::hp::DoFHandler<dim, spacedim>&) [with int dim = 1; int spacedim = 1]’
/home/drwells/Documents/Code/CPP/dealii-dev/source/hp/dof_handler.cc:1291:85:
required from ‘void dealii::hp::DoFHandler<dim, spacedim>::distribute_dofs(const dealii::hp::FECollection<dim, spacedim>&) [with int dim = 1; int spacedim = 1]’
/home/drwells/Documents/Code/CPP/dealii-dev/build/source/hp/dof_handler.inst:12:17:   required from here
/usr/include/boost/serialization/access.hpp:116:11: error: ‘struct std::array<unsigned int, 4>’ has no member named ‘serialize’
         t.serialize(ar, file_version);
         ~~^~~~~~~~~
```

**Comment by tjhei** [comment]
@bangerth is to blame I think. ;-)

**Comment by drwells** [comment]
@tjhei it looks like this has something to do with the boost version: the bundled boost is fine but not 1.64.

**Comment by tamiko** [comment]
simserv04 with boost version 1.57 is completely broken as well.

**Comment by drwells** [comment]
How did `boost::archive` forget how to serialize longs? This is not good.

**Comment by tamiko** [comment]
Bisected commit:
```
65bbc4d7ffe58c88285dfc1851a20772c978ea6d is the first bad commit
commit 65bbc4d7ffe58c88285dfc1851a20772c978ea6d
Author: Wolfgang Bangerth <bangerth@colostate.edu>
Date:   Sun Aug 13 16:41:14 2017 -0600

    Express the ghost exchange of DoF indices using GridTools::exchange_cell_data_to_ghosts().
```

Above change breaks with external boost 1.57.

**Comment by tamiko** [comment]
Bisected commit:
```
46688dbcbe68e728410018087715003b5c5cf172 is the first bad commit                               
commit 46688dbcbe68e728410018087715003b5c5cf172                                                
Author: Matthias Maier <tamiko@43-1.org>       
Date:   Mon Aug 14 17:39:26 2017 -0500         

    CMake: Update internal CUDA setup, remove obsolete code                                    
                                               
    Update internal CUDA setup to use native language features. If the                         
    current CMake version is too old, fall back to the old behavior.                           
                                               
    Further, remove obsolete CUDA configuration from tests.                                    

:040000 040000 5b22cf59db19d4a086d99ea735c8705b7b2d43ca f68e811c1115caaa48b05966c417e3fc70d84d66 M      cmake                                                                                  
:040000 040000 cbef286de7b1959deab67f01c7894cec74b86e19 587c507cda92ab43b0efdf61f9d54bc1929194d8 M      tests
```
Above change breaks ~40 debug tests.

**Comment by bangerth** [comment]
Did #4885 fix all problems? Or is the boost serialization thingy still broken?

**Comment by tamiko** [comment]
@bangerth Boost is still broken.

**Comment by bangerth** [comment]
I don't have access to a platform that fails. I'll need some help figuring out what is going on. Can someone open an issue that shows one of the failing tests and how exactly it fails?

**Comment by tamiko** [comment]
@bangerth
```
In file included from /mnt/data/testsuite/dealii/source/hp/dof_handler.cc:31:0:
/mnt/data/testsuite/dealii/include/deal.II/distributed/grid_tools.h: In instantiation of ‘void dealii::parallel::GridTools::internal::CellDataTransferBuffer<dim, T>::save(Archive&, unsigned int) const [with Archive = boost::archive::binary_oarchive; int dim = 1; T = unsigned int]’:
/export/home/mmaier/gentoo/usr/include/boost/serialization/access.hpp:93:9:   required from ‘static void boost::serialization::access::member_save(Archive&, T&, unsigned int) [with Archive = boost::archive::binary_oarchive; T = const dealii::parallel::GridTools::internal::CellDataTransferBuffer<1, unsigned int>]’
/export/home/mmaier/gentoo/usr/include/boost/serialization/split_member.hpp:43:32:   required from ‘static void boost::serialization::detail::member_saver<Archive, T>::invoke(Archive&, const T&, unsigned int) [with Archive = boost::archive::binary_oarchive; T = dealii::parallel::GridTools::internal::CellDataTransferBuffer<1, unsigned int>]’
/export/home/mmaier/gentoo/usr/include/boost/serialization/split_member.hpp:69:18:   required from ‘void boost::serialization::split_member(Archive&, T&, unsigned int) [with Archive = boost::archive::binary_oarchive; T = dealii::parallel::GridTools::internal::CellDataTransferBuffer<1, unsigned int>]’
/mnt/data/testsuite/dealii/include/deal.II/distributed/grid_tools.h:188:9:   required from ‘void dealii::parallel::GridTools::internal::CellDataTransferBuffer<dim, T>::serialize(Archive&, unsigned int) [with Archive = boost::archive::binary_oarchive; int dim = 1; T = unsigned int]’
/export/home/mmaier/gentoo/usr/include/boost/serialization/access.hpp:118:9:   required from ‘static void boost::serialization::access::serialize(Archive&, T&, unsigned int) [with Archive = boost::archive::binary_oarchive; T = dealii::parallel::GridTools::internal::CellDataTransferBuffer<1, unsigned int>]’
/export/home/mmaier/gentoo/usr/include/boost/serialization/serialization.hpp:69:22:   [ skipping 10 instantiation contexts, use -ftemplate-backtrace-limit=0 to disable ]
/export/home/mmaier/gentoo/usr/include/boost/archive/detail/interface_oarchive.hpp:63:9:   required from ‘Archive& boost::archive::detail::interface_oarchive<Archive>::operator<<(T&) [with T = const dealii::parallel::GridTools::internal::CellDataTransferBuffer<1, unsigned int>; Archive = boost::archive::binary_oarchive]’
/mnt/data/testsuite/dealii/include/deal.II/distributed/grid_tools.h:210:21:   required from ‘std::vector<char> dealii::parallel::GridTools::internal::CellDataTransferBuffer<dim, T>::pack_data() const [with int dim = 1; T = unsigned int]’
/mnt/data/testsuite/dealii/include/deal.II/distributed/grid_tools.h:346:28:   required from ‘void dealii::parallel::GridTools::exchange_cell_data_to_ghosts(const MeshType&, std::function<boost::optional<T>(const typename MeshType::active_cell_iterator&)>, std::function<void(const typename MeshType::active_cell_iterator&, const DataType&)>) [with DataType = unsigned int; MeshType = dealii::hp::DoFHandler<1, 1>; typename MeshType::active_cell_iterator = dealii::TriaActiveIterator<dealii::DoFCellAccessor<dealii::hp::DoFHandler<1, 1>, false> >]’
/mnt/data/testsuite/dealii/source/hp/dof_handler.cc:937:19:   required from ‘static void dealii::internal::hp::DoFHandler::Implementation::communicate_active_fe_indices(dealii::hp::DoFHandler<dim, spacedim>&) [with int dim = 1; int spacedim = 1]’
/mnt/data/testsuite/dealii/source/hp/dof_handler.cc:1293:85:   required from ‘void dealii::hp::DoFHandler<dim, spacedim>::distribute_dofs(const dealii::hp::FECollection<dim, spacedim>&) [with int dim = 1; int spacedim = 1]’
/mnt/data/testsuite/dealii/build/source/hp/dof_handler.inst:12:17:   required from here
/mnt/data/testsuite/dealii/include/deal.II/distributed/grid_tools.h:157:28: error: invalid initialization of non-const reference of type ‘long unsigned int&’ from an rvalue of type ‘std::vector<dealii::CellId>::size_type {aka long unsigned int}’
           ar &cell_ids.size();
                            ^
In file included from /export/home/mmaier/gentoo/usr/include/boost/archive/detail/common_oarchive.hpp:22:0,
                 from /export/home/mmaier/gentoo/usr/include/boost/archive/basic_binary_oarchive.hpp:34,
                 from /export/home/mmaier/gentoo/usr/include/boost/archive/binary_oarchive_impl.hpp:23,
                 from /export/home/mmaier/gentoo/usr/include/boost/archive/binary_oarchive.hpp:21,
                 from /mnt/data/testsuite/dealii/include/deal.II/distributed/grid_tools.h:27,
                 from /mnt/data/testsuite/dealii/source/hp/dof_handler.cc:31:
/export/home/mmaier/gentoo/usr/include/boost/archive/detail/interface_oarchive.hpp:69:15: note:   initializing argument 1 of ‘Archive& boost::archive::detail::interface_oarchive<Archive>::operator&(T&) [with T = long unsigned int; Archive = boost::archive::binary_oarchive]’
     Archive & operator&(T & t){
               ^
In file included from /mnt/data/testsuite/dealii/source/hp/dof_handler.cc:31:0:
/mnt/data/testsuite/dealii/include/deal.II/distributed/grid_tools.h: In instantiation of ‘void dealii::parallel::GridTools::internal::CellDataTransferBuffer<dim, T>::save(Archive&, unsigned int) const [with Archive = boost::archive::binary_oarchive; int dim = 2; T = unsigned int]’:
/export/home/mmaier/gentoo/usr/include/boost/serialization/access.hpp:93:9:   required from ‘static void boost::serialization::access::member_save(Archive&, T&, unsigned int) [with Archive = boost::archive::binary_oarchive; T = const dealii::parallel::GridTools::internal::CellDataTransferBuffer<2, unsigned int>]’
/export/home/mmaier/gentoo/usr/include/boost/serialization/split_member.hpp:43:32:   required from ‘static void boost::serialization::detail::member_saver<Archive, T>::invoke(Archive&, const T&, unsigned int) [with Archive = boost::archive::binary_oarchive; T = dealii::parallel::GridTools::internal::CellDataTransferBuffer<2, unsigned int>]’
/export/home/mmaier/gentoo/usr/include/boost/serialization/split_member.hpp:69:18:   required from ‘void boost::serialization::split_member(Archive&, T&, unsigned int) [with Archive = boost::archive::binary_oarchive; T = dealii::parallel::GridTools::internal::CellDataTransferBuffer<2, unsigned int>]’
/mnt/data/testsuite/dealii/include/deal.II/distributed/grid_tools.h:188:9:   required from ‘void dealii::parallel::GridTools::internal::CellDataTransferBuffer<dim, T>::serialize(Archive&, unsigned int) [with Archive = boost::archive::binary_oarchive; int dim = 2; T = unsigned int]’
/export/home/mmaier/gentoo/usr/include/boost/serialization/access.hpp:118:9:   required from ‘static void boost::serialization::access::serialize(Archive&, T&, unsigned int) [with Archive = boost::archive::binary_oarchive; T = dealii::parallel::GridTools::internal::CellDataTransferBuffer<2, unsigned int>]’
/export/home/mmaier/gentoo/usr/include/boost/serialization/serialization.hpp:69:22:   [ skipping 10 instantiation contexts, use -ftemplate-backtrace-limit=0 to disable ]
/export/home/mmaier/gentoo/usr/include/boost/archive/detail/interface_oarchive.hpp:63:9:   required from ‘Archive& boost::archive::detail::interface_oarchive<Archive>::operator<<(T&) [with T = const dealii::parallel::GridTools::internal::CellDataTransferBuffer<2, unsigned int>; Archive = boost::archive::binary_oarchive]’
/mnt/data/testsuite/dealii/include/deal.II/distributed/grid_tools.h:210:21:   required from ‘std::vector<char> dealii::parallel::GridTools::internal::CellDataTransferBuffer<dim, T>::pack_data() const [with int dim = 2; T = unsigned int]’
/mnt/data/testsuite/dealii/include/deal.II/distributed/grid_tools.h:346:28:   required from ‘void dealii::parallel::GridTools::exchange_cell_data_to_ghosts(const MeshType&, std::function<boost::optional<T>(const typename MeshType::active_cell_iterator&)>, std::function<void(const typename MeshType::active_cell_iterator&, const DataType&)>) [with DataType = unsigned int; MeshType = dealii::hp::DoFHandler<2, 2>; typename MeshType::active_cell_iterator = dealii::TriaActiveIterator<dealii::DoFCellAccessor<dealii::hp::DoFHandler<2, 2>, false> >]’
/mnt/data/testsuite/dealii/source/hp/dof_handler.cc:937:19:   required from ‘static void dealii::internal::hp::DoFHandler::Implementation::communicate_active_fe_indices(dealii::hp::DoFHandler<dim, spacedim>&) [with int dim = 2; int spacedim = 2]’
/mnt/data/testsuite/dealii/source/hp/dof_handler.cc:1293:85:   required from ‘void dealii::hp::DoFHandler<dim, spacedim>::distribute_dofs(const dealii::hp::FECollection<dim, spacedim>&) [with int dim = 2; int spacedim = 2]’
/mnt/data/testsuite/dealii/build/source/hp/dof_handler.inst:85:17:   required from here
/mnt/data/testsuite/dealii/include/deal.II/distributed/grid_tools.h:157:28: error: invalid initialization of non-const reference of type ‘long unsigned int&’ from an rvalue of type ‘std::vector<dealii::CellId>::size_type {aka long unsigned int}’
           ar &cell_ids.size();
                            ^
In file included from /export/home/mmaier/gentoo/usr/include/boost/archive/detail/common_oarchive.hpp:22:0,
                 from /export/home/mmaier/gentoo/usr/include/boost/archive/basic_binary_oarchive.hpp:34,
                 from /export/home/mmaier/gentoo/usr/include/boost/archive/binary_oarchive_impl.hpp:23,
                 from /export/home/mmaier/gentoo/usr/include/boost/archive/binary_oarchive.hpp:21,
                 from /mnt/data/testsuite/dealii/include/deal.II/distributed/grid_tools.h:27,
                 from /mnt/data/testsuite/dealii/source/hp/dof_handler.cc:31:
/export/home/mmaier/gentoo/usr/include/boost/archive/detail/interface_oarchive.hpp:69:15: note:   initializing argument 1 of ‘Archive& boost::archive::detail::interface_oarchive<Archive>::operator&(T&) [with T = long unsigned int; Archive = boost::archive::binary_oarchive]’
     Archive & operator&(T & t){
               ^
In file included from /mnt/data/testsuite/dealii/source/hp/dof_handler.cc:31:0:
/mnt/data/testsuite/dealii/include/deal.II/distributed/grid_tools.h: In instantiation of ‘void dealii::parallel::GridTools::internal::CellDataTransferBuffer<dim, T>::save(Archive&, unsigned int) const [with Archive = boost::archive::binary_oarchive; int dim = 3; T = unsigned int]’:
/export/home/mmaier/gentoo/usr/include/boost/serialization/access.hpp:93:9:   required from ‘static void boost::serialization::access::member_save(Archive&, T&, unsigned int) [with Archive = boost::archive::binary_oarchive; T = const dealii::parallel::GridTools::internal::CellDataTransferBuffer<3, unsigned int>]’
/export/home/mmaier/gentoo/usr/include/boost/serialization/split_member.hpp:43:32:   required from ‘static void boost::serialization::detail::member_saver<Archive, T>::invoke(Archive&, const T&, unsigned int) [with Archive = boost::archive::binary_oarchive; T = dealii::parallel::GridTools::internal::CellDataTransferBuffer<3, unsigned int>]’
/export/home/mmaier/gentoo/usr/include/boost/serialization/split_member.hpp:69:18:   required from ‘void boost::serialization::split_member(Archive&, T&, unsigned int) [with Archive = boost::archive::binary_oarchive; T = dealii::parallel::GridTools::internal::CellDataTransferBuffer<3, unsigned int>]’
/mnt/data/testsuite/dealii/include/deal.II/distributed/grid_tools.h:188:9:   required from ‘void dealii::parallel::GridTools::internal::CellDataTransferBuffer<dim, T>::serialize(Archive&, unsigned int) [with Archive = boost::archive::binary_oarchive; int dim = 3; T = unsigned int]’
/export/home/mmaier/gentoo/usr/include/boost/serialization/access.hpp:118:9:   required from ‘static void boost::serialization::access::serialize(Archive&, T&, unsigned int) [with Archive = boost::archive::binary_oarchive; T = dealii::parallel::GridTools::internal::CellDataTransferBuffer<3, unsigned int>]’
/export/home/mmaier/gentoo/usr/include/boost/serialization/serialization.hpp:69:22:   [ skipping 10 instantiation contexts, use -ftemplate-backtrace-limit=0 to disable ]
/export/home/mmaier/gentoo/usr/include/boost/archive/detail/interface_oarchive.hpp:63:9:   required from ‘Archive& boost::archive::detail::interface_oarchive<Archive>::operator<<(T&) [with T = const dealii::parallel::GridTools::internal::CellDataTransferBuffer<3, unsigned int>; Archive = boost::archive::binary_oarchive]’
/mnt/data/testsuite/dealii/include/deal.II/distributed/grid_tools.h:210:21:   required from ‘std::vector<char> dealii::parallel::GridTools::internal::CellDataTransferBuffer<dim, T>::pack_data() const [with int dim = 3; T = unsigned int]’
/mnt/data/testsuite/dealii/include/deal.II/distributed/grid_tools.h:346:28:   required from ‘void dealii::parallel::GridTools::exchange_cell_data_to_ghosts(const MeshType&, std::function<boost::optional<T>(const typename MeshType::active_cell_iterator&)>, std::function<void(const typename MeshType::active_cell_iterator&, const DataType&)>) [with DataType = unsigned int; MeshType = dealii::hp::DoFHandler<3>; typename MeshType::active_cell_iterator = dealii::TriaActiveIterator<dealii::DoFCellAccessor<dealii::hp::DoFHandler<3>, false> >]’
/mnt/data/testsuite/dealii/source/hp/dof_handler.cc:937:19:   required from ‘static void dealii::internal::hp::DoFHandler::Implementation::communicate_active_fe_indices(dealii::hp::DoFHandler<dim, spacedim>&) [with int dim = 3; int spacedim = 3]’
/mnt/data/testsuite/dealii/source/hp/dof_handler.cc:1293:85:   required from ‘void dealii::hp::DoFHandler<dim, spacedim>::distribute_dofs(const dealii::hp::FECollection<dim, spacedim>&) [with int dim = 3; int spacedim = 3]’
/mnt/data/testsuite/dealii/build/source/hp/dof_handler.inst:158:17:   required from here
/mnt/data/testsuite/dealii/include/deal.II/distributed/grid_tools.h:157:28: error: invalid initialization of non-const reference of type ‘long unsigned int&’ from an rvalue of type ‘std::vector<dealii::CellId>::size_type {aka long unsigned int}’
           ar &cell_ids.size();
                            ^
In file included from /export/home/mmaier/gentoo/usr/include/boost/archive/detail/common_oarchive.hpp:22:0,
                 from /export/home/mmaier/gentoo/usr/include/boost/archive/basic_binary_oarchive.hpp:34,
                 from /export/home/mmaier/gentoo/usr/include/boost/archive/binary_oarchive_impl.hpp:23,
                 from /export/home/mmaier/gentoo/usr/include/boost/archive/binary_oarchive.hpp:21,
                 from /mnt/data/testsuite/dealii/include/deal.II/distributed/grid_tools.h:27,
                 from /mnt/data/testsuite/dealii/source/hp/dof_handler.cc:31:
/export/home/mmaier/gentoo/usr/include/boost/archive/detail/interface_oarchive.hpp:69:15: note:   initializing argument 1 of ‘Archive& boost::archive::detail::interface_oarchive<Archive>::operator&(T&) [with T = long unsigned int; Archive = boost::archive::binary_oarchive]’
     Archive & operator&(T & t){
               ^
make[2]: *** [source/hp/CMakeFiles/obj_hp_debug.dir/dof_handler.cc.o] Error 1
```

**Comment by tamiko** [comment]
The relevant part seems to be
```
/mnt/data/testsuite/dealii/include/deal.II/distributed/grid_tools.h:157:28: error: invalid initialization of non-const reference of type ‘long unsigned int&’ from an rvalue of type ‘std::vector<dealii::CellId>::size_type {aka long unsigned int}’
           ar &cell_ids.size();
```

I am not sure, whether I bisected correctly. I will ping @tjhei preemptively as well :-]

**Comment by tamiko** [comment]
@drwells (@bangerth @tjhei):
Yes, boost archive probably fails because the right-hand side is not a reference to an `unsigned int` but an rvalue `unsigned int`.

```
/.../dealii/include/deal.II/distributed/grid_tools.h:157:14: error: invalid operands to binary expression ('boost::archive::binary_oarchive' and 'size_type' (aka 'unsigned long'))

          ar &cell_ids.size();
          ~~ ^~~~~~~~~~~~~~~~
```

**Comment by tjhei** [comment]
Yes, that is my fault. I have a fix...

**Comment by tjhei** [comment]
see #4891

**Comment by tamiko** [comment]
The final set of failing tests [1] are likely fixed with #4891 as well. Let's see.
[1] https://cdash.kyomu.43-1.org/viewTest.php?onlyfailed&buildid=10278
