### ISSUE TITLE
Regression tester regressed 451219

### ISSUE THREAD

**Issue by tamiko** [dealii/dealii#16127]
[start automated regression testsuite report]

Dear all,

this is the automated regression testsuite reporting a new regression between
- new revision: 451219fc0e467a15c0d69d95063c773e410e10b4  [regression testsuite results](https://cdash.dealii.org/index.php?project=deal.II&filtercount=1&showfilters=1&field1=revision&compare1=63&value1=451219)
- old revision: d198e02089bad92d5a75343b89764bcb4f0c94a9  [regression testsuite results](https://cdash.dealii.org/index.php?project=deal.II&filtercount=1&showfilters=1&field1=revision&compare1=63&value1=d198e0)

Summary:
- :angry: new test failures introduced for configuration [GNU-11.3.0-master-ubuntu-lts-22.04](https://cdash.dealii.org/build/3143) on site tester-tng
- :angry: new test failures introduced for configuration [GNU-12.2.0-master-debian-12](https://cdash.dealii.org/build/3146) on site tester-tng
- :angry: new test failures introduced for configuration [GNU-12.2.0-master-ubuntu-23.04](https://cdash.dealii.org/build/3144) on site tester-tng
- :angry: new test failures introduced for configuration [GNU-12.3.0-master-debian-13](https://cdash.dealii.org/build/3145) on site tester-tng

I have identified the following pull requests as possible candidates:
- #15927 (authored-by: @peterrum; merged-by: @drwells)
- #16005 (authored-by: @jpthiele; merged-by: @drwells)
- #16114 (authored-by: @bangerth; merged-by: @kronbichler)
- #16122 (authored-by: @kronbichler; merged-by: @tjhei)
- #16088 (authored-by: @peterrum; merged-by: @kronbichler)

Notes:
 - The regression reported above is a subset of the following full set of regressions compared to the baseline:
   - :angry: test failures for configuration [GNU-11.3.0-master-ubuntu-lts-22.04](https://cdash.dealii.org/build/3143) on site tester-tng
   - :angry: test failures for configuration [GNU-12.2.0-master-debian-12](https://cdash.dealii.org/build/3146) on site tester-tng
   - :angry: test failures for configuration [GNU-12.2.0-master-ubuntu-23.04](https://cdash.dealii.org/build/3144) on site tester-tng
   - :angry: test failures for configuration [GNU-12.3.0-master-debian-13](https://cdash.dealii.org/build/3145) on site tester-tng
 - I will close and unpin this issue automatically once a full run is complete and compares cleanly to the baseline.
 - If closed I will reopen the issue if the testsuite run identified an additional regression compared to what I have reported so far.

[end automated regression testsuite report]

**Comment by bangerth** [comment]
The failure is this:
```
/jenkins/workspace/dealii-mpi_PR-16123/tests/multigrid-global-coarsening/multigrid_p_04.cc: In function ‘void test(unsigned int, unsigned int, bool, unsigned int)’:
/jenkins/workspace/dealii-mpi_PR-16123/tests/multigrid-global-coarsening/multigrid_p_04.cc:101:23: error: type/value mismatch at argument 2 in template parameter list for ‘template<int dim_, int n_components, class Number> class Operator’
  101 |   Operator<dim, Number> fine_operator;
      |                       ^
```
This is because in `multigrid_p_04.cc`, we have
```
  // set up operator
  Operator<dim, Number> fine_operator;
  fine_operator.reinit(*mapping, fine_dof_handler, *quad, fine_constraints);
```
but in `multigrid_util.h` in the same directory, we have
```
template <int dim_, int n_components = dim_, typename Number = double>
class Operator : public Subscriptor
{...
```

I believe that this was caused by the merge of #16088. It leads to failing CI checks, for example in #16123.

@peterrum FYI
