### PR TITLE
Linking error: make `dealii::internal::SolverGMRESImplementation::solve_triangular()` inline

### PR DESCRIPTION
**Pull request by mschreter**
This PR suggests to make the function `dealii::internal::SolverGMRESImplementation::solve_triangular()` inline, since it is currently defined in the header file. Otherwise a linking error occurs with a multiple definitions warning. The function was introduced in https://github.com/dealii/dealii/pull/14251.

@kronbichler FYI

### CODE REVIEW

**Comment by kronbichler** [comment]
Absolutely, thank you for fixing it.

**Review by kronbichler — APPROVED** [review]

**Review by peterrum — APPROVED** [review]
