### PR TITLE
Fix warning about deprecated implicit conversion.

### PR DESCRIPTION
**Pull request by marcfehling**
This should take care of the warning introduced in https://github.com/dealii/dealii/pull/15415#issuecomment-1722778989.

### CODE REVIEW

**Review by kronbichler — APPROVED** [review]

**Comment by kronbichler** [comment]
There is one additional error, now at the linker stage (showing that the error in #15415 was indeed not just spurious):
```
 /usr/bin/ld: ../lib/libdeal_II.g.so.9.6.0-pre: undefined reference to `void dealii::internal::hermite_hierarchic_to_lexicographic_numbering<0>(unsigned int, std::vector<unsigned int, std::allocator<unsigned int> >&)'
/usr/bin/ld: ../lib/libdeal_II.g.so.9.6.0-pre: undefined reference to `dealii::FiniteElementData<0>::FiniteElementData(std::vector<unsigned int, std::allocator<unsigned int> > const&, unsigned int, unsigned int, dealii::FiniteElementData<0>::Conformity, dealii::BlockIndices const&)'
```

**Review by kronbichler — APPROVED** [review]

**Comment by peterrum** [comment]
I think the undefined references should be fixed now. There is some recursive template calling which is actually terminates with dim=1.

File: source/fe/fe_hermite.cc [hunk 1]
```diff
@@ -203,8 +203,8 @@ namespace internal
   hermite_face_lexicographic_to_hierarchic_numbering(
     const unsigned int regularity)
   {
-    return (dim > 1) ? hermite_lexicographic_to_hierarchic_numbering<dim - 1>(
-                         regularity) :
+    return (dim > 1) ? hermite_lexicographic_to_hierarchic_numbering<
+                         std::max(dim - 1, 1)>(regularity) :
                        std::vector<unsigned int>();
```
Comment (masterleinad) [inline source/fe/fe_hermite.cc:208]: I think
```suggestion
    if constexpr (dim > 1)
      return hermite_lexicographic_to_hierarchic_numbering<dim - 1)>(regularity);
    else
      return std::vector<unsigned int>();
```
is easier to read.

**Review by kronbichler — APPROVED** [review]
