### PR TITLE
Use aliases for TpetraTypes::[Dual]View[Unmanaged]

### LINKED ISSUE #17434: Compilation fails with Tpetra and Kokkos with complex and float
Trying to build the current master branch with `gcc 9.4.0` and `Trilinos 15.1.1` configured with `Trilinos_ENABLE_COMPLEX=ON` and `Trilinos_ENABLE_FLOAT=ON` on our house cluster, but I get a 1200 lines long error.

Does this look familiar to anyone? It rather looks like an issue in Trilinos/Kokkos than in deal.II.

```
FAILED: source/lac/CMakeFiles/object_lac_debug.dir/trilinos_tpetra_precondition.cc.o 
/linux-ubuntu20.04-skylake_avx512/gcc9.4.0/openmpi/4.1.6/k6qlwqr2vx5osaqf/bin/mpicxx -DDEBUG -DKOKKOS_DEPENDENCE -I/build-dealii/source/lac -I/dealii/source/lac -I/build-dealii/include -I/dealii/include -isystem /dealii/bundled/boost-1.84.0/include -isystem /dealii/bundled/umfpack/UMFPACK/Include -isystem /dealii/bundled/umfpack/AMD/Include -isystem /dealii/bundled/muparser_v2_3_3/include -isystem /linux-ubuntu20.04-skylake_avx512/gcc9.4.0/zlib/1.2.13/sz4h6ncyn4o7aczi/include -isystem /bin/trilinos-15.1.1/include -isystem /bin/sundials-7.0.0/include -isystem /bin/p4est-2.3.6/FAST/include -std=c++17 -fPIC -pedantic -Wall -Wextra -Wmissing-braces -Woverloaded-virtual -Wpointer-arith -Wsign-compare -Wsuggest-override -Wswitch -Wsynth -Wwrite-strings -Wno-placement-new -Wno-deprecated-declarations -Wno-literal-suffix -Wno-psabi -Wno-unused-local-typedefs -Wno-parentheses -fopenmp-simd -march=skylake-avx512 -O0 -ggdb -Wa,--compress-debug-sections -g -MD -MT source/lac/CMakeFiles/object_lac_debug.dir/trilinos_tpetra_precondition.cc.o -MF source/lac/CMakeFiles/object_lac_debug.dir/trilinos_tpetra_precondition.cc.o.d -o source/lac/CMakeFiles/object_lac_debug.dir/trilinos_tpetra_precondition.cc.o -c /dealii/source/lac/trilinos_tpetra_precondition.cc
In file included from /bin/trilinos-15.1.1/include/Tpetra_Map_decl.hpp:53,
                 from /bin/trilinos-15.1.1/include/Tpetra_Map.hpp:1,
                 from /dealii/include/deal.II/base/index_set.h:34,
                 from /dealii/include/deal.II/lac/trilinos_tpetra_precondition.templates.h:22,
                 from /dealii/source/lac/trilinos_tpetra_precondition.cc:16:
/bin/trilinos-15.1.1/include/Kokkos_DualView.hpp: In instantiation of 'Kokkos::DualView<DataType, Arg1Type, Arg2Type, Arg3Type>::DualView(const Kokkos::DualView<DT, DP ...>&) [with DT = std::complex<float>**; DP = {Kokkos::LayoutLeft, Kokkos::Serial, Kokkos::MemoryTraits<1>}; DataType = Kokkos::complex<float>**; Arg1Type = Kokkos::LayoutLeft; Arg2Type = Kokkos::Device<Kokkos::Serial, Kokkos::HostSpace>; Arg3Type = void]':
/dealii/include/deal.II/lac/trilinos_tpetra_precondition.templates.h:175:52:   required from 'void dealii::LinearAlgebra::TpetraWrappers::PreconditionBase<Number, MemorySpace>::vmult(dealii::Vector<OtherNumber>&, dealii::Vector<OtherNumber>&) const [with Number = std::complex<float>; MemorySpace = dealii::MemorySpace::Host]'
/dealii/source/lac/trilinos_tpetra_precondition.cc:66:20:   required from here
/bin/trilinos-15.1.1/include/Kokkos_DualView.hpp:293:26: error: no matching function for call to 'Kokkos::View<Kokkos::complex<float>**, Kokkos::LayoutLeft, Kokkos::Device<Kokkos::Serial, Kokkos::HostSpace>, void>::View(const t_dev&)'
  293 |         h_view(src.h_view) {}
      |                          ^
In file included from /bin/trilinos-15.1.1/include/Kokkos_Parallel.hpp:31,
                 from /bin/trilinos-15.1.1/include/Kokkos_MemoryPool.hpp:26,
                 from /bin/trilinos-15.1.1/include/Kokkos_TaskScheduler.hpp:34,
                 from /bin/trilinos-15.1.1/include/Serial/Kokkos_Serial.hpp:37,
                 from /bin/trilinos-15.1.1/include/decl/Kokkos_Declare_SERIAL.hpp:21,
                 from /bin/trilinos-15.1.1/include/KokkosCore_Config_DeclareBackend.hpp:22,
                 from /bin/trilinos-15.1.1/include/Kokkos_Core.hpp:45,
                 from /bin/trilinos-15.1.1/include/Tpetra_KokkosCompat_ClassicNodeAPI_Wrapper.hpp:4,
                 from /bin/trilinos-15.1.1/include/Tpetra_Details_DefaultTypes.hpp:45,
                 from /bin/trilinos-15.1.1/include/Tpetra_ConfigDefs.hpp:43,
                 from /bin/trilinos-15.1.1/include/Tpetra_Map_decl.hpp:47,
                 from /bin/trilinos-15.1.1/include/Tpetra_Map.hpp:1,
                 from /dealii/include/deal.II/base/index_set.h:34,
                 from /dealii/include/deal.II/lac/trilinos_tpetra_precondition.templates.h:22,
                 from /dealii/source/lac/trilinos_tpetra_precondition.cc:16:
/bin/trilinos-15.1.1/include/Kokkos_View.hpp:1640:35: note: candidate: 'Kokkos::View<DataType, Properties>::View(const typename Kokkos::View<DataType, Properties>::traits::execution_space::scratch_memory_space&, size_t, size_t, size_t, size_t, size_t, size_t, size_t, size_t) [with DataType = Kokkos::complex<float>**; Properties = {Kokkos::LayoutLeft, Kokkos::Device<Kokkos::Serial, Kokkos::HostSpace>, void}; typename Kokkos::View<DataType, Properties>::traits::execution_space::scratch_memory_space = Kokkos::ScratchMemorySpace<Kokkos::Serial>; size_t = long unsigned int]'
 1640 |   explicit KOKKOS_INLINE_FUNCTION View(
      |                                   ^~~~
/bin/trilinos-15.1.1/include/Kokkos_View.hpp:1641:69: note:   no known conversion for argument 1 from 'const t_dev' {aka 'const Kokkos::View<std::complex<float>**, Kokkos::LayoutLeft, Kokkos::Serial, Kokkos::MemoryTraits<1> >'} to 'const scratch_memory_space&' {aka 'const Kokkos::ScratchMemorySpace<Kokkos::Serial>&'}
 1641 |       const typename traits::execution_space::scratch_memory_space& arg_space,
      |       ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^~~~~~~~~
/bin/trilinos-15.1.1/include/Kokkos_View.hpp:1632:35: note: candidate: 'Kokkos::View<DataType, Properties>::View(const typename Kokkos::View<DataType, Properties>::traits::execution_space::scratch_memory_space&, const typename Kokkos::View<DataType, Properties>::traits::array_layout&) [with DataType = Kokkos::complex<float>**; Properties = {Kokkos::LayoutLeft, Kokkos::Device<Kokkos::Serial, Kokkos::HostSpace>, void}; typename Kokkos::View<DataType, Properties>::traits::execution_space::scratch_memory_space = Kokkos::ScratchMemorySpace<Kokkos::Serial>; typename Kokkos::View<DataType, Properties>::traits::array_layout = Kokkos::LayoutLeft]'
 1632 |   explicit KOKKOS_INLINE_FUNCTION View(
      |                                   ^~~~
/bin/trilinos-15.1.1/include/Kokkos_View.hpp:1632:35: note:   candidate expects 2 arguments, 1 provided
/bin/trilinos-15.1.1/include/Kokkos_View.hpp:1585:35: note: candidate: 'Kokkos::View<DataType, Properties>::View(Kokkos::View<DataType, Properties>::pointer_type, const typename Kokkos::View<DataType, Properties>::traits::array_layout&) [with DataType = Kokkos::complex<float>**; Properties = {Kokkos::LayoutLeft, Kokkos::Device<Kokkos::Serial, Kokkos::HostSpace>, void}; Kokkos::View<DataType, Properties>::pointer_type = Kokkos::complex<float>*; typename Kokkos::View<DataType, Properties>::traits::array_layout = Kokkos::LayoutLeft]'
 1585 |   explicit KOKKOS_INLINE_FUNCTION View(
      |                                   ^~~~
/bin/trilinos-15.1.1/include/Kokkos_View.hpp:1585:35: note:   candidate expects 2 arguments, 1 provided
/bin/trilinos-15.1.1/include/Kokkos_View.hpp:1568:35: note: candidate: 'Kokkos::View<DataType, Properties>::View(Kokkos::View<DataType, Properties>::pointer_type, size_t, size_t, size_t, size_t, size_t, size_t, size_t, size_t) [with DataType = Kokkos::complex<float>**; Properties = {Kokkos::LayoutLeft, Kokkos::Device<Kokkos::Serial, Kokkos::HostSpace>, void}; Kokkos::View<DataType, Properties>::pointer_type = Kokkos::complex<float>*; size_t = long unsigned int]'
 1568 |   explicit KOKKOS_INLINE_FUNCTION View(
      |                                   ^~~~
/bin/trilinos-15.1.1/include/Kokkos_View.hpp:1569:20: note:   no known conversion for argument 1 from 'const t_dev' {aka 'const Kokkos::View<std::complex<float>**, Kokkos::LayoutLeft, Kokkos::Serial, Kokkos::MemoryTraits<1> >'} to 'Kokkos::View<Kokkos::complex<float>**, Kokkos::LayoutLeft, Kokkos::Device<Kokkos::Serial, Kokkos::HostSpace>, void>::pointer_type' {aka 'Kokkos::complex<float>*'}
 1569 |       pointer_type arg_ptr, const size_t arg_N0 = KOKKOS_IMPL_CTOR_DEFAULT_ARG,
      |       ~~~~~~~~~~~~~^~~~~~~
/bin/trilinos-15.1.1/include/Kokkos_View.hpp:1539:26: note: candidate: 'template<class Traits> Kokkos::View<DataType, Properties>::View(const typename Kokkos::View<DataType, Properties>::view_tracker_type::track_type&, const Kokkos::Impl::ViewMapping<Traits, typename Traits::specialize>&)'
 1539 |   KOKKOS_INLINE_FUNCTION View(
      |                          ^~~~
/bin/trilinos-15.1.1/include/Kokkos_View.hpp:1539:26: note:   template argument deduction/substitution failed:
[...]
```

[full error message](https://github.com/user-attachments/files/16495524/full-error.txt)

### PR DESCRIPTION
**Pull request by masterleinad**
Fixes #17434. We don't actually need the `Kokkos::MemoryUnmanaged` trait since a `Kokkos::View` is unmanaged if and only if it was instructed from a pointer.

### CODE REVIEW

**Review by marcfehling — APPROVED** [review]

**Comment by marcfehling** [comment]
```
In file included from /__w/dealii/dealii/include/deal.II/lac/trilinos_tpetra_vector.h:23,
                 from /__w/dealii/dealii/include/deal.II/lac/vector_element_access.h:22,
                 from /__w/dealii/dealii/include/deal.II/lac/affine_constraints.h:29,
                 from /__w/dealii/dealii/include/deal.II/dofs/dof_accessor.templates.h:30,
                 from /__w/dealii/dealii/include/deal.II/dofs/dof_accessor.h:2145,
                 from /__w/dealii/dealii/source/numerics/data_out.cc:17:
/__w/dealii/dealii/include/deal.II/lac/trilinos_tpetra_types.h:154:37: error: ‘template<class Number, class MemorySpace> using VectorType = Tpetra::Vector<Number, int, long long int, Kokkos::Compat::KokkosDeviceWrapperNode<typename MemorySpace::kokkos_space::execution_space, typename MemorySpace::kokkos_space> >’ used without template arguments
  154 |       using HostViewType = typename VectorType::host_view_type;
      |                                     ^~~~~~~~~~
/__w/dealii/dealii/include/deal.II/lac/trilinos_tpetra_types.h:162:37: error: ‘template<class Number, class MemorySpace> using VectorType = Tpetra::Vector<Number, int, long long int, Kokkos::Compat::KokkosDeviceWrapperNode<typename MemorySpace::kokkos_space::execution_space, typename MemorySpace::kokkos_space> >’ used without template arguments
  162 |       using DualViewType = typename VectorType::dual_view_type;
      |                                     ^~~~~~~~~~
```

File: include/deal.II/lac/trilinos_tpetra_types.h [hunk 1]
```diff
@@ -145,36 +145,21 @@ namespace LinearAlgebra
...
-       *
-       * Unmanaged means that the view is not allocating data itself, but only
-       * uses an external pointer. Consequently, the memory is not freed upon
-       * destruction of the view.
+       * @brief Typedef for the Kokkos::View type.
        * This is needed for shallow copies of deal.II LA structures
        * to Trilinos LA structures.
        *
        */
       template <typename Number>
```
Comment (marcfehling) [inline include/deal.II/lac/trilinos_tpetra_types.h:153]:
```suggestion
```

File: include/deal.II/lac/trilinos_tpetra_types.h [hunk 2]
```diff
@@ -145,36 +145,21 @@ namespace LinearAlgebra
...
-       * @brief Typedef for the Kokkos::View type of unmanaged memory.
-       *
-       * Unmanaged means that the view is not allocating data itself, but only
-       * uses an external pointer. Consequently, the memory is not freed upon
-       * destruction of the view.
+       * @brief Typedef for the Kokkos::DualView type.
        * This is needed for shallow copies of deal.II LA structures
        * to Trilinos LA structures.
        */
       template <typename Number, typename MemorySpace>
```
Comment (marcfehling) [inline include/deal.II/lac/trilinos_tpetra_types.h:161]:
```suggestion
```

File: include/deal.II/lac/trilinos_tpetra_precondition.templates.h [hunk 3]
```diff
@@ -216,10 +208,10 @@ namespace LinearAlgebra
...
 
       // 3. Create dual views from the previous ones
-      TpetraTypes::DualViewTypeUnmanaged<Number, MemorySpace> dual_src(
-        dev_src, host_src);
-      TpetraTypes::DualViewTypeUnmanaged<Number, MemorySpace> dual_dst(
-        dev_dst, host_dst);
+      TpetraTypes::DualViewType<Number, MemorySpace> dual_src(dev_src,
+                                                              host_src);
+      TpetraTypes::DualViewType<Number, MemorySpace> dual_dst(dev_dst,
+                                                              host_dst);
```
Comment (marcfehling) [inline include/deal.II/lac/trilinos_tpetra_precondition.templates.h:214]:
```suggestion
      TpetraTypes::DualViewType dual_src(dev_src, host_src);
      TpetraTypes::DualViewType dual_dst(dev_dst, host_dst);
```

File: include/deal.II/lac/trilinos_tpetra_precondition.templates.h [hunk 4]
```diff
@@ -201,12 +197,8 @@ namespace LinearAlgebra
...
       // 1. Make host view with underlying dealii::Vector data.
       //    (This is always a n x 1 matrix since multivector expects that.)
-      TpetraTypes::HostViewTypeUnmanaged<Number> host_src(src.data(),
-                                                          src.size(),
-                                                          1);
-      TpetraTypes::HostViewTypeUnmanaged<Number> host_dst(dst.data(),
-                                                          dst.size(),
-                                                          1);
+      TpetraTypes::HostViewType<Number> host_src(src.data(), src.size(), 1);
+      TpetraTypes::HostViewType<Number> host_dst(dst.data(), dst.size(), 1);
```
Comment (marcfehling) [inline include/deal.II/lac/trilinos_tpetra_precondition.templates.h:201]:
```suggestion
      TpetraTypes::HostViewType host_src(src.data(), src.size(), 1);
      TpetraTypes::HostViewType host_dst(dst.data(), dst.size(), 1);
```

File: include/deal.II/lac/trilinos_tpetra_precondition.templates.h [hunk 5]
```diff
@@ -166,10 +162,10 @@ namespace LinearAlgebra
...
 
       // 3. Create dual views from the previous ones
-      TpetraTypes::DualViewTypeUnmanaged<Number, MemorySpace> dual_src(
-        dev_src, host_src);
-      TpetraTypes::DualViewTypeUnmanaged<Number, MemorySpace> dual_dst(
-        dev_dst, host_dst);
+      TpetraTypes::DualViewType<Number, MemorySpace> dual_src(dev_src,
+                                                              host_src);
+      TpetraTypes::DualViewType<Number, MemorySpace> dual_dst(dev_dst,
+                                                              host_dst);
```
Comment (marcfehling) [inline include/deal.II/lac/trilinos_tpetra_precondition.templates.h:168]:
```suggestion
      TpetraTypes::DualViewType dual_src(dev_src, host_src);
      TpetraTypes::DualViewType dual_dst(dev_dst, host_dst);
```

File: include/deal.II/lac/trilinos_tpetra_precondition.templates.h [hunk 6]
```diff
@@ -151,12 +151,8 @@ namespace LinearAlgebra
...
       // 1. Make host view with underlying dealii::Vector data.
       //    (This is always a n x 1 matrix since multivector expects that.)
-      TpetraTypes::HostViewTypeUnmanaged<Number> host_src(src.data(),
-                                                          src.size(),
-                                                          1);
-      TpetraTypes::HostViewTypeUnmanaged<Number> host_dst(dst.data(),
-                                                          dst.size(),
-                                                          1);
+      TpetraTypes::HostViewType<Number> host_src(src.data(), src.size(), 1);
+      TpetraTypes::HostViewType<Number> host_dst(dst.data(), dst.size(), 1);
```
Comment (marcfehling) [inline include/deal.II/lac/trilinos_tpetra_precondition.templates.h:155]:
```suggestion
      TpetraTypes::HostViewType host_src(src.data(), src.size(), 1);
      TpetraTypes::HostViewType host_dst(dst.data(), dst.size(), 1);
```

**Review by marcfehling — CHANGES_REQUESTED** [review]
Looks like you don't need the template arguments anymore.

**Review by marcfehling — CHANGES_REQUESTED** [review]
I was following the definitions in [`TPetra::MultiVector`](https://docs.trilinos.org/dev/packages/tpetra/doc/html/Tpetra__MultiVector__decl_8hpp_source.html#l00381) and would suggest to recreate their aliases. This way it would be clear that the types were not necessarily limited to `VectorType`. What do you think of this?
```
template <typename Number>
using KokkosNumberType = typename Kokkos::ArithTraits<Number>::val_type;

template <typename MemorySpace>
using DeviceType = typename NodeType<MemorySpace>::device_type;

template <typename Number, typename MemorySpace>
using DualViewType = Kokkos::DualView<KokkosNumberType<Number> **,
                                      Kokkos::LayoutLeft,
                                      DeviceType<MemorySpace>>;

template <typename Number, typename MemorySpace>
using HostViewType = typename DualViewType<Number, MemorySpace>::t_host;
```

I don't feel strongly about this. Feel free to stick to `VectorType::host_view_type` and `VectorType::dual_view_type`.

**Comment by marcfehling** [comment]
Unfortunately, the initial issue from #17434 still persists:
```
FAILED: source/lac/CMakeFiles/object_lac_debug.dir/trilinos_tpetra_precondition.cc.o
/usr/local/pkg/Installs/linux-ubuntu20.04-skylake_avx512/gcc9.4.0/openmpi/4.1.6/k6qlwqr2vx5osaqf/bin/mpicxx -DDEBUG -DKOKKOS_DEPENDENCE -I/build-dealii/source/lac -I/dealii/source/lac -I/build-dealii/include -I/dealii/include -isystem /dealii/bundled/boost-1.84.0/include -isystem /dealii/bundled/umfpack/UMFPACK/Include -isystem /dealii/bundled/umfpack/AMD/Include -isystem /dealii/bundled/muparser_v2_3_3/include -isystem /usr/local/pkg/Installs/linux-ubuntu20.04-skylake_avx512/gcc9.4.0/zlib/1.2.13/sz4h6ncyn4o7aczi/include -isystem /bin/trilinos-15.1.1/include -isystem /usr/local/pkg/Installs/linux-ubuntu20.04-skylake_avx512/gcc9.4.0/gsl/2.6/xmi4tpmfn2a4h4kp/include -isystem /bin/sundials-7.0.0/include -isystem /bin/p4est-2.3.6/FAST/include -std=c++17 -fPIC -pedantic -Wall -Wextra -Wmissing-braces -Woverloaded-virtual -Wpointer-arith -Wsign-compare -Wsuggest-override -Wswitch -Wsynth -Wwrite-strings -Wno-placement-new -Wno-deprecated-declarations -Wno-literal-suffix -Wno-psabi -Wno-unused-local-typedefs -Wno-parentheses -fopenmp-simd -march=skylake-avx512 -O0 -ggdb -Wa,--compress-debug-sections -g -MD -MT source/lac/CMakeFiles/object_lac_debug.dir/trilinos_tpetra_precondition.cc.o -MF source/lac/CMakeFiles/object_lac_debug.dir/trilinos_tpetra_precondition.cc.o.d -o source/lac/CMakeFiles/object_lac_debug.dir/trilinos_tpetra_precondition.cc.o -c /dealii/source/lac/trilinos_tpetra_precondition.cc
In file included from /dealii/source/lac/trilinos_tpetra_precondition.cc:16:
/dealii/include/deal.II/lac/trilinos_tpetra_precondition.templates.h: In instantiation of 'void dealii::LinearAlgebra::TpetraWrappers::PreconditionBase<Number, MemorySpace>::vmult(dealii::Vector<OtherNumber>&, dealii::Vector<OtherNumber>&) const [with Number = std::complex<float>; MemorySpace = dealii::MemorySpace::Host]':
/dealii/source/lac/trilinos_tpetra_precondition.cc:66:20:   required from here
/dealii/include/deal.II/lac/trilinos_tpetra_precondition.templates.h:154:54: error: no matching function for call to 'Kokkos::View<Kokkos::complex<float>**, Kokkos::LayoutLeft, Kokkos::Device<Kokkos::Serial, Kokkos::HostSpace>, Kokkos::Experimental::EmptyViewHooks>::View(dealii::Vector<std::complex<float> >::pointer, dealii::Vector<std::complex<float> >::size_type, int)'
  154 |       TpetraTypes::HostViewType<Number, MemorySpace> host_src(src.data(),
      |                                                      ^~~~~~~~
In file included from /bin/trilinos-15.1.1/include/Kokkos_Parallel.hpp:31,
                 from /bin/trilinos-15.1.1/include/Kokkos_MemoryPool.hpp:26,
                 from /bin/trilinos-15.1.1/include/Kokkos_TaskScheduler.hpp:34,
                 from /bin/trilinos-15.1.1/include/Serial/Kokkos_Serial.hpp:37,
                 from /bin/trilinos-15.1.1/include/decl/Kokkos_Declare_SERIAL.hpp:21,
                 from /bin/trilinos-15.1.1/include/KokkosCore_Config_DeclareBackend.hpp:22,
                 from /bin/trilinos-15.1.1/include/Kokkos_Core.hpp:45,
                 from /bin/trilinos-15.1.1/include/Tpetra_KokkosCompat_ClassicNodeAPI_Wrapper.hpp:4,
                 from /bin/trilinos-15.1.1/include/Tpetra_Details_DefaultTypes.hpp:45,
                 from /bin/trilinos-15.1.1/include/Tpetra_ConfigDefs.hpp:43,
                 from /bin/trilinos-15.1.1/include/Tpetra_Map_decl.hpp:47,
                 from /bin/trilinos-15.1.1/include/Tpetra_Map.hpp:1,
                 from /dealii/include/deal.II/base/index_set.h:34,
                 from /dealii/include/deal.II/lac/trilinos_tpetra_precondition.templates.h:22,
                 from /dealii/source/lac/trilinos_tpetra_precondition.cc:16:
/bin/trilinos-15.1.1/include/Kokkos_View.hpp:1640:35: note: candidate: 'Kokkos::View<DataType, Properties>::View(const typename Kokkos::View<DataType, Properties>::traits::execution_space::scratch_memory_space&, size_t, size_t, size_t, size_t, size_t, size_t, size_t, size_t) [with DataType = Kokkos::complex<float>**; Properties = {Kokkos::LayoutLeft, Kokkos::Device<Kokkos::Serial, Kokkos::HostSpace>, Kokkos::Experimental::EmptyViewHooks}; typename Kokkos::View<DataType, Properties>::traits::execution_space::scratch_memory_space = Kokkos::ScratchMemorySpace<Kokkos::Serial>; size_t = long unsigned int]'
 1640 |   explicit KOKKOS_INLINE_FUNCTION View(
      |                                   ^~~~
/bin/trilinos-15.1.1/include/Kokkos_View.hpp:1641:69: note:   no known conversion for argument 1 from 'dealii::Vector<std::complex<float> >::pointer' {aka 'std::complex<float>*'} to 'const scratch_memory_space&' {aka 'const Kokkos::ScratchMemorySpace<Kokkos::Serial>&'}
 1641 |       const typename traits::execution_space::scratch_memory_space& arg_space,
      |       ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^~~~~~~~~
/bin/trilinos-15.1.1/include/Kokkos_View.hpp:1632:35: note: candidate: 'Kokkos::View<DataType, Properties>::View(const typename Kokkos::View<DataType, Properties>::traits::execution_space::scratch_memory_space&, const typename Kokkos::View<DataType, Properties>::traits::array_layout&) [with DataType = Kokkos::complex<float>**; Properties = {Kokkos::LayoutLeft, Kokkos::Device<Kokkos::Serial, Kokkos::HostSpace>, Kokkos::Experimental::EmptyViewHooks}; typename Kokkos::View<DataType, Properties>::traits::execution_space::scratch_memory_space = Kokkos::ScratchMemorySpace<Kokkos::Serial>; typename Kokkos::View<DataType, Properties>::traits::array_layout = Kokkos::LayoutLeft]'
 1632 |   explicit KOKKOS_INLINE_FUNCTION View(
      |                                   ^~~~
/bin/trilinos-15.1.1/include/Kokkos_View.hpp:1632:35: note:   candidate expects 2 arguments, 3 provided
/bin/trilinos-15.1.1/include/Kokkos_View.hpp:1585:35: note: candidate: 'Kokkos::View<DataType, Properties>::View(Kokkos::View<DataType, Properties>::pointer_type, const typename Kokkos::View<DataType, Properties>::traits::array_layout&) [with DataType = Kokkos::complex<float>**; Properties = {Kokkos::LayoutLeft, Kokkos::Device<Kokkos::Serial, Kokkos::HostSpace>, Kokkos::Experimental::EmptyViewHooks}; Kokkos::View<DataType, Properties>::pointer_type = Kokkos::complex<float>*; typename Kokkos::View<DataType, Properties>::traits::array_layout = Kokkos::LayoutLeft]'
 1585 |   explicit KOKKOS_INLINE_FUNCTION View(
      |                                   ^~~~
/bin/trilinos-15.1.1/include/Kokkos_View.hpp:1585:35: note:   candidate expects 2 arguments, 3 provided
/bin/trilinos-15.1.1/include/Kokkos_View.hpp:1568:35: note: candidate: 'Kokkos::View<DataType, Properties>::View(Kokkos::View<DataType, Properties>::pointer_type, size_t, size_t, size_t, size_t, size_t, size_t, size_t, size_t) [with DataType = Kokkos::complex<float>**; Properties = {Kokkos::LayoutLeft, Kokkos::Device<Kokkos::Serial, Kokkos::HostSpace>, Kokkos::Experimental::EmptyViewHooks}; Kokkos::View<DataType, Properties>::pointer_type = Kokkos::complex<float>*; size_t = long unsigned int]'
 1568 |   explicit KOKKOS_INLINE_FUNCTION View(
      |                                   ^~~~
/bin/trilinos-15.1.1/include/Kokkos_View.hpp:1569:20: note:   no known conversion for argument 1 from 'dealii::Vector<std::complex<float> >::pointer' {aka 'std::complex<float>*'} to 'Kokkos::View<Kokkos::complex<float>**, Kokkos::LayoutLeft, Kokkos::Device<Kokkos::Serial, Kokkos::HostSpace>, Kokkos::Experimental::EmptyViewHooks>::pointer_type' {aka 'Kokkos::complex<float>*'}
 1569 |       pointer_type arg_ptr, const size_t arg_N0 = KOKKOS_IMPL_CTOR_DEFAULT_ARG,
      |       ~~~~~~~~~~~~~^~~~~~~
/bin/trilinos-15.1.1/include/Kokkos_View.hpp:1539:26: note: candidate: 'template<class Traits> Kokkos::View<DataType, Properties>::View(const typename Kokkos::View<DataType, Properties>::view_tracker_type::track_type&, const Kokkos::Impl::ViewMapping<Traits, typename Traits::specialize>&)'
 1539 |   KOKKOS_INLINE_FUNCTION View(
      |                          ^~~~
/bin/trilinos-15.1.1/include/Kokkos_View.hpp:1539:26: note:   template argument deduction/substitution failed:
[...]
```

**Comment by masterleinad** [comment]
> Is it because the deal.II Vector should have a value_type `Kokkos::complex<float>`?

Yes, we would need to `reinterpret_cast` the pointer or manually copy every element on the host.

**Comment by marcfehling** [comment]
Compilation succeeds! :tada:

The issue was introduced in #17183 and is part of the release candidate. Could you take this over to the release branch, too? Thank you!

**Comment by marcfehling** [comment]
Now a tester complains that `host_view_type` is missing. I am confused: To me it looks like this was defines since Trilinos 13.4 https://github.com/trilinos/Trilinos/commit/92b8ea7c84e1bb011ef909935b4dc6f89b62ca17
```
In file included from /__w/dealii/dealii/include/deal.II/lac/trilinos_tpetra_precondition.templates.h:24,
                 from /__w/dealii/dealii/source/lac/trilinos_tpetra_precondition.cc:16:
/__w/dealii/dealii/include/deal.II/lac/trilinos_tpetra_types.h: In substitution of ‘template<class Number> using HostViewType = typename dealii::LinearAlgebra::TpetraWrappers::TpetraTypes::VectorType<Number, dealii::MemorySpace::Host>::host_view_type [with Number = double]’:
/__w/dealii/dealii/include/deal.II/lac/trilinos_tpetra_precondition.templates.h:156:13:   required from ‘void dealii::LinearAlgebra::TpetraWrappers::PreconditionBase<Number, MemorySpace>::vmult(dealii::Vector<Number>&, dealii::Vector<Number>&) const [with Number = double; MemorySpace = dealii::MemorySpace::Host]’
/__w/dealii/dealii/source/lac/trilinos_tpetra_precondition.cc:48:20:   required from here
/__w/dealii/dealii/include/deal.II/lac/trilinos_tpetra_types.h:156:13: error: no type named ‘host_view_type’ in ‘dealii::LinearAlgebra::TpetraWrappers::TpetraTypes::VectorType<double, dealii::MemorySpace::Host>’ {aka ‘class Tpetra::Vector<double, int, long long int, Kokkos::Compat::KokkosDeviceWrapperNode<Kokkos::Serial> >’}
  156 |       using HostViewType =
      |             ^~~~~~~~~~~~
```

**Review by marcfehling — APPROVED** [review]
