### PR TITLE
Guard GCC 11 fixes for intel 18/19 compatibility

### LINKED ISSUE #12507: Intel 19.1 and 19.0 constexpr error
9.3 and master fails with
```
 /home1/08067/msmaier/workspace/dealii/include/deal.II/base/geometry_info.h(2613): error: expression must have a constant value
         internal::GeometryInfoHelper::Initializers<dim>::unit_normal_vector();
         ^
 Note: too few arguments in function call
           detected during:
             instantiation of class "dealii::GeometryInfo<dim> [with dim=3]" at line 330 of "/home1/08067/msmaier/workspace/dealii/source/fe/mapping_cartesian.cc"
             instantiation of "void dealii::MappingCartesian<dim, spacedim>::maybe_update_normal_vectors(unsigned int, const dealii::MappingCartesian<dim, spacedim>::InternalData &, std::vector<dealii::Tensor<1, dim, double>, std::allocator<dealii::Tensor<1, dim, double>>> &) const [with dim=3, spacedim=3]" at line 480 of "/home1/08067/msmaier/workspace/dealii/source/fe/mapping_cartesian.cc"
```
As reported by @tamiko and @zjiaqi2018 

@tamiko has narrowed it down to a single patch. Can you share?

### PR DESCRIPTION
**Pull request by tamiko**
<s>This commit reverts pull request #12246</s>

Closes #12507

### CODE REVIEW

**Comment by tamiko** [comment]
@tjhei This is a plain revert of the changes. We could either try to find another fix for gcc-11 or exclude intel from the preprocessor guard.

**Comment by drwells** [comment]
Do you have GCC11 available? I ran this and got a ton of errors with Sacado.

**Comment by tamiko** [comment]
@drwells 
> Do you have GCC11 available?

Yes, I do have gcc 11.1.0 available.

**Comment by drwells** [comment]
13.0.1. If it would help I can try some permutation of patches.

**Comment by tamiko** [comment]
@drwells @tjhei Update: This revert compiles for me just fine for gcc-11.1.0 with Trilinos 13.0.1 (i.e. sacado enabled). More precisely:
```
% gcc --version
gcc (Gentoo Hardened 11.1.0-r1 p2) 11.1.0
Copyright (C) 2021 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

% eix -I trilinos
[I] sci-libs/trilinos
     Available versions:  (~)13.0.1^t{xpak:2} {X adolc arprec boost clp cuda eigen glpk gtest hdf5 hwloc hypre matio metis mkl mumps netcdf petsc qd scalapack scotch sparse superlu taucs tbb test threads tvmet yaml zlib}
     Installed versions:  13.0.1^t{xpak:2}(11:53:05 AM 06/14/2021)(X boost hdf5 hwloc hypre matio mumps netcdf scalapack scotch tbb zlib -adolc -arprec -clp -cuda -eigen -glpk -gtest -metis -mkl -petsc -qd -sparse -superlu -taucs -test -threads -tvmet -yaml)
```

@mathsen *ping* Would you mind telling us quickly what Trilinos version you used?

**Comment by tjhei** [comment]
So was the hack needed for GCC 11.0 only?

**Comment by drwells** [comment]
[detailed.log](https://github.com/dealii/dealii/files/6728709/detailed.log)

I still get the same errors around Sacado as before.

**Comment by mathsen** [comment]
@tamiko No, I also used gcc 11.1.0 (from arch linux repos):
````
gcc (GCC) 11.1.0
Copyright (C) 2021 Free Software Foundation, Inc.
Dies ist freie Software; die Kopierbedingungen stehen in den Quellen. Es
gibt KEINE Garantie; auch nicht für MARKTGÄNGIGKEIT oder FÜR SPEZIELLE ZWECKE.
````

But I use the trilinos master branch - maybe this is the culprit?

**Comment by drwells** [comment]
11.0 was the development version - 11.1 is the first release.

Perhaps this is some odd Arch Linux-specific behavior? It sounds like things work with Matthias' GCC11 set up. Let me see if I can find another platform for comparison.

**Comment by mathsen** [comment]
@drwells I also tried it with GCC 11.1.0 installed via spack on a base Red Hat system, which resulted in the same error. Reverted there to GCC 10.3.0 and did the debugging on my local workstation. I can give it also another try with the spack GCC 11.1.0

**Comment by drwells** [comment]
That's surprising - perhaps Matthias has the exceptional set up. I am recompiling Trilinos on my mac with gcc11 but this will take awhile.

**Comment by drwells** [comment]
@mathsen if you have time doing one more check would be good because the contradictory results we get with this patch are baffling.

**Comment by mathsen** [comment]
@drwells Yes, no problem. I will do the tests tomorrow with spack and again with my system gcc and report the results here back.

**Comment by tamiko** [comment]
@drwells Baffling, I have almost the same `detailed.log` than yours.

**Comment by drwells** [comment]
I get the same type of errors on my mac with gcc11 (via homebrew):

[detailed.log](https://github.com/dealii/dealii/files/6729383/detailed.log)
```

In file included from /Users/drwells/Documents/CPP/dealii/source/base/symmetric_tensor.cc:19:
/Users/drwells/Documents/CPP/dealii/include/deal.II/base/symmetric_tensor.h: In instantiation of 'constexpr dealii::SymmetricTensor<rank, dim, T> dealii::SymmetricTensor<rank, dim, Number>::operator-() const [with int rank_ = 2; int dim = 1; Number = Sacado::Rad::ADvar<double>]':
/Users/drwells/Documents/CPP/dealii/build-homebrew/source/base/symmetric_tensor.inst:150:16:   required from here
/Users/drwells/Documents/CPP/dealii/include/deal.II/base/symmetric_tensor.h:1645:23: error: use of deleted function 'dealii::Tensor<1, 1, Sacado::Rad::ADvar<double> >& dealii::Tensor<1, 1, Sacado::Rad::ADvar<double> >::operator=(dealii::Tensor<1, 1, Sacado::Rad::ADvar<double> >&&)'
 1645 |   tmp.data            = -tmp.data;
      |   ~~~~~~~~~~~~~~~~~~~~^~~~~~~~~~~
```

**Comment by tamiko** [comment]
I'll dig into the patchset applied to gcc 11 in Gentoo. In any case: Ideally, I would like to identify a small test for this compilation issue that we can add to the cmake configuration and only enable the workaround in that case.

**Comment by mathsen** [comment]
So I just compiled "vanilla" GCC 11.1.0 on a Red Hat system, using GCC 4.8.5 via spack. Spack doesn't apply any patches to the GCC 11.1.0 sources.
Compiling current master branch of deal.II (with all dependencies) using this setup works fine. When trying to build @tamiko [revert branch](https://github.com/tamiko/dealii/tree/revert_gcc11_fixes), I got the same error as reported in [issue 12244.](https://github.com/dealii/dealii/issues/12244)

Here is the corresponding detailed.log (of the failed build):
[detailed.log](https://github.com/dealii/dealii/files/6731286/detailed.log)

I will do another test using the arch GCC 11.1.0 compiler and edit this post when it's finished.

**Comment by tamiko** [comment]
@mathsen Thanks a lot - this is as much as we need. I will bootstrap a gcc 11 without patches and try to extract a minimal test that we can use to enable the constructor definitions if needed.

**Comment by tamiko** [comment]
@mathsen @drwells Would you mind testing the following snippet for me?
```

struct NonMovable {
  NonMovable(NonMovable&&) = delete;
};

template <class T>
struct Maybe {
  NonMovable mMember;

  template <typename U>
  Maybe(Maybe<U>&&);
};

void foo(Maybe<int>);

void unlucky(Maybe<int>&& x) {
  Maybe<int> var{(Maybe<int>&&)x};
}
```

**Comment by drwells** [comment]
```
[drwells@archway gcc11-bug-workaround]$ cat bug.cc

struct NonMovable {
  NonMovable(NonMovable&&) = delete;
};

template <class T>
struct Maybe {
  NonMovable mMember;

  template <typename U>
  Maybe(Maybe<U>&&);
};

void foo(Maybe<int>);

void unlucky(Maybe<int>&& x) {
  Maybe<int> var{(Maybe<int>&&)x};
}
[drwells@archway gcc11-bug-workaround]$ g++ -c bug.cc
bug.cc: In function 'void unlucky(Maybe<int>&&)':
bug.cc:17:33: error: use of deleted function 'Maybe<int>::Maybe(Maybe<int>&&)'
   17 |   Maybe<int> var{(Maybe<int>&&)x};
      |                                 ^
bug.cc:7:8: note: 'Maybe<int>::Maybe(Maybe<int>&&)' is implicitly deleted because the default definition would be ill-formed:                               
    7 | struct Maybe {
      |        ^~~~~
bug.cc:7:8: error: use of deleted function 'NonMovable::NonMovable(NonMovable&&)'
bug.cc:3:3: note: declared here
    3 |   NonMovable(NonMovable&&) = delete;
      |   ^~~~~~~~~~
[drwells@archway gcc11-bug-workaround]$ 
```

**Comment by drwells** [comment]
If it helps, I checked that godbolt does not patch this bug so you can reproduce this there too. clang++ is happy to compile the snippet.

**Comment by tamiko** [comment]
Excellent. Refactoring now.

**Comment by tamiko** [comment]
Timo: Yes, this is only necessary for gcc-11.1. On the bright side none of the major distros will likely make a release in the near furute with gcc-11.1 and by the time gcc-11.2 is out this workaround becomes obsolete. I will refactor with an explicit bug check in cmake that only enables the fixes when necessary.

**Comment by tamiko** [comment]
@drwells @mathsen @tjhei Alright, let's give this version a spin.

For gcc-11.1.0 without the regression patch we should see:
```
-- Include /home/tamiko/workspace/dealii/cmake/checks/check_03_compiler_bugs.cmake
-- Performing Test DEAL_II_DELETED_MOVE_CONSTRUCTOR_BUG_OK
-- Performing Test DEAL_II_DELETED_MOVE_CONSTRUCTOR_BUG_OK - Failed
-- Test unsuccessful, define DEAL_II_DELETED_MOVE_CONSTRUCTOR_BUG
```

The test passes for clang and gcc (with upstream patch) on my system. I will now check compilation with intel-19.

**Comment by tjhei** [comment]
@zjiaqi2018 can you please test this PR with the Intel compiler versions available on palmetto?

**Comment by drwells** [comment]
Looks good - I see
```
-- Performing Test DEAL_II_DELETED_MOVE_CONSTRUCTOR_BUG_OK
-- Performing Test DEAL_II_DELETED_MOVE_CONSTRUCTOR_BUG_OK - Failed
-- Test unsuccessful, define DEAL_II_DELETED_MOVE_CONSTRUCTOR_BUG
```

**Comment by drwells** [comment]
The fix isn't done yet. I get errors of the form
```
/home/drwells/Documents/Code/CPP/dealii-dev/include/deal.II/base/tensor.h:1040:1: error: redefinition of 'constexpr dealii::Tensor<0, dim, Number>& dealii::Tensor<0, dim, Number>::operator=(const dealii::Tensor<0, dim, Number>&)'
 1040 | Tensor<0, dim, Number>::operator=(const Tensor<0, dim, Number> &other)
      | ^~~~~~~~~~~~~~~~~~~~~~
/home/drwells/Documents/Code/CPP/dealii-dev/include/deal.II/base/tensor.h:1030:3: note: 'constexpr dealii::Tensor<0, dim, Number>& dealii::Tensor<0, dim, Number>::operator=(const dealii::Tensor<0, dim, Number>&)' previously declared here
 1030 |   Tensor<0, dim, Number>::operator=(const Tensor<0, dim, Number> &p)
      |   ^~~~~~~~~~~~~~~~~~~~~~
```

**Comment by tamiko** [comment]
@drwells Copy and paste SNAFU. Fixing.

**Comment by tamiko** [comment]
@drwells Fixed. Hopefully. Currently compiling.

**Comment by drwells** [comment]
The fix works for me.

**Review by drwells — APPROVED** [review]
Things work with GCC11 and Intel (I tried 18.2 and 20.2) so this is ready.

**Comment by zjiaqi2018** [comment]
> @zjiaqi2018 can you please test this PR with the Intel compiler versions available on palmetto?

It works perfectly with intel 19.1 except for the OpenMP warning
`dealii/include/deal.II/matrix_free/mapping_info.templates.h(2288): warning #16219: Some OpenMP processing was skipped to constrain compile time. Consider overriding limits (-qoverride-limits).
`

**Comment by drwells** [comment]
That warning isn't related so lets merge.
