### PR TITLE
Fix unity build with clang-3.5.

### PR DESCRIPTION
**Pull request by kronbichler**
clang-3.5 complained about the new unity build from #4442 due to two problems:
```
In file included from /data/kronbichler/deal/serial_build/source/grid/unity_0.cc:10:
/home/kronbichler/deal/deal.II/source/grid/grid_reordering.cc:1105:20: error: explicit specialization of
      'invert_all_cells_of_negative_grid' after instantiation
GridReordering<1>::invert_all_cells_of_negative_grid(const std::vector<Point<1> > &,
                   ^
/home/kronbichler/deal/deal.II/source/grid/grid_in.cc:367:40: note: implicit instantiation first required here
        GridReordering<dim, spacedim>::invert_all_cells_of_negative_grid(vertices,
                                       ^
```
(two more errors in lines `1115` and `1125` in `grid_reordering.cc`) and
```
In file included from /data/kronbichler/deal/serial_build/source/base/unity_0.cc:21:
/home/kronbichler/deal/deal.II/source/base/geometry_info.cc:113:37: error: explicit specialization of 'ucd_to_deal' after
      instantiation
const unsigned int GeometryInfo<1>::ucd_to_deal[GeometryInfo<1>::vertices_per_cell]
                                    ^
/home/kronbichler/deal/deal.II/source/base/data_out_base.cc:7729:48: note: implicit instantiation first required here
      out << patch.vertices[GeometryInfo<dim>::ucd_to_deal[i]] << ' ';
                                               ^
```
(and a few more errors of the same kind). In order to work around this issue, the two alternatives I see is to add the declarations of the explicit specializations in the header files - which I do not really like - or to exclude these files from the unity build, since it's only two files. And at least `data_out_base` is a pretty large compilation unit already anyway.

### CODE REVIEW

**Comment by bangerth** [comment]
This works. But what is wrong with declaring the explicit specializations? The standard actually says that we have to do that anyway.

**Comment by kronbichler** [comment]
It is a long list of explicit specializations that would need to go to the header file (e.g. 6 occurrences for the former error). You know more about the standard than I do, so is it right that we do a specialization when we provide all implementations of a member function of a templated class that gets instantiated with fixed value of the template? I thought we would have that only if we have a generic *templated* version of that particular function and then a few additional specialized ones... Anyway, I fail to see why this would work for the original case or why it works for gcc. It must be a gray zone it seems.

**Comment by drwells** [comment]
@kronbichler thanks for fixing this 👍 

The grid reordering issue is interesting since we do provide specializations for the 1D functions as well (but we don't explicitly say so in the header). I am working on a patch that should clarify what we specialize.

**Comment by bangerth** [comment]
@kronbichler -- I don't think I completely understand your question, but here is the gist of it: if you have a class like this in a header file,
```
  template <int dim> class X {
     void f();
  }
```
and then this in the `.cc` file, as we have in many places:
```
  template <int dim> void X<dim>::f() { ... }   // general template
  template <>            void X<1>::f() { ... }       // explicit specialization of a member function

  template class X<1>;     // explicit instantiation of classes
  template class X<2>;
```
Then, strictly speaking, the code would require us to put this also into the header file:
```
  template <>            void X<1>::f();    // forward declaration for the existence of a specialization
```

This is so because the standard wants to allow compilers to use a different mangling for functions that (i) result from instantiation of a template, and (ii) explicit specializations of class template member functions. This is relevant because if there were no explicit specialization in the .cc file, we would get `X<1>::f()` via (i), but as it is written above, we get `X<1>::f()` from (ii).

Because these two can have different manglings, it is important that the explicit specialization be forward declared at the point where they are used. This may be in a different `.cc` file, and consequently the explicit specialization needs to be in the `.h` file.

Now, why do we never see compiler errors for this? (Or, better, linker errors: the absence of a forward declaration would make the compiler think that `X<1>::f()` results from an explicit *instantiation* of the function from the general template, and put a reference to that function in; but only the differently mangled form of the explicit *specialization* is available to the linker and it will complain loudly.) The reason is that while the standard gives compilers *permission* to mangle these differently, most compilers do not actually make use of this permission. In particular, the linux ABI for the x86_64 platform prescribes a mangling scheme that results in the same mangled symbols for options (i) and (ii) above.

So we don't get linker errors. But we could on other platforms and other compilers. I suspect nobody would be silly enough today to design such a different ABI, but I recall that ~15 years ago, such compilers still existed on platforms like DEC or AIX. I don't recall specifics, but do recall that I needed to go in and add the forward declarations for these explicit specializations to make the whole thing compile and link.
