### PR TITLE
Fix process_dof_indices (for artificial faces in DoFTools::set_periodicity_constraints)

### PR DESCRIPTION
**Pull request by peterrum**
Fix a bug introduced by #12032. `DoFTools::set_periodicity_constraints` was not working for artifical faces anymore...

### CODE REVIEW

**Comment by drwells** [comment]
Is there a corresponding test for this?

**Comment by peterrum** [comment]
Yes. `mpi/periodicity*`.

**Review by drwells — APPROVED** [review]

**Review by kronbichler — APPROVED** [review]

**Review by masterleinad — APPROVED** [review]

**Comment by masterleinad** [comment]
```
/home/runner/work/dealii/dealii/include/deal.II/dofs/dof_accessor.templates.h:898:28: error: unused variable ‘n_dofs_active’ [-Werror=unused-variable]
         const unsigned int n_dofs_active =
```
