### PR TITLE
Enable complex build.

### PR DESCRIPTION
**Pull request by marcfehling**
This patch enables building with complex values on our `linux/debug-parallel` workflow to achieve higher testing coverage.

Workflow will fail at the moment due to https://github.com/dealii/dealii/pull/19803#issuecomment-4620494998.

### CODE REVIEW

**Comment by bangerth** [comment]
Probably a useful patch given that we're catching errors:
```
/__w/dealii/dealii/include/deal.II/numerics/error_estimator.templates.h:380:53: error: cannot convert ‘dealii::Tensor<0, 3, std::complex<double> >::tensor_type’ {aka ‘std::complex<double>’} to ‘dealii::AlignedVector<double>::value_type’ {aka ‘double’} in assignment
  380 |             (parallel_data.psi(n, point)[component] *
      |             ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^
      |                                                     |
      |                                                     dealii::Tensor<0, 3, std::complex<double> >::tensor_type {aka std::complex<double>}
  381 |              parallel_data.normal_vectors[point]);
      |              ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~    
/__w/dealii/dealii/include/deal.II/numerics/error_estimator.templates.h:391:50: error: no match for ‘operator+=’ (operand types are ‘dealii::AlignedVector<double>::value_type’ {aka ‘double’} and ‘dealii::Tensor<0, 3, std::complex<double> >::tensor_type’ {aka ‘std::complex<double>’})
  391 |               parallel_data.phi(n, p, component) +=
      |               ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^~
  392 |                 (parallel_data.neighbor_psi(n, p)[component] *
      |                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
  393 |                  parallel_data.neighbor_normal_vectors[p]);
      |                  ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/__w/dealii/dealii/include/deal.II/numerics/error_estimator.templates.h:450:48: error: no match for ‘operator-=’ (operand types are ‘dealii::AlignedVector<double>::value_type’ {aka ‘double’} and ‘__gnu_cxx::__alloc_traits<std::allocator<std::complex<double> >, std::complex<double> >::value_type’ {aka ‘std::complex<double>’})
  450 |                 parallel_data.phi(n, point, 0) -=
      |                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^~
  451 |                   parallel_data.neumann_values1[point];
      |                   ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/__w/dealii/dealii/include/deal.II/numerics/error_estimator.templates.h:465:58: error: no match for ‘operator-=’ (operand types are ‘dealii::AlignedVector<double>::value_type’ {aka ‘double’} and ‘std::complex<double>’)
  465 |                   parallel_data.phi(n, point, component) -=
      |                   ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^~
  466 |                     parallel_data.neumann_values[point](component);
      |                     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
```

**Comment by bangerth** [comment]
I see that @drwells already fixed that. @marcfehling Want to rebase?

**Comment by marcfehling** [comment]
> Want to rebase?

Done!

**Review by drwells — APPROVED** [review]

**Review by masterleinad — APPROVED** [review]
