### ISSUE TITLE
Compilation failure on the tester when compiling with clang (cgal 5.2.2)

### ISSUE THREAD

**Issue by tamiko** [dealii/dealii#14319]
I encounter the following compilation error on the tester for the last two weeks: [1, 2]
```
source/cgal/intersections.cc:719: error: no matching function for call to 'get_vertices_in_cgal_order'

      CGALWrappers::get_vertices_in_cgal_order<int(std::pow(2, dim0))>(
      ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
```

<s>This doesn't seem to happen with CGAL 5.5.</s>

@luca-heltai @jh66637 A wild guess that this is related to 41630d07d67adc1361e9d18d7b3368add10fda16

[1] https://cdash.dealii.org/viewBuildError.php?buildid=227
[2] https://github.com/dealii/dealii/blob/master/source/cgal/intersections.cc#L719

**Comment by tamiko** [comment]
Trying to reproduce...

**Comment by tamiko** [comment]
Ah, this is ill-formed: (introduced in 41630d07d67)
```
718     const auto vertices0 =                                                       
719       CGALWrappers::get_vertices_in_cgal_order<int(std::pow(2, dim0))>(          
720         cell0, mapping0);                                                        
721     const auto vertices1 =                                                       
722       CGALWrappers::get_vertices_in_cgal_order<int(std::pow(2, dim1))>(          
723         cell1, mapping1); 
```

In this context the call to `std::pow` loses the constexpr and the final expression cannot be used as template argument. gcc seems to be incorrectly accepting it. See https://bugs.llvm.org/show_bug.cgi?id=41093 for a related discussion.

**Comment by tamiko** [comment]
Minimal reproducer:
```
#include <cmath>

int main()
{
  constexpr int dim = 1;
  constexpr int size = std::pow(2, dim);
}
```
gcc compiles this expression, clang correctly complains:
```
test.cc:6:17: error: constexpr variable 'size' must be initialized by a constant expression
  constexpr int size = std::pow(2, dim);
                ^      ~~~~~~~~~~~~~~~~
/usr/lib/gcc/x86_64-pc-linux-gnu/12.2.1/include/g++-v12/cmath:418:14: note: non-constexpr function 'pow' cannot be used in a constant expression
      return pow(__type(__x), __type(__y));
             ^
test.cc:6:24: note: in call to 'pow(2, 1)'
  constexpr int size = std::pow(2, dim);
                       ^
/usr/include/bits/mathcalls.h:140:17: note: declared here
__MATHCALL_VEC (pow,, (_Mdouble_ __x, _Mdouble_ __y));
                ^
1 error generated.
```
