### PR TITLE
Remove unnecessary include file

### PR DESCRIPTION
**Pull request by kronbichler**
As far as I can see, there is not reference to `VectorTools` in this file.

### CODE REVIEW

**Comment by peterrum** [comment]
> /jenkins/workspace/dealii-tidy_PR-13244/include/deal.II/matrix_free/fe_point_evaluation.h:882:11: error: implicit conversion 'dealii::UpdateFlags' -> bool [readability-implicit-bool-conversion,-warnings-as-errors]
/jenkins/workspace/dealii-tidy_PR-13244/include/deal.II/matrix_free/fe_point_evaluation.h:886:11: error: implicit conversion 'dealii::UpdateFlags' -> bool [readability-implicit-bool-conversion,-warnings-as-errors]
/jenkins/workspace/dealii-tidy_PR-13244/include/deal.II/matrix_free/fe_point_evaluation.h:893:11: error: implicit conversion 'dealii::UpdateFlags' -> bool [readability-implicit-bool-conversion,-warnings-as-errors]

Introduced by #12983. We should disable the check until we have a decision!

**Review by peterrum — APPROVED** [review]

**Comment by kronbichler** [comment]
Let us merge this one as it does not affect any of the tidy checks.
