### PR TITLE
Second order derivatives for simplex shape functions

### PR DESCRIPTION
**Pull request by dominiktassilostill**
In #19921 some test fail as the implementation for second order derivatives in `ScalarLagrangePolynomialSimplex` are missing. This PR adds the needed functionality. The code relies on the higher order derivatives of the Jacobi polynomials introduced in #19958 and the homogenized Jacobi polynomials from #19959.

### CODE REVIEW

**Comment by kronbichler** [comment]
This has a number of build warnings/errors on the CI, see:
```
/__w/dealii/dealii/source/base/polynomials_simplex.cc: In member function ‘virtual dealii::Tensor<2, dim> dealii::ScalarLagrangePolynomialSimplex<dim>::evaluate_orthogonal_basis_2nd_derivative_by_degree(unsigned int, unsigned int, unsigned int, const dealii::Point<dim>&) const’:
/__w/dealii/dealii/source/base/polynomials_simplex.cc:429:22: error: ‘jacobi_polynomial_homogenized_value’ is not a member of ‘dealii::Polynomials’; did you mean ‘jacobi_polynomial_value’?
  429 |         Polynomials::jacobi_polynomial_homogenized_value<double>(i, 0, 0, x, s);
      |                      ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
      |                      jacobi_polynomial_value
/__w/dealii/dealii/source/base/polynomials_simplex.cc:429:58: error: expected primary-expression before ‘double’
  429 |         Polynomials::jacobi_polynomial_homogenized_value<double>(i, 0, 0, x, s);
      |                                                          ^~~~~~
/__w/dealii/dealii/source/base/polynomials_simplex.cc:434:22: error: ‘jacobi_polynomial_homogenized_derivative’ is not a member of ‘dealii::Polynomials’; did you mean ‘jacobi_polynomial_derivative’?
  434 |         Polynomials::jacobi_polynomial_homogenized_derivative<double>(
      |                      ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
      |                      jacobi_polynomial_derivative
/__w/dealii/dealii/source/base/polynomials_simplex.cc:434:63: error: expected primary-expression before ‘double’
  434 |         Polynomials::jacobi_polynomial_homogenized_derivative<double>(
      |                                                               ^~~~~~
/__w/dealii/dealii/source/base/polynomials_simplex.cc:437:22: error: ‘jacobi_polynomial_homogenized_derivative’ is not a member of ‘dealii::Polynomials’; did you mean ‘jacobi_polynomial_derivative’?
  437 |         Polynomials::jacobi_polynomial_homogenized_derivative<double>(
      |                      ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
      |                      jacobi_polynomial_derivative
/__w/dealii/dealii/source/base/polynomials_simplex.cc:437:63: error: expected primary-expression before ‘double’
  437 |         Polynomials::jacobi_polynomial_homogenized_derivative<double>(
      |                                                               ^~~~~~
/__w/dealii/dealii/source/base/polynomials_simplex.cc:444:22: error: ‘jacobi_polynomial_homogenized_derivative’ is not a member of ‘dealii::Polynomials’; did you mean ‘jacobi_polynomial_derivative’?
  444 |         Polynomials::jacobi_polynomial_homogenized_derivative<double>(
      |                      ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
      |                      jacobi_polynomial_derivative
/__w/dealii/dealii/source/base/polynomials_simplex.cc:444:63: error: expected primary-expression before ‘double’
  444 |         Polynomials::jacobi_polynomial_homogenized_derivative<double>(
      |                                                               ^~~~~~
/__w/dealii/dealii/source/base/polynomials_simplex.cc:447:22: error: ‘jacobi_polynomial_homogenized_derivative’ is not a member of ‘dealii::Polynomials’; did you mean ‘jacobi_polynomial_derivative’?
  447 |         Polynomials::jacobi_polynomial_homogenized_derivative<double>(
      |                      ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
      |                      jacobi_polynomial_derivative
/__w/dealii/dealii/source/base/polynomials_simplex.cc:447:63: error: expected primary-expression before ‘double’
  447 |         Polynomials::jacobi_polynomial_homogenized_derivative<double>(
      |                                                               ^~~~~~
/__w/dealii/dealii/source/base/polynomials_simplex.cc:450:22: error: ‘jacobi_polynomial_homogenized_derivative’ is not a member of ‘dealii::Polynomials’; did you mean ‘jacobi_polynomial_derivative’?
  450 |         Polynomials::jacobi_polynomial_homogenized_derivative<double>(
      |                      ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
      |                      jacobi_polynomial_derivative
/__w/dealii/dealii/source/base/polynomials_simplex.cc:450:63: error: expected primary-expression before ‘double’
  450 |         Polynomials::jacobi_polynomial_homogenized_derivative<double>(
      |                                                               ^~~~~~
/__w/dealii/dealii/source/base/polynomials_simplex.cc:454:58: error: too many arguments to function ‘Number dealii::Polynomials::jacobi_polynomial_derivative(unsigned int, int, int, Number, bool) [with Number = double]’
  454 |         Polynomials::jacobi_polynomial_derivative<double>(
      |         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^
  455 |           2, j, 2 * i + 1, 0, y, true);
      |           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~                    
In file included from /__w/dealii/dealii/source/base/polynomials_simplex.cc:21:
/__w/dealii/dealii/include/deal.II/base/polynomial.h:1138:3: note: declared here
 1138 |   jacobi_polynomial_derivative(const unsigned int degree,
      |   ^~~~~~~~~~~~~~~~~~~~~~~~~~~~
/__w/dealii/dealii/source/base/polynomials_simplex.cc:488:22: error: ‘jacobi_polynomial_homogenized_value’ is not a member of ‘dealii::Polynomials’; did you mean ‘jacobi_polynomial_value’?
  488 |         Polynomials::jacobi_polynomial_homogenized_value<double>(i, 0, 0, x, t);
      |                      ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
      |                      jacobi_polynomial_value
/__w/dealii/dealii/source/base/polynomials_simplex.cc:488:58: error: expected primary-expression before ‘double’
  488 |         Polynomials::jacobi_polynomial_homogenized_value<double>(i, 0, 0, x, t);
      |                                                          ^~~~~~
/__w/dealii/dealii/source/base/polynomials_simplex.cc:490:22: error: ‘jacobi_polynomial_homogenized_value’ is not a member of ‘dealii::Polynomials’; did you mean ‘jacobi_polynomial_value’?
  490 |         Polynomials::jacobi_polynomial_homogenized_value<double>(
      |                      ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
      |                      jacobi_polynomial_value
/__w/dealii/dealii/source/base/polynomials_simplex.cc:490:58: error: expected primary-expression before ‘double’
  490 |         Polynomials::jacobi_polynomial_homogenized_value<double>(
      |                                                          ^~~~~~
/__w/dealii/dealii/source/base/polynomials_simplex.cc:496:22: error: ‘jacobi_polynomial_homogenized_derivative’ is not a member of ‘dealii::Polynomials’; did you mean ‘jacobi_polynomial_derivative’?
  496 |         Polynomials::jacobi_polynomial_homogenized_derivative<double>(
      |                      ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
      |                      jacobi_polynomial_derivative
/__w/dealii/dealii/source/base/polynomials_simplex.cc:496:63: error: expected primary-expression before ‘double’
  496 |         Polynomials::jacobi_polynomial_homogenized_derivative<double>(
      |                                                               ^~~~~~
/__w/dealii/dealii/source/base/polynomials_simplex.cc:499:22: error: ‘jacobi_polynomial_homogenized_derivative’ is not a member of ‘dealii::Polynomials’; did you mean ‘jacobi_polynomial_derivative’?
  499 |         Polynomials::jacobi_polynomial_homogenized_derivative<double>(
      |                      ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
      |                      jacobi_polynomial_derivative
/__w/dealii/dealii/source/base/polynomials_simplex.cc:499:63: error: expected primary-expression before ‘double’
  499 |         Polynomials::jacobi_polynomial_homogenized_derivative<double>(
      |                                                               ^~~~~~
/__w/dealii/dealii/source/base/polynomials_simplex.cc:503:22: error: ‘jacobi_polynomial_homogenized_derivative’ is not a member of ‘dealii::Polynomials’; did you mean ‘jacobi_polynomial_derivative’?
  503 |         Polynomials::jacobi_polynomial_homogenized_derivative<double>(
      |                      ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
      |                      jacobi_polynomial_derivative
/__w/dealii/dealii/source/base/polynomials_simplex.cc:503:63: error: expected primary-expression before ‘double’
  503 |         Polynomials::jacobi_polynomial_homogenized_derivative<double>(
      |                                                               ^~~~~~
/__w/dealii/dealii/source/base/polynomials_simplex.cc:506:22: error: ‘jacobi_polynomial_homogenized_derivative’ is not a member of ‘dealii::Polynomials’; did you mean ‘jacobi_polynomial_derivative’?
  506 |         Polynomials::jacobi_polynomial_homogenized_derivative<double>(
      |                      ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
      |                      jacobi_polynomial_derivative
/__w/dealii/dealii/source/base/polynomials_simplex.cc:506:63: error: expected primary-expression before ‘double’
  506 |         Polynomials::jacobi_polynomial_homogenized_derivative<double>(
      |                                                               ^~~~~~
/__w/dealii/dealii/source/base/polynomials_simplex.cc:513:22: error: ‘jacobi_polynomial_homogenized_derivative’ is not a member of ‘dealii::Polynomials’; did you mean ‘jacobi_polynomial_derivative’?
  513 |         Polynomials::jacobi_polynomial_homogenized_derivative<double>(
      |                      ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
      |                      jacobi_polynomial_derivative
/__w/dealii/dealii/source/base/polynomials_simplex.cc:513:63: error: expected primary-expression before ‘double’
  513 |         Polynomials::jacobi_polynomial_homogenized_derivative<double>(
      |                                                               ^~~~~~
/__w/dealii/dealii/source/base/polynomials_simplex.cc:516:22: error: ‘jacobi_polynomial_homogenized_derivative’ is not a member of ‘dealii::Polynomials’; did you mean ‘jacobi_polynomial_derivative’?
  516 |         Polynomials::jacobi_polynomial_homogenized_derivative<double>(
      |                      ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
      |                      jacobi_polynomial_derivative
/__w/dealii/dealii/source/base/polynomials_simplex.cc:516:63: error: expected primary-expression before ‘double’
  516 |         Polynomials::jacobi_polynomial_homogenized_derivative<double>(
      |                                                               ^~~~~~
/__w/dealii/dealii/source/base/polynomials_simplex.cc:519:22: error: ‘jacobi_polynomial_homogenized_derivative’ is not a member of ‘dealii::Polynomials’; did you mean ‘jacobi_polynomial_derivative’?
  519 |         Polynomials::jacobi_polynomial_homogenized_derivative<double>(
      |                      ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
      |                      jacobi_polynomial_derivative
/__w/dealii/dealii/source/base/polynomials_simplex.cc:519:63: error: expected primary-expression before ‘double’
  519 |         Polynomials::jacobi_polynomial_homogenized_derivative<double>(
      |                                                               ^~~~~~
/__w/dealii/dealii/source/base/polynomials_simplex.cc:523:22: error: ‘jacobi_polynomial_homogenized_derivative’ is not a member of ‘dealii::Polynomials’; did you mean ‘jacobi_polynomial_derivative’?
  523 |         Polynomials::jacobi_polynomial_homogenized_derivative<double>(
      |                      ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
      |                      jacobi_polynomial_derivative
/__w/dealii/dealii/source/base/polynomials_simplex.cc:523:63: error: expected primary-expression before ‘double’
  523 |         Polynomials::jacobi_polynomial_homogenized_derivative<double>(
      |                                                               ^~~~~~
/__w/dealii/dealii/source/base/polynomials_simplex.cc:526:22: error: ‘jacobi_polynomial_homogenized_derivative’ is not a member of ‘dealii::Polynomials’; did you mean ‘jacobi_polynomial_derivative’?
  526 |         Polynomials::jacobi_polynomial_homogenized_derivative<double>(
      |                      ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
      |                      jacobi_polynomial_derivative
/__w/dealii/dealii/source/base/polynomials_simplex.cc:526:63: error: expected primary-expression before ‘double’
  526 |         Polynomials::jacobi_polynomial_homogenized_derivative<double>(
      |                                                               ^~~~~~
/__w/dealii/dealii/source/base/polynomials_simplex.cc:529:22: error: ‘jacobi_polynomial_homogenized_derivative’ is not a member of ‘dealii::Polynomials’; did you mean ‘jacobi_polynomial_derivative’?
  529 |         Polynomials::jacobi_polynomial_homogenized_derivative<double>(
      |                      ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
      |                      jacobi_polynomial_derivative
/__w/dealii/dealii/source/base/polynomials_simplex.cc:529:63: error: expected primary-expression before ‘double’
  529 |         Polynomials::jacobi_polynomial_homogenized_derivative<double>(
      |                                                               ^~~~~~
/__w/dealii/dealii/source/base/polynomials_simplex.cc:533:58: error: too many arguments to function ‘Number dealii::Polynomials::jacobi_polynomial_derivative(unsigned int, int, int, Number, bool) [with Number = double]’
  533 |         Polynomials::jacobi_polynomial_derivative<double>(
      |         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^
  534 |           2, k, 2 * (i + j) + 2, 0, z, true);
      |           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~              
In file included from /__w/dealii/dealii/source/base/polynomials_simplex.cc:21:
/__w/dealii/dealii/include/deal.II/base/polynomial.h:1138:3: note: declared here
 1138 |   jacobi_polynomial_derivative(const unsigned int degree,
      |   ^~~~~~~~~~~~~~~~~~~~~~~~~~~~
/__w/dealii/dealii/source/base/polynomials_simplex.cc: In instantiation of ‘dealii::Tensor<2, dim> dealii::ScalarLagrangePolynomialSimplex<dim>::evaluate_orthogonal_basis_2nd_derivative_by_degree(unsigned int, unsigned int, unsigned int, const dealii::Point<dim>&) const [with int dim = 1]’:
/__w/dealii/dealii/source/base/polynomials_simplex.cc:633:16:   required from here
/__w/dealii/dealii/source/base/polynomials_simplex.cc:407:70: error: too many arguments to function ‘Number dealii::Polynomials::jacobi_polynomial_derivative(unsigned int, int, int, Number, bool) [with Number = double]’
  407 |       deriv[0][0] = Polynomials::jacobi_polynomial_derivative<double>(
      |                     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^
  408 |         2, i, 0, 0, p[0], true);
      |         ~~~~~~~~~~~~~~~~~~~~~~~                                       
In file included from /__w/dealii/dealii/source/base/polynomials_simplex.cc:21:
/__w/dealii/dealii/include/deal.II/base/polynomial.h:1138:3: note: declared here
 1138 |   jacobi_polynomial_derivative(const unsigned int degree,
      |   ^~~~~~~~~~~~~~~~~~~~~~~~~~~~
/__w/dealii/dealii/source/base/polynomials_simplex.cc: In instantiation of ‘dealii::Tensor<2, dim> dealii::ScalarLagrangePolynomialSimplex<dim>::evaluate_orthogonal_basis_2nd_derivative_by_degree(unsigned int, unsigned int, unsigned int, const dealii::Point<dim>&) const [with int dim = 2]’:
/__w/dealii/dealii/source/base/polynomials_simplex.cc:634:16:   required from here
/__w/dealii/dealii/source/base/polynomials_simplex.cc:454:58: error: too many arguments to function ‘Number dealii::Polynomials::jacobi_polynomial_derivative(unsigned int, int, int, Number, bool) [with Number = double]’
  454 |         Polynomials::jacobi_polynomial_derivative<double>(
      |         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^
  455 |           2, j, 2 * i + 1, 0, y, true);
      |           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~                    
In file included from /__w/dealii/dealii/source/base/polynomials_simplex.cc:21:
/__w/dealii/dealii/include/deal.II/base/polynomial.h:1138:3: note: declared here
 1138 |   jacobi_polynomial_derivative(const unsigned int degree,
      |   ^~~~~~~~~~~~~~~~~~~~~~~~~~~~
/__w/dealii/dealii/source/base/polynomials_simplex.cc:423:20: error: unused variable ‘x’ [-Werror=unused-variable]
  423 |       const double x     = p[0];
      |                    ^
/__w/dealii/dealii/source/base/polynomials_simplex.cc:425:20: error: unused variable ‘s’ [-Werror=unused-variable]
  425 |       const double s     = 1 - y;
      |                    ^
/__w/dealii/dealii/source/base/polynomials_simplex.cc: In instantiation of ‘dealii::Tensor<2, dim> dealii::ScalarLagrangePolynomialSimplex<dim>::evaluate_orthogonal_basis_2nd_derivative_by_degree(unsigned int, unsigned int, unsigned int, const dealii::Point<dim>&) const [with int dim = 3]’:
/__w/dealii/dealii/source/base/polynomials_simplex.cc:635:16:   required from here
/__w/dealii/dealii/source/base/polynomials_simplex.cc:533:58: error: too many arguments to function ‘Number dealii::Polynomials::jacobi_polynomial_derivative(unsigned int, int, int, Number, bool) [with Number = double]’
  533 |         Polynomials::jacobi_polynomial_derivative<double>(
      |         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^
  534 |           2, k, 2 * (i + j) + 2, 0, z, true);
      |           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~              
In file included from /__w/dealii/dealii/source/base/polynomials_simplex.cc:21:
/__w/dealii/dealii/include/deal.II/base/polynomial.h:1138:3: note: declared here
 1138 |   jacobi_polynomial_derivative(const unsigned int degree,
      |   ^~~~~~~~~~~~~~~~~~~~~~~~~~~~
/__w/dealii/dealii/source/base/polynomials_simplex.cc:476:20: error: unused variable ‘x’ [-Werror=unused-variable]
  476 |       const double x = p[0];
      |                    ^
/__w/dealii/dealii/source/base/polynomials_simplex.cc:480:20: error: unused variable ‘s’ [-Werror=unused-variable]
  480 |       const double s     = 1 - z;
      |                    ^
/__w/dealii/dealii/source/base/polynomials_simplex.cc:483:20: error: unused variable ‘t’ [-Werror=unused-variable]
  483 |       const double t     = 1 - y - z;
      |                    ^
cc1plus: all warnings being treated as errors
```
Can you please have a look?

**Comment by dominiktassilostill** [comment]
> This has a number of build warnings/errors on the CI, see:
> Can you please have a look?

It relies on the functions implemented in #19958 and #19959, that is why it is failing for now, could have made that clear in the description:(  

The method in #19959 came up here as it is very tedious to derive all special cases by hand and with the new functions they are all covered, which makes the code also much more simple and readable.

**Comment by kronbichler** [comment]
Now with the other code merged, can you please rebase this code to make the final assessment?

**Review by kronbichler — APPROVED** [review]
