### ISSUE TITLE
LinearAlgebra::{E,T}petraWrappers::Vector::compress() doesn't do anything.

### ISSUE THREAD

**Issue by bangerth** [dealii/dealii#15624]
At the time of writing, the `LinearAlgebra::EpetraWrappers::Vector` class does not implement its own `compress()` function, but because it derives from `VectorSpaceVector` inherits that base class's implementation of `compress()` -- which does nothing. This is almost certainly wrong.

I'm breaking the derivation from `VectorSpaceVector` in #15623, which requires me to implement my own `compress()` function, which I do by just not doing anything at all. This needs to be fixed.

**Comment by tjhei** [comment]
I doubt these classes are used at all.

**Comment by Rombur** [comment]
yes, I think we should remove `EpetraWrappers::Vector`

**Comment by bangerth** [comment]
Let's do that when @masterleinad 's tpetra work is completed. For now, this may perhaps still serve as a code example to look at when necessary.

**Comment by bangerth** [comment]
Linking to #745 so that we have a central place for these things.

**Comment by bangerth** [comment]
It turns out that the Tpetra wrapper vector has the same problem. See #15631.

**Comment by bangerth** [comment]
@gassmoeller: @tjhei and @Rombur suggest above that we deprecate the classes in `EpetraWrappers`. Do you think the `TpetraWrappers` state is so that we should do as suggested? Perhaps we can still get that done before the release.

**Comment by gassmoeller** [comment]
Yes, I think we need to deprecate them, but I am not sure if we can make it happen before the release.

Reasons for deprecating:
- More and more users will rely on Trilinos 17 (which we now accept during configuration), and they will silently switch to the TpetraWrappers. For them the deprecation probably doesnt matter much, since they cannot use the old classes anyway, but at least the deprecation makes clear that using the new ones is the intended way forward.
- Everyone still relying on Trilinos 16 or older should get the warning that these classes will go away.

Concerns I have:
- The TpetraWrappers are not full replacements for the old classes. Some functionality is missing, and I am convinced we will find more bugs when they are used in more different applications. Users may be stuck in a situation where the old classes produce deprecation warnings, but the new classes dont have the functionality they need.
- The TpetraWrappers do not support our example programs yet. That means compiling our examples will produce deprecation warnings we cannot avoid, which feels awkward.

Maybe we know more in a few days when my barrage of Tpetra compatibility PRs is merged. I have a running step-31 including thread safety locally, so there is hope we can support at least some of the examples with Tpetra already.

**Comment by bangerth** [comment]
Just to clarify: I was specifically talking about the classes in `TrilinosWrappers::EpetraWrappers`, which parallel the functionality we have for the classes in `TrilinosWrappers`. But the former are largely unused whereas the latter are of course heavily used.

**Comment by gassmoeller** [comment]
Oh, I misunderstood. I havent been paying much attention to the EpetraWrappers, but there is already https://github.com/dealii/dealii/pull/19242. Do you propose to change that from `DEPRECATED_EARLY` to `DEPRECATED` or something else? (I forget if we typically changes this before or after a release).

Yes, they should definitely be deprecated.

**Comment by masterleinad** [comment]
`EpetraWrappers` classes were already deprecated in https://github.com/dealii/dealii/pull/19242.

**Comment by bangerth** [comment]
Ah, I had forgotten about #19242. Since they are already deprecated, and since @gassmoeller has fixed the `compress()` issue with Tpetra, I think everything here has been completed.
