### PR TITLE
Force CUDA host compiler to be the same as the one used as C++ compiler

### LINKED ISSUE #7369: CUDA build fails due to `-Wsuggest-override`
### Problem

Building deal.II with CUDA support fails due to the `-Wsuggest-override` flag, which is unknown to `gcc-4.9`. Related to #6993.

### Details

The flag in question is conditionally added by `cmake/setup_compiler_flags_gnu.cmake:65`:
```
ENABLE_IF_SUPPORTED(DEAL_II_CXX_FLAGS "-Wsuggest-override")
```
CMake indicates that this test passes:
```
-- Include /usr/local/tnk10/share/dealii/cmake/setup_compiler_flags_gnu.cmake
-- Performing Test DEAL_II_HAVE_FLAG_Wsuggest_override
-- Performing Test DEAL_II_HAVE_FLAG_Wsuggest_override - Success
```
However, when building, this is proven false:
```
[ 70%] Building CUDA object source/base/CMakeFiles/obj_base_release.dir/cuda.cu.o
gcc-4.9: error: unrecognized command line option ‘-Wsuggest-override’
source/base/CMakeFiles/obj_base_release.dir/build.make:894: recipe for target 'source/base/CMakeFiles/obj_base_release.dir/cuda.cu.o' failed
make[2]: *** [source/base/CMakeFiles/obj_base_release.dir/cuda.cu.o] Error 1
```

### Crude Fix

Removing the line `ENABLE_IF_SUPPORTED(DEAL_II_CXX_FLAGS "-Wsuggest-override")` from `cmake/setup_compiler_flags_gnu.cmake` resolves this error, and permits deal.II to successfully build.

### Request for Solutions

An objectively "good" solution would retain `-Wsuggest-override` for compilers that support it. I can think of a couple ways to approach this:
1. Disable the specialized warning flags for the `Release` build, since end users probably do not care.
2. Revise the `ENABLE_IF_SUPPORTED` macro to accurately assess whether or not the flag is supported.

### Build Environment

- Debian version 9.5 "Stretch"
- CMake version 3.12.2 *via* `conda`
- CUDA version 8.0.44 *via* `apt`
- deal.II version 6b6ce30aad *via* `git` (master branch)
- GCC/G++/GFortran version 4.9 *via* `apt`
  - Required by CUDA, despite primary GCC version 6.3.0 *via* `apt`
- Make version 4.1 *via* `apt`
- p4est version [`93cedb5`](cburstedde/p4est@93cedb5a) *via* `git` (master branch)

### Build Command
```bash
$ cmake  -DDEAL_II_WITH_CXX14=OFF \
>             -DDEAL_II_WITH_CXX17=OFF \
>             -DCMAKE_BUILD_TYPE="Release" \
>             -DCMAKE_INSTALL_PREFIX=~/.conda/envs/prisms \
>             -DDEAL_II_WITH_MPI=ON \
>             -DDEAL_II_WITH_P4EST=ON \
>             -DP4EST_DIR=~/.conda/envs/prisms \
>             -DDEAL_II_WITH_CUDA=ON \
>             -DCUDA_cusolver_LIBRARY:FILEPATH=/usr/lib/x86_64-linux-gnu/libcusolver.so \
>             -DCUDA_cusparse_LIBRARY:FILEPATH=/usr/lib/x86_64-linux-gnu/libcusparse.so \
>             -DCUDA_PROPAGATE_HOST_FLAGS=OFF \
>             ..
```

### PR DESCRIPTION
**Pull request by masterleinad**
Fixes #7369. This is the same approach as taken in, e.g. https://github.com/LLNL/blt/blob/master/cmake/thirdparty/SetupCUDA.cmake#L49.

### CODE REVIEW

**Comment by tkphd** [comment]
By forcing the "CUDA host compiler" to be the same as the "host compiler," when the CMake compilers are improperly set, this change successfully halts the build with an instructive message:
```
$ cmake -DDEAL_II_WITH_CXX14=OFF -DCMAKE_BUILD_TYPE="Release" \
        -DDEAL_II_WITH_MPI=ON    -DDEAL_II_WITH_P4EST=ON \
        -DDEAL_II_WITH_CUDA=ON ..
```
```
-- Check for working CUDA compiler: /usr/bin/nvcc -- broken
CMake Error at /cmake-3.12/Modules/CMakeTestCUDACompiler.cmake:46 (message):
  The CUDA compiler

    "/usr/bin/nvcc"

  is not able to compile a simple test program.

  It fails with the following output:

    Change Dir: /dealii/7370/CMakeFiles/CMakeTmp
    
    Run Build Command:"/usr/site/bin/gmake" "cmTC_ff239/fast"
    /usr/site/bin/gmake -f CMakeFiles/cmTC_ff239.dir/build.make CMakeFiles/cmTC_ff239.dir/build
    gmake[1]: Entering directory '/dealii/7370/CMakeFiles/CMakeTmp'
    Building CUDA object CMakeFiles/cmTC_ff239.dir/main.cu.o
    /usr/bin/nvcc -ccbin=/usr/bin/c++    -x cu -c /dealii/7370/CMakeFiles/CMakeTmp/main.cu -o CMakeFiles/cmTC_ff239.dir/main.cu.o
    nvcc warning : The 'compute_20', 'sm_20', and 'sm_21' architectures are deprecated, and may be removed in a future release (Use -Wno-deprecated-gpu-targets to suppress warning).
    In file included from /usr/include/cuda_runtime.h:78:0,
                     from <command-line>:0:
    /usr/include/host_config.h:119:2: error: #error -- unsupported GNU version! gcc versions later than 5 are not supported!
     #error -- unsupported GNU version! gcc versions later than 5 are not supported!
      ^~~~~
    CMakeFiles/cmTC_ff239.dir/build.make:65: recipe for target 'CMakeFiles/cmTC_ff239.dir/main.cu.o' failed
    gmake[1]: *** [CMakeFiles/cmTC_ff239.dir/main.cu.o] Error 1
    gmake[1]: Leaving directory '/dealii/7370/CMakeFiles/CMakeTmp'
    Makefile:121: recipe for target 'cmTC_ff239/fast' failed
    gmake: *** [cmTC_ff239/fast] Error 2
```
This seems to be a satisfactory solution to #7369.

**Comment by Rombur** [comment]
@tkphd You get a better error message but were you able to use a new version of gcc with CUDA or did you "downgrade" the version that you were using on the host?

**Comment by tkphd** [comment]
@Rombur No -- if you use an incompatible host compiler (GCC≥5.0), the build process throws an error and exits. This is the appropriate behavior. The remedy is to specify the correct compiler, in most cases `gcc-4.9`, so that the host and device codes are built consistently. Perhaps this ought to be documented...

**Comment by masterleinad** [comment]
For me, the default host compiler is `gcc-8` and `nvcc` uses `gcc-6` by default. Consequently, this PR tries to use `gcc-8` by default which fails.
On the other hand, `gcc-6` doesn't work with `nvcc-9.1` either, so I want to use `gcc-5` as `C++` compiler. This PR requires me to only change the `CMAKE_CXX_COMPILER` and not provide extra `NVCC` flags.

**Comment by Rombur** [comment]
I think that's OK but we should add a comment in the documentation about this behavior since it's not the default behavior for nvcc.

File: doc/external-libs/cuda.html [hunk 1]
```diff
@@ -45,10 +47,12 @@ <h1>Installing deal.II with CUDA</h1>
       </pre>
       <code>-DDEAL_II_CUDA_FLAGS_DEBUG</code> and 
       <code>-DDEAL_II_CUDA_FLAGS_RELEASE</code> are also available if you want
-      a finer control on the CUDA flags. Finally, the CUDA compiler and the
+      a finer control on the CUDA flags. The CUDA compiler and the
       CUDA toolkit root directory can be set using 
       <code>-DDEAL_II_CUDA_COMPILER</code> and 
       <code>-DDEAL_II_CUDA_TOOLKIT_ROOT_DIR</code>.
+      Finally, the CUDA host compiler is the same as the C++ compiler
+      by default, but can be changed using CUDA flags as well.
```
Comment (Rombur) [inline doc/external-libs/cuda.html]: Have you tried that? You can compile deal with gcc 6 and have the CUDA host compiler to be gcc 5?

Comment (masterleinad) [reply doc/external-libs/cuda.html]: Yes, I tested that I can set the `CUDA` host compiler to `gcc-8` while the C++ compiler is `gcc-5` using `-ccbin` even with this PR. Of course, this is not really useful, but if people want to use a different `CUDA` host compiler that is compatible with the flags set due to the C++ compiler, they can.
