### ISSUE TITLE
More matrix-free / GMG  bugs from PR 4606

### ISSUE THREAD

**Issue by davydden** [dealii/dealii#4613]
@tamiko it looks like there are more bugs introduced in https://github.com/dealii/dealii/pull/4606 related to geometric multigrid and matrix-free. Can you please run the corresponding test-suite on your branch to confirm? 

The errors are convoluted but roughly read

```
lac/la_parallel_vector.h:1496:9: error: request for member ‘initialize_dof_vector’ in ‘matrix’, which is of pointer type <....>
lac/la_parallel_vector.h:1507:9: error: request for member ‘initialize_dof_vector’ in ‘matrix’, which is of pointer type <.....>
```

**Comment by tamiko** [comment]
I've a patch in the pipeline. ETA 24h.
