### PR TITLE
Fix compilation of a test.

### LINKED ISSUE #16794: Regression tester regressed 052db7
[start automated regression testsuite report]

Dear all,

this is the automated regression testsuite reporting a new regression between
- new revision: 052db79e87c284d063186767b590e683bb8e89db  [regression testsuite results](https://cdash.dealii.org/index.php?project=deal.II&filtercount=1&showfilters=1&field1=revision&compare1=63&value1=052db7)
- old revision: f6081edf3194bc74d3884a06a2efbc27549fc42f  [regression testsuite results](https://cdash.dealii.org/index.php?project=deal.II&filtercount=1&showfilters=1&field1=revision&compare1=63&value1=f6081e)

Summary:
- :angry: new test failures introduced for configuration [GNU-13.1.1-master-autodetection-20230507](https://cdash.dealii.org/build/2858) on site tester-tos

I have identified the following pull requests as possible candidates:
- #16784 (authored-by: @masterleinad; merged-by: @bangerth)
- #16790 (authored-by: @bangerth; merged-by: @drwells)
- #16791 (authored-by: @bangerth; merged-by: @drwells)
- #16789 (authored-by: @kronbichler; merged-by: @drwells)

Notes:
 - The regression reported above is a subset of the following full set of regressions compared to the baseline:
   - :angry: test failures for configuration [GNU-13.1.1-master-autodetection-20230507](https://cdash.dealii.org/build/2858) on site tester-tos
 - I will close and unpin this issue automatically once a full run is complete and compares cleanly to the baseline.
 - If closed I will reopen the issue if the testsuite run identified an additional regression compared to what I have reported so far.

[end automated regression testsuite report]

### LINKED ISSUE #16974: Regression tester regressed d97197
[start automated regression testsuite report]

Dear all,

this is the automated regression testsuite reporting a new regression between
- new revision: d97197395fca9e0fe6cb1292600bd32d8b34f082  [regression testsuite results](https://cdash.dealii.org/index.php?project=deal.II&filtercount=1&showfilters=1&field1=revision&compare1=63&value1=d97197)
- old revision: df8d02aab6f2b73edc8d89b4ab6794b75386e347  [regression testsuite results](https://cdash.dealii.org/index.php?project=deal.II&filtercount=1&showfilters=1&field1=revision&compare1=63&value1=df8d02)

Summary:
- :angry: new test failures introduced for configuration [GNU-13.2.0-master-debian-13](https://cdash.dealii.org/build/4080) on site tester-tng

I have identified the following pull requests as possible candidates:
- #16971 (authored-by: @bangerth; merged-by: @masterleinad)
- #16968 (authored-by: @bangerth; merged-by: @kronbichler)
- #16969 (authored-by: @bangerth; merged-by: @kronbichler)
- #16932 (authored-by: @peterrum; merged-by: @drwells)

Notes:
 - The regression reported above is a subset of the following full set of regressions compared to the baseline:
   - :angry: test failures for configuration [GNU-13.2.0-master-debian-13](https://cdash.dealii.org/build/4080) on site tester-tng
   - :disappointed: build warnings for configuration [GNU-9.4.0-master-ubuntu-lts-20.04](https://cdash.dealii.org/build/4071) on site tester-tng
 - I will close and unpin this issue automatically once a full run is complete and compares cleanly to the baseline.
 - If closed I will reopen the issue if the testsuite run identified an additional regression compared to what I have reported so far.

[end automated regression testsuite report]

### PR DESCRIPTION
**Pull request by bangerth**
This should fix #16794, broken by #16790.

The test as fixed compiles for me (it didn't without the changes) but produces different output on my machine. That said, the differences in output are produced in other parts of the test, not by the function here, so I'm pretty confident that the patch is correct.

### CODE REVIEW

**Review by kronbichler — APPROVED** [review]

**Review by masterleinad — COMMENTED** [review]
What about lines 139 through 147? We should also replace `begin_raw` and `end_raw` there.

**Comment by bangerth** [comment]
I had done so until I realized that (i) these are for `SymmetricTensor`, for which the function is not deprecated or removed yet, and (ii) `SymmetricTensor<4,dim>` does not implement `operator[]`.

I did verify that the test compiles with my changes. I'd like to leave everything else for a later patch.

**Review by masterleinad — APPROVED** [review]

**Comment by masterleinad** [comment]
> I had done so until I realized that (i) these are for `SymmetricTensor`, for which the function is not deprecated or removed yet, and (ii) `SymmetricTensor<4,dim>` does not implement `operator[]`.

It seems they are, see https://github.com/dealii/dealii/blob/16f23ad59990c75aa7710b91827c41f5b2c7ec90/include/deal.II/base/symmetric_tensor.h#L797-L844 and https://github.com/dealii/dealii/blob/master/include/deal.II/base/symmetric_tensor.h#L1021-L1037.

**Comment by bangerth** [comment]
Oh. Still -- let's leave that for a non-emergency situation.
