### ISSUE TITLE
Fix compilation with OpenCASCADE on the tester

### ISSUE THREAD

**Issue by masterleinad** [dealii/dealii#4384]
Recently, the tester failed on some PR (#4377, #4381, #4383) with
> FAILED: /usr/bin/clang++   -DDEBUG -DTBB_DO_ASSERT=1 -DTBB_IMPLEMENT_CPP0X=1 -DTBB_USE_DEBUG -Isource/opencascade -Iinclude -I/home/bob/source/include -I/home/bob/source/bundled/tbb41_20130401oss/include -I/home/bob/source/bundled/umfpack/UMFPACK/Include -I/home/bob/source/bundled/umfpack/AMD/Include -I/home/bob/source/bundled/boost-1.62.0/include -I/home/bob/source/bundled/muparser_v2_2_4/include -I/usr/lib/openmpi/include -I/usr/lib/openmpi/include/openmpi -I/home/bob/libs/parmetis-4.0.3/include -I/home/bob/libs/trilinos-12.4.2-Source/include -I/home/bob/libs/petsc-3.6.4/include -I/home/bob/libs/hdf5-1.8.15-patch1/include -I/home/bob/libs/oce-OCE-0.17/include/oce -I/home/bob/libs/p4est-1.1/FAST/include -I/home/bob/libs/slepc-3.6.0/include    -pedantic -fPIC -Wall -Wextra -Wpointer-arith -Wwrite-strings -Wsynth -Wsign-compare -Wswitch -Woverloaded-virtual -Wno-deprecated-declarations -Qunused-arguments -Wno-unsupported-friend -Wno-unused-parameter -Wno-unused-variable -Wno-unused-function -std=c++11 -Wno-parentheses -O0 -ggdb -MMD -MT source/opencascade/CMakeFiles/obj_opencascade_debug.dir/boundary_lib.cc.o -MF "source/opencascade/CMakeFiles/obj_opencascade_debug.dir/boundary_lib.cc.o.d" -o source/opencascade/CMakeFiles/obj_opencascade_debug.dir/boundary_lib.cc.o -c /home/bob/source/source/opencascade/boundary_lib.cc
In file included from /home/bob/source/source/opencascade/boundary_lib.cc:17:
/home/bob/source/include/deal.II/opencascade/boundary_lib.h:229:5: error: constructor for 'dealii::OpenCASCADE::NormalToMeshProjectionBoundary<1, 3>' must explicitly initialize the const member 'direction'
    NormalToMeshProjectionBoundary(const TopoDS_Shape &sh,
    ^
source/opencascade/boundary_lib.inst:12:17: note: in instantiation of member function 'dealii::OpenCASCADE::NormalToMeshProjectionBoundary<1, 3>::NormalToMeshProjectionBoundary' requested here
 template class NormalToMeshProjectionBoundary< 1 , 3>;
                ^
/home/bob/source/include/deal.II/opencascade/boundary_lib.h:254:20: note: 'direction' declared here
    const Point<3> direction;
                   ^
/home/bob/source/include/deal.II/opencascade/boundary_lib.h:229:5: error: constructor for 'dealii::OpenCASCADE::NormalToMeshProjectionBoundary<2, 3>' must explicitly initialize the const member 'direction'
    NormalToMeshProjectionBoundary(const TopoDS_Shape &sh,
    ^
source/opencascade/boundary_lib.inst:19:17: note: in instantiation of member function 'dealii::OpenCASCADE::NormalToMeshProjectionBoundary<2, 3>::NormalToMeshProjectionBoundary' requested here
 template class NormalToMeshProjectionBoundary< 2 , 3>;
                ^
/home/bob/source/include/deal.II/opencascade/boundary_lib.h:254:20: note: 'direction' declared here
    const Point<3> direction;
                   ^
/home/bob/source/include/deal.II/opencascade/boundary_lib.h:229:5: error: constructor for 'dealii::OpenCASCADE::NormalToMeshProjectionBoundary<3, 3>' must explicitly initialize the const member 'direction'
    NormalToMeshProjectionBoundary(const TopoDS_Shape &sh,
    ^
source/opencascade/boundary_lib.inst:26:17: note: in instantiation of member function 'dealii::OpenCASCADE::NormalToMeshProjectionBoundary<3, 3>::NormalToMeshProjectionBoundary' requested here
 template class NormalToMeshProjectionBoundary< 3 , 3>;
                ^
/home/bob/source/include/deal.II/opencascade/boundary_lib.h:254:20: note: 'direction' declared here
    const Point<3> direction;

**Comment by drwells** [comment]
I suspect #4377 may be the culprit since the compiler complains about initializing a `const` object.

**Comment by drwells** [comment]
In fact, it looks like we never even use the private member `direction` in this class. I will write a patch.

**Comment by drwells** [comment]
Well, things seem to work with clang 4.0; I suspect that this is a bug when we declare a default initialization of a class in the way I did.

I'll have a patch ready in a few minutes; if I am right the tester will be happy :D

**Comment by drwells** [comment]
Well, the tester is happy again (and builds are passing), so I am going to close this.

Fixed by #4386.
