### ISSUE TITLE
rol tests failing

### ISSUE THREAD

**Issue by davydden** [dealii/dealii#5456]
ROL in Trilinos are failing on this tester https://cdash.kyomu.43-1.org/viewTest.php?onlyfailed&buildid=13149 

with errors
```
In file included from /mnt/data/testsuite/dealii/tests/rol/vector_adaptor_01.cc:21:0:
/mnt/data/testsuite/dealii/include/deal.II/optimization/rol/vector_adaptor.h:226:33: error: ‘Elementwise’ in namespace ‘ROL’ does not name a type
     void applyUnary (const ROL::Elementwise::UnaryFunction<value_type> &f);
     
```

this is with `TRILINOS_VERSION: 12.2.1`. 

Probably the interfaces in ROL changed we need to require some minimum version of Trilinos. (certainly works with  `12.12.1`).

@vishalkenchan could you please try to figure out which version of Trilinos has the interface to ROL you expect?

**Comment by vishalkenchan** [comment]
@davydden I tested it with dealii@develop ^trilinos@12.12.1 as well. I couldn't reproduce this error with gcc@4.8.4. May be this is because of missing includes in `rol/vector_adaptor.h`?
`ROL_Elementwise_Function.hpp` was included in `ROL_Vector.hpp`, should we include `ROL_Elementwise_Function.hpp` again even though we are including `ROL_Vector.hpp` in `rol/vector_adaptor.h`?

**Comment by davydden** [comment]
strange, could indeed be some includes, like this https://github.com/dealii/dealii/issues/5455#issuecomment-344058180

**Comment by davydden** [comment]
@vishalkenchan you should try with  `12.2.1` instead of `12.12.1`.

**Comment by masterleinad** [comment]
It seems that the namespace `Elementwise` was introduced in 12.4.

**Comment by davydden** [comment]
> It seems that the namespace Elementwise was introduced in 12.4.

yes, there are some other issues with `12.2.1`, i think @vishalkenchan is working on a fix

**Comment by masterleinad** [comment]
The easiest fix would probably be to only enable `DEAL_II_TRILINOS_WITH_ROL` if we have at least `Trilinos-12.4`.

**Comment by vishalkenchan** [comment]
@masterleinad I intend to do very similar to this. I wanted to test before I push any changes.
