### PR TITLE
Fix instantiation for add_entries_local_to_global

### PR DESCRIPTION
**Pull request by zjiaqi2018**
`add_entries_local_to_global` currently is not instantiated for block systems, this should fix it. @tjhei 

intel compiler complains with
```
ld.bfd: /work2/08254/jiaqi2/frontera/dealii/installed_intel_test_branch/lib/libdeal_II.so.10.0.0-pre: undefined reference to `void dealii::AffineConstraints<double>::add_entries_local_to_global<dealii::BlockDynamicSparsityPattern>(std::vector<unsigned long, std::allocator<unsigned long> > const&, dealii::AffineConstraints<double> const&, std::vector<unsigned long, std::allocator<unsigned long> > const&, dealii::BlockDynamicSparsityPattern&, bool, dealii::Table<2, bool> const&) const'
ld.bfd: /work2/08254/jiaqi2/frontera/dealii/installed_intel_test_branch/lib/libdeal_II.so.10.0.0-pre: undefined reference to `void dealii::AffineConstraints<float>::add_entries_local_to_global<dealii::BlockDynamicSparsityPattern>(std::vector<unsigned long, std::allocator<unsigned long> > const&, dealii::AffineConstraints<float> const&, std::vector<unsigned long, std::allocator<unsigned long> > const&, dealii::BlockDynamicSparsityPattern&, bool, dealii::Table<2, bool> const&) const'
```

### CODE REVIEW

**Comment by tjhei** [comment]
This was broken in #13415

**Review by tjhei — APPROVED** [review]

**Review by masterleinad — APPROVED** [review]
