### ISSUE TITLE
deal.II 9.5.1+ does not compile with Boost 1.83 (Visual Studio 2022)

### ISSUE THREAD

**Issue by vdilecce** [dealii/dealii#16413]
OS: Windows 10
Compiler: Visual Studio 2022
deal.II version: 9.5.1 and master

I configured, built, and installed Boost 1.83 as follows:
```
.\bootstrap.bat

.\b2 --prefix="C:\sw\boost\msvc-2022\1.83.0-static" --build-dir=.\build-static --layout=versioned --abbreviate-paths --hash --without-python --without-graph_parallel --without-mpi --without-stacktrace toolset=msvc-14.3 link=static runtime-link=static,shared variant=debug,release architecture=x86 address-model=64 cxxstd=17 install
```

I configured and built deal.II 9.5.1 (and master) as follows:
```
cmake -G "Visual Studio 17 2022" -A x64 -T host=x64 -DCMAKE_INSTALL_PREFIX=C:/sw/dealii/msvc-2022/9.5.1 -DDEAL_II_CXX_FLAGS="/std:c++17" -DDEAL_II_ALLOW_AUTODETECTION=OFF -DDEAL_II_FORCE_BUNDLED_KOKKOS=ON -DBOOST_DIR=C:/sw/boost/msvc-2022/1.83.0-static -DBoost_USE_STATIC_RUNTIME=OFF -DBoost_ARCHITECTURE=-x64 -DDEAL_II_WITH_TBB=OFF -S . -B build

cmake --build build --parallel
```

Compilation fails with lots of errors like the following:
```
C:\sw\boost\msvc-2022\1.83.0-static\include\boost-1_83\boost\smart_ptr\detail\spinlock_gcc_atomic.hpp(48,16): error C3861: '__atomic_test_and_set': identifier not found
(compiling source file 'source/numerics/data_out.cc')
```

**Comment by bangerth** [comment]
@vdilecce Since I'm running into this again #16621, did you eventually figure out how to address the problem?

**Comment by vdilecce** [comment]
I did not. Two reasons basically:

- I found out that Boost 1.83 introduced a bug [fixed in 1.84](https://github.com/boostorg/math/blob/fd0a0bf207186514c88b69ea1c99fc4faf4ba650/include/boost/math/tools/promotion.hpp#L29-L35) so I went for Boost 1.82 only.
- I can't remember if I tried building deal.II 9.5 with Boost 1.82, but eventually I decided to skip deal.II 9.5 and wait for 9.6 later this year.

The issue remains, though (with [Boost 1.84](https://github.com/dealii/dealii/pull/16621) too, apparently).

**Comment by bangerth** [comment]
But 1.82 worked? Perhaps this is what I should try then.

**Comment by vdilecce** [comment]
I think so, though if I try an external Boost 1.82 there is still the problem of #16433

**Comment by vdilecce** [comment]
Commit dc830783ecc9c669caf6cd96ef40e60542db80cf (today's master) does not build on Visual Studio 2022 even with Boost 1.82.

**Comment by bangerth** [comment]
@vdilecce  Thanks for checking. I suppose it's the same error message? In other words, there is nothing specific about the commit you mention, but that no recent commit has worked with Boost 1.82/83/84?

**Comment by vdilecce** [comment]
The error message was very similar (actually, many almost identical errors with slightly different details).

I mentioned that commit since it was the most recent snapshot at the time of writing. I can't remember if Boost 1.82 worked with deal.II 9.5, but it doesn't with the current master.

I never tried Boost 1.84 because I am still on CMake 3.27 which supports up to Boost 1.83 (I can't tell which earlier Boost versions might or might not work).

**Comment by bangerth** [comment]
I think we figured out what the problem is. With the fix we applied to the bundled version of Kokkos (#16882) and the patch to the newly bundled version of BOOST, do you think we can close this issue?

**Comment by vdilecce** [comment]
Yes, the latest master commit works! Closing.
