### PR TITLE
Un-break compilation.

### LINKED ISSUE #1259: deall.ii dev build will not compile with gcc version 4.4.7
```
/gpfs/home/jvs5482/lib/devDeal/dealii/source/fe/fe_system.cc: In member function ‘void dealii::FESystem<dim, spacedim>::compute_fill(const dealii::Mapping<dim, spacedim>&, const typename dealii::Triangulation<dim, spacedim>::cell_iterator&, unsigned int, unsigned int, const dealii::Quadrature<dim_1>&, dealii::CellSimilarity::Similarity, const typename dealii::Mapping<dim, spacedim>::InternalDataBase&, const typename dealii::Mapping<dim, spacedim>::InternalDataBase&, const dealii::internal::FEValues::MappingRelatedData<dim, spacedim>&, dealii::internal::FEValues::FiniteElementRelatedData<dim, spacedim>&) const [with int dim_1 = 1, int dim = 1, int spacedim = 1]’:
/gpfs/home/jvs5482/lib/devDeal/dealii/source/fe/fe_system.cc:1046:   instantiated from ‘void dealii::FESystem<dim, spacedim>::fill_fe_values(const dealii::Mapping<dim, spacedim>&, const typename dealii::Triangulation<dim, spacedim>::cell_iterator&, const dealii::Quadrature<dim>&, const typename dealii::Mapping<dim, spacedim>::InternalDataBase&, const typename dealii::Mapping<dim, spacedim>::InternalDataBase&, const dealii::internal::FEValues::MappingRelatedData<dim, spacedim>&, dealii::internal::FEValues::FiniteElementRelatedData<dim, spacedim>&, dealii::CellSimilarity::Similarity) const [with int dim = 1, int spacedim = 1]’
/gpfs/home/jvs5482/lib/devDeal/build/source/fe/fe_system.inst:2:   instantiated from here
/gpfs/home/jvs5482/lib/devDeal/dealii/source/fe/fe_system.cc:1305: error: no matching function for call to ‘bind(<unresolved overloaded function type>, const dealii::FESystem<1, 1>* const, const boost::reference_wrapper<const dealii::Mapping<1, 1> >, const boost::reference_wrapper<const dealii::TriaIterator<dealii::CellAccessor<1, 1> > >, std::pair<unsigned int, unsigned int>, const boost::reference_wrapper<const dealii::Quadrature<1> >, dealii::CellSimilarity::Similarity, std::pair<const dealii::Mapping<1, 1>::InternalDataBase*, const dealii::Mapping<1, 1>::InternalDataBase*>, unsigned int&, const boost::reference_wrapper<const dealii::internal::FEValues::MappingRelatedData<1, 1> >, const boost::reference_wrapper<dealii::internal::FEValues::FiniteElementRelatedData<1, 1> >)’
/gpfs/home/jvs5482/lib/devDeal/dealii/source/fe/fe_system.cc: In member function ‘void dealii::FESystem<dim, spacedim>::compute_fill(const dealii::Mapping<dim, spacedim>&, const typename dealii::Triangulation<dim, spacedim>::cell_iterator&, unsigned int, unsigned int, const dealii::Quadrature<dim_1>&, dealii::CellSimilarity::Similarity, const typename dealii::Mapping<dim, spacedim>::InternalDataBase&, const typename dealii::Mapping<dim, spacedim>::InternalDataBase&, const dealii::internal::FEValues::MappingRelatedData<dim, spacedim>&, dealii::internal::FEValues::FiniteElementRelatedData<dim, spacedim>&) const [with int dim_1 = 0, int dim = 1, int spacedim = 1]’:
/gpfs/home/jvs5482/lib/devDeal/dealii/source/fe/fe_system.cc:1065:   instantiated from ‘void dealii::FESystem<dim, spacedim>::fill_fe_face_values(const dealii::Mapping<dim, spacedim>&, const typename dealii::Triangulation<dim, spacedim>::cell_iterator&, unsigned int, const dealii::Quadrature<(dim - 1)>&, const typename dealii::Mapping<dim, spacedim>::InternalDataBase&, const typename dealii::Mapping<dim, spacedim>::InternalDataBase&, const dealii::internal::FEValues::MappingRelatedData<dim, spacedim>&, dealii::internal::FEValues::FiniteElementRelatedData<dim, spacedim>&) const [with int dim = 1, int spacedim = 1]’
/gpfs/home/jvs5482/lib/devDeal/build/source/fe/fe_system.inst:2:   instantiated from here
/gpfs/home/jvs5482/lib/devDeal/dealii/source/fe/fe_system.cc:1305: error: no matching function for call to ‘bind(<unresolved overloaded function type>, const dealii::FESystem<1, 1>* const, const boost::reference_wrapper<const dealii::Mapping<1, 1> >, const boost::reference_wrapper<const dealii::TriaIterator<dealii::CellAccessor<1, 1> > >, std::pair<unsigned int, unsigned int>, const boost::reference_wrapper<const dealii::Quadrature<0> >, dealii::CellSimilarity::Similarity, std::pair<const dealii::Mapping<1, 1>::InternalDataBase*, const dealii::Mapping<1, 1>::InternalDataBase*>, unsigned int&, const boost::reference_wrapper<const dealii::internal::FEValues::MappingRelatedData<1, 1> >, const boost::reference_wrapper<dealii::internal::FEValues::FiniteElementRelatedData<1, 1> >)’
/gpfs/home/jvs5482/lib/devDeal/dealii/source/fe/fe_system.cc: In member function ‘void dealii::FESystem<dim, spacedim>::compute_fill(const dealii::Mapping<dim, spacedim>&, const typename dealii::Triangulation<dim, spacedim>::cell_iterator&, unsigned int, unsigned int, const dealii::Quadrature<dim_1>&, dealii::CellSimilarity::Similarity, const typename dealii::Mapping<dim, spacedim>::InternalDataBase&, const typename dealii::Mapping<dim, spacedim>::InternalDataBase&, const dealii::internal::FEValues::MappingRelatedData<dim, spacedim>&, dealii::internal::FEValues::FiniteElementRelatedData<dim, spacedim>&) const [with int dim_1 = 1, int dim = 1, int spacedim = 2]’:
```

### PR DESCRIPTION
**Pull request by bangerth**
On compilers without C++11, we need to stay within the limits of BOOST's maximal
number of arguments for boost::bind.

Fixes #1259.

### CODE REVIEW

**Comment by tamiko** [comment]
*hrng*
