### PR TITLE
Support sundials-3.0.0

### LINKED ISSUE #5372: issues with sundials 3.0.0
current develop can't compile with sundials 3.0.0. Some interfaces must have changed, numerous build errors:
```
     1297  /home/denis/spack/var/spack/stage/dealii-develop-bm27meuslaphwji6bj7o5fpwbnb2bsph/dealii/source/sundials/arkode.cc: In member function ‘void dealii::SUNDIALS::ARKode<VectorType>::reset(const double&, const double&, const VectorType&)’:
  >> 1298  /home/denis/spack/var/spack/stage/dealii-develop-bm27meuslaphwji6bj7o5fpwbnb2bsph/dealii/source/sundials/arkode.cc:427:25: error: ‘struct ARKodeMemRec’ has no member named ‘ark_setupNonNull’
     1299               ARKode_mem->ark_setupNonNull = true;
     1300                           ^
  >> 1301  /home/denis/spack/var/spack/stage/dealii-develop-bm27meuslaphwji6bj7o5fpwbnb2bsph/dealii/source/sundials/arkode.cc:444:25: error: ‘struct ARKodeMemRec’ has no member named ‘ark_MassSetupNonNull’
     1302               ARKode_mem->ark_MassSetupNonNull = true;
     1303                           ^
     1304  /home/denis/spack/var/spack/stage/dealii-develop-bm27meuslaphwji6bj7o5fpwbnb2bsph/dealii/source/sundials/arkode.cc: In instantiation of ‘void dealii::SUNDIALS::ARKode<VectorType>::reset(const double&, const double&, const VectorType&) [with VectorType = dealii::Vector<double>]’:
     1305  /home/denis/spack/var/spack/stage/dealii-develop-bm27meuslaphwji6bj7o5fpwbnb2bsph/dealii/source/sundials/arkode.cc:468:18:   required from here
  >> 1306  /home/denis/spack/var/spack/stage/dealii-develop-bm27meuslaphwji6bj7o5fpwbnb2bsph/dealii/source/sundials/arkode.cc:423:32: error: no matches converting function ‘t_arkode_solve_jacobian’ to type ‘int (*)(struct ARKodeMemRec*, N_Vector, N_Vector, N_Vector) {aka int (*)(struct ARKodeMemRec*, struct _generic_N_Vector*, struct _generic_N_Vector*, struct _generic_N_Vector*)’}
     1307           ARKode_mem->ark_lsolve = t_arkode_solve_jacobian<VectorType>;
     1308                                  ^
     1309  /home/denis/spack/var/spack/stage/dealii-develop-bm27meuslaphwji6bj7o5fpwbnb2bsph/dealii/source/sundials/arkode.cc:138:9: note: candidate is: template<class VectorType> int dealii::SUNDIALS::{anonymous}::t_arkode_solve_jacobian(ARKodeMem, N_Vector, N_Vector, N_Vector, N_Vector)
     1310       int t_arkode_solve_jacobian(ARKodeMem arkode_mem,
     1311           ^
  >> 1312  /home/denis/spack/var/spack/stage/dealii-develop-bm27meuslaphwji6bj7o5fpwbnb2bsph/dealii/source/sundials/arkode.cc:439:32: error: no matches converting function ‘t_arkode_solve_mass’ to type ‘int (*)(struct ARKodeMemRec*, N_Vector) {aka int (*)(struct ARKodeMemRec*, struct _generic_N_Vector*)’}
     1313           ARKode_mem->ark_msolve = t_arkode_solve_mass<VectorType>;
     1314                                  ^
     1315  /home/denis/spack/var/spack/stage/dealii-develop-bm27meuslaphwji6bj7o5fpwbnb2bsph/dealii/source/sundials/arkode.cc:188:9: note: candidate is: template<class VectorType> int dealii::SUNDIALS::{anonymous}::t_arkode_solve_mass(ARKodeMem, N_Vector, N_Vector)
     1316       int t_arkode_solve_mass(ARKodeMem arkode_mem,
     1317           ^
     1318  /home/denis/spack/var/spack/stage/dealii-develop-bm27meuslaphwji6bj7o5fpwbnb2bsph/dealii/source/sundials/arkode.cc: In instantiation of ‘void dealii::SUNDIALS::ARKode<VectorType>::reset(const double&, const double&, const VectorType&) [with VectorType = dealii::BlockVector<double>]’:
     1319  /home/denis/spack/var/spack/stage/dealii-develop-bm27meuslaphwji6bj7o5fpwbnb2bsph/dealii/source/sundials/arkode.cc:469:18:   required from here
  >> 1320  /home/denis/spack/var/spack/stage/dealii-develop-bm27meuslaphwji6bj7o5fpwbnb2bsph/dealii/source/sundials/arkode.cc:423:32: error: no matches converting function ‘t_arkode_solve_jacobian’ to type ‘int (*)(struct ARKodeMemRec*, N_Vector, N_Vector, N_Vector) {aka int (*)(struct ARKodeMemRec*, struct _generic_N_Vector*, struct _generic_N_Vector*, struct _generic_N_Vector*)’}
     1321           ARKode_mem->ark_lsolve = t_arkode_solve_jacobian<VectorType>;
     1322                                  ^
     1323  /home/denis/spack/var/spack/stage/dealii-develop-bm27meuslaphwji6bj7o5fpwbnb2bsph/dealii/source/sundials/arkode.cc:138:9: note: candidate is: template<class VectorType> int dealii::SUNDIALS::{anonymous}::t_arkode_solve_jacobian(ARKodeMem, N_Vector, N_Vector, N_Vector, N_Vector)
     1324       int t_arkode_solve_jacobian(ARKodeMem arkode_mem,
     1325           ^
  >> 1326  /home/denis/spack/var/spack/stage/dealii-develop-bm27meuslaphwji6bj7o5fpwbnb2bsph/dealii/source/sundials/arkode.cc:439:32: error: no matches converting function ‘t_arkode_solve_mass’ to type ‘int (*)(struct ARKodeMemRec*, N_Vector) {aka int (*)(struct ARKodeMemRec*, struct _generic_N_Vector*)’}
     1327           ARKode_mem->ark_msolve = t_arkode_solve_mass<VectorType>;
     1328                                  ^
     1329  /home/denis/spack/var/spack/stage/dealii-develop-bm27meuslaphwji6bj7o5fpwbnb2bsph/dealii/source/sundials/arkode.cc:188:9: note: candidate is: template<class VectorType> int dealii::SUNDIALS::{anonymous}::t_arkode_solve_mass(ARKodeMem, N_Vector, N_Vector)
     1330       int t_arkode_solve_mass(ARKodeMem arkode_mem,
     1331           ^
     1332  /home/denis/spack/var/spack/stage/dealii-develop-bm27meuslaphwji6bj7o5fpwbnb2bsph/dealii/source/sundials/arkode.cc: In instantiation of ‘void dealii::SUNDIALS::ARKode<VectorType>::reset(const double&, const double&, const VectorType&) [with VectorType = dealii::TrilinosWrappers::MPI::Vector]’:
     1333  /home/denis/spack/var/spack/stage/dealii-develop-bm27meuslaphwji6bj7o5fpwbnb2bsph/dealii/source/sundials/arkode.cc:474:18:   required from here
  >> 1334  /home/denis/spack/var/spack/stage/dealii-develop-bm27meuslaphwji6bj7o5fpwbnb2bsph/dealii/source/sundials/arkode.cc:423:32: error: no matches converting function ‘t_arkode_solve_jacobian’ to type ‘int (*)(struct ARKodeMemRec*, N_Vector, N_Vector, N_Vector) {aka int (*)(struct ARKodeMemRec*, struct _generic_N_Vector*, struct _generic_N_Vector*, struct _generic_N_Vector*)’}
     1335           ARKode_mem->ark_lsolve = t_arkode_solve_jacobian<VectorType>;
     1336                                  ^
     1337  /home/denis/spack/var/spack/stage/dealii-develop-bm27meuslaphwji6bj7o5fpwbnb2bsph/dealii/source/sundials/arkode.cc:138:9: note: candidate is: template<class VectorType> int dealii::SUNDIALS::{anonymous}::t_arkode_solve_jacobian(ARKodeMem, N_Vector, N_Vector, N_Vector, N_Vector)
     1338       int t_arkode_solve_jacobian(ARKodeMem arkode_mem,
     1339           ^
  >> 1340  /home/denis/spack/var/spack/stage/dealii-develop-bm27meuslaphwji6bj7o5fpwbnb2bsph/dealii/source/sundials/arkode.cc:439:32: error: no matches converting function ‘t_arkode_solve_mass’ to type ‘int (*)(struct ARKodeMemRec*, N_Vector) {aka int (*)(struct ARKodeMemRec*, struct _generic_N_Vector*)’}
     1341           ARKode_mem->ark_msolve = t_arkode_solve_mass<VectorType>;
     1342                                  ^
     1343  /home/denis/spack/var/spack/stage/dealii-develop-bm27meuslaphwji6bj7o5fpwbnb2bsph/dealii/source/sundials/arkode.cc:188:9: note: candidate is: template<class VectorType> int dealii::SUNDIALS::{anonymous}::t_arkode_solve_mass(ARKodeMem, N_Vector, N_Vector)
     1344       int t_arkode_solve_mass(ARKodeMem arkode_mem,
     1345           ^
     1346  /home/denis/spack/var/spack/stage/dealii-develop-bm27meuslaphwji6bj7o5fpwbnb2bsph/dealii/source/sundials/arkode.cc: In instantiation of ‘void dealii::SUNDIALS::ARKode<VectorType>::reset(const double&, const double&, const VectorType&) [with VectorType = dealii::TrilinosWrappers::MPI::BlockVector]’:
     1347  /home/denis/spack/var/spack/stage/dealii-develop-bm27meuslaphwji6bj7o5fpwbnb2bsph/dealii/source/sundials/arkode.cc:475:18:   required from here
  >> 1348  /home/denis/spack/var/spack/stage/dealii-develop-bm27meuslaphwji6bj7o5fpwbnb2bsph/dealii/source/sundials/arkode.cc:423:32: error: no matches converting function ‘t_arkode_solve_jacobian’ to type ‘int (*)(struct ARKodeMemRec*, N_Vector, N_Vector, N_Vector) {aka int (*)(struct ARKodeMemRec*, struct _generic_N_Vector*, struct _generic_N_Vector*, struct _generic_N_Vector*)’}
     1349           ARKode_mem->ark_lsolve = t_arkode_solve_jacobian<VectorType>;
     1350                                  ^
     1351  /home/denis/spack/var/spack/stage/dealii-develop-bm27meuslaphwji6bj7o5fpwbnb2bsph/dealii/source/sundials/arkode.cc:138:9: note: candidate is: template<class VectorType> int dealii::SUNDIALS::{anonymous}::t_arkode_solve_jacobian(ARKodeMem, N_Vector, N_Vector, N_Vector, N_Vector)
     1352       int t_arkode_solve_jacobian(ARKodeMem arkode_mem,
     1353           ^
  >> 1354  /home/denis/spack/var/spack/stage/dealii-develop-bm27meuslaphwji6bj7o5fpwbnb2bsph/dealii/source/sundials/arkode.cc:439:32: error: no matches converting function ‘t_arkode_solve_mass’ to type ‘int (*)(struct ARKodeMemRec*, N_Vector) {aka int (*)(struct ARKodeMemRec*, struct _generic_N_Vector*)’}
     1355           ARKode_mem->ark_msolve = t_arkode_solve_mass<VectorType>;
     1356                                  ^
     1357  /home/denis/spack/var/spack/stage/dealii-develop-bm27meuslaphwji6bj7o5fpwbnb2bsph/dealii/source/sundials/arkode.cc:188:9: note: candidate is: template<class VectorType> int dealii::SUNDIALS::{anonymous}::t_arkode_solve_mass(ARKodeMem, N_Vector, N_Vector)
     1358       int t_arkode_solve_mass(ARKodeMem arkode_mem,
     1359           ^
     1360  /home/denis/spack/var/spack/stage/dealii-develop-bm27meuslaphwji6bj7o5fpwbnb2bsph/dealii/source/sundials/arkode.cc: In instantiation of ‘void dealii::SUNDIALS::ARKode<VectorType>::reset(const double&, const double&, const VectorType&) [with VectorType = dealii::PETScWrappers::MPI::Vector]’:
     1361  /home/denis/spack/var/spack/stage/dealii-develop-bm27meuslaphwji6bj7o5fpwbnb2bsph/dealii/source/sundials/arkode.cc:480:18:   required from here
  >> 1362  /home/denis/spack/var/spack/stage/dealii-develop-bm27meuslaphwji6bj7o5fpwbnb2bsph/dealii/source/sundials/arkode.cc:423:32: error: no matches converting function ‘t_arkode_solve_jacobian’ to type ‘int (*)(struct ARKodeMemRec*, N_Vector, N_Vector, N_Vector) {aka int (*)(struct ARKodeMemRec*, struct _generic_N_Vector*, struct _generic_N_Vector*, struct _generic_N_Vector*)’}
     1363           ARKode_mem->ark_lsolve = t_arkode_solve_jacobian<VectorType>;
     1364                                  ^
     1365  /home/denis/spack/var/spack/stage/dealii-develop-bm27meuslaphwji6bj7o5fpwbnb2bsph/dealii/source/sundials/arkode.cc:138:9: note: candidate is: template<class VectorType> int dealii::SUNDIALS::{anonymous}::t_arkode_solve_jacobian(ARKodeMem, N_Vector, N_Vector, N_Vector, N_Vector)
     1366       int t_arkode_solve_jacobian(ARKodeMem arkode_mem,
     1367           ^
  >> 1368  /home/denis/spack/var/spack/stage/dealii-develop-bm27meuslaphwji6bj7o5fpwbnb2bsph/dealii/source/sundials/arkode.cc:439:32: error: no matches converting function ‘t_arkode_solve_mass’ to type ‘int (*)(struct ARKodeMemRec*, N_Vector) {aka int (*)(struct ARKodeMemRec*, struct _generic_N_Vector*)’}
     1369           ARKode_mem->ark_msolve = t_arkode_solve_mass<VectorType>;
     1370                                  ^
     1371  /home/denis/spack/var/spack/stage/dealii-develop-bm27meuslaphwji6bj7o5fpwbnb2bsph/dealii/source/sundials/arkode.cc:188:9: note: candidate is: template<class VectorType> int dealii::SUNDIALS::{anonymous}::t_arkode_solve_mass(ARKodeMem, N_Vector, N_Vector)
     1372       int t_arkode_solve_mass(ARKodeMem arkode_mem,
     1373           ^
     1374  /home/denis/spack/var/spack/stage/dealii-develop-bm27meuslaphwji6bj7o5fpwbnb2bsph/dealii/source/sundials/arkode.cc: In instantiation of ‘void dealii::SUNDIALS::ARKode<VectorType>::reset(const double&, const double&, const VectorType&) [with VectorType = dealii::PETScWrappers::MPI::BlockVector]’:
     1375  /home/denis/spack/var/spack/stage/dealii-develop-bm27meuslaphwji6bj7o5fpwbnb2bsph/dealii/source/sundials/arkode.cc:481:18:   required from here
  >> 1376  /home/denis/spack/var/spack/stage/dealii-develop-bm27meuslaphwji6bj7o5fpwbnb2bsph/dealii/source/sundials/arkode.cc:423:32: error: no matches converting function ‘t_arkode_solve_jacobian’ to type ‘int (*)(struct ARKodeMemRec*, N_Vector, N_Vector, N_Vector) {aka int (*)(struct ARKodeMemRec*, struct _generic_N_Vector*, struct _generic_N_Vector*, struct _generic_N_Vector*)’}
     1377           ARKode_mem->ark_lsolve = t_arkode_solve_jacobian<VectorType>;
     1378                                  ^
     1379  /home/denis/spack/var/spack/stage/dealii-develop-bm27meuslaphwji6bj7o5fpwbnb2bsph/dealii/source/sundials/arkode.cc:138:9: note: candidate is: template<class VectorType> int dealii::SUNDIALS::{anonymous}::t_arkode_solve_jacobian(ARKodeMem, N_Vector, N_Vector, N_Vector, N_Vector)
     1380       int t_arkode_solve_jacobian(ARKodeMem arkode_mem,
     1381           ^
  >> 1382  /home/denis/spack/var/spack/stage/dealii-develop-bm27meuslaphwji6bj7o5fpwbnb2bsph/dealii/source/sundials/arkode.cc:439:32: error: no matches converting function ‘t_arkode_solve_mass’ to type ‘int (*)(struct ARKodeMemRec*, N_Vector) {aka int (*)(struct ARKodeMemRec*, struct _generic_N_Vector*)’}
     1383           ARKode_mem->ark_msolve = t_arkode_solve_mass<VectorType>;
     1384                                  ^
     1385  /home/denis/spack/var/spack/stage/dealii-develop-bm27meuslaphwji6bj7o5fpwbnb2bsph/dealii/source/sundials/arkode.cc:188:9: note: candidate is: template<class VectorType> int dealii::SUNDIALS::{anonymous}::t_arkode_solve_mass(ARKodeMem, N_Vector, N_Vector)
     1386       int t_arkode_solve_mass(ARKodeMem arkode_mem,
     1387           ^
  >> 1388  source/sundials/CMakeFiles/obj_sundials_release.dir/build.make:65: recipe for target 'source/sundials/CMakeFiles/obj_sundials_release.dir/arkode.cc.o' failed
  >> 1389  make[2]: *** [source/sundials/CMakeFiles/obj_sundials_release.dir/arkode.cc.o] Error 1
     1390  make[2]: Leaving directory '/tmp/denis/spack-stage/spack-stage-Cc2o43/dealii/spack-build'
  >> 1391  CMakeFiles/Makefile2:5379: recipe for target 'source/sundials/CMakeFiles/obj_sundials_release.dir/all' failed
  >> 1392  make[1]: *** [source/sundials/CMakeFiles/obj_sundials_release.dir/all] Error 2
```

### PR DESCRIPTION
**Pull request by masterleinad**
Fixes #5372.

Lots of variables were removed and interfaces changed. The only major change is
 the replacement of `KINDense` by  `SUNDenseMatrix`, `SUNDenseLinearSolver` and `KINDlsSetLinearSolver` which is adapted from `examples/kinsol/serial/kinFerTron_dns.c`.

### CODE REVIEW

**Comment by davydden** [comment]
unless @luca-heltai has some comments, please merge yourself in a day or so.
