### ISSUE TITLE
Build failed with intel compiler

### ISSUE THREAD

**Issue by QiaoLei-88** [dealii/dealii#5829]
When building revision 78b759bb42, the intel compiler complains 
```
In file included from /home/qiaol/devel/dealii/include/deal.II/base/parameter_handler.h(23),
                 from /home/qiaol/devel/dealii/source/algorithms/operator.cc(17):
/home/qiaol/devel/dealii/include/deal.II/base/patterns.h(1455): error: too few arguments for class template "std::map"
        template <typename... Args> struct is_map_compatible<std::map               <Args...>> : std::true_type {};

```

The compiler version is `icpc (ICC) 15.0.0 20140723` and system environment is `CentOS Linux release 7.2.1511 (Core)`.

**Comment by Rombur** [comment]
We only test for ICC 18 so if you can, use a newer version of the compiler. Since the error is in `std::map` it could also be because of the gcc backend. Which version do you use? You need at least gcc 4.8.

**Comment by QiaoLei-88** [comment]
Sadly, the system gcc version is 4.4.6. 

I have checked that this deal.II revision works on my laptop with clang-900.0.39.2, either with CXX14 and CXX17 futures turned ON or OFF.

I think I have to abandon ICC and rebuild every thing with a newer GCC.

**Comment by bangerth** [comment]
@QiaoLei-88 -- good to hear from you!

The line in question is this one:
```
 template <typename... Args> struct is_map_compatible<std::map               <Args...>> : std::true_type {};
```
I suspect the compiler complains because `std::map` does not in fact take a variadic set of arguments, but has this very specific signature:
```
template<
    class Key,
    class T,
    class Compare = std::less<Key>,
    class Allocator = std::allocator<std::pair<const Key, T> >
> class map;
```
Can you try what happens if you replace the line in question by the following:
```
template<
    class Key,
    class T,
    class Compare,
    class Allocator
> 
struct is_map_compatible<std::map<Key,T,Compare,Allocator>> : std::true_type {};
```
Does it compile then? 

I think the code we currently have is correct, but that should not prevent us from working around a problem if we can find an easy way to do so.

There are other, similar lines in the same file for which we may have to do something similar. But let's do it one line at a time.

**Comment by QiaoLei-88** [comment]
@bangerth I was just set free from the Phd jail :)

You are right. The modification satisfied ICC. Now it stops on the next line about std::multmap with the same error.

**Comment by bangerth** [comment]
Well, congratulations about the PhD then!

`std::multimap` actually has the same list of template arguments as `std::map`:
```
template<
    class Key,
    class T,
    class Compare = std::less<Key>,
    class Allocator = std::allocator<std::pair<const Key, T> >
> class multimap;
```
(see http://en.cppreference.com/w/cpp/container/multimap). Can you make the same change to that line? `std::unordered_map` is here http://en.cppreference.com/w/cpp/container/unordered_map and `std::unordered_multimap` here: http://en.cppreference.com/w/cpp/container/unordered_multimap

**Comment by QiaoLei-88** [comment]
Now the maps problems are fixed.
The compile stops on
```
/home/qiaol/devel/dealii/include/deal.II/base/tensor.h(356): error: initial value of reference to non-const must be an lvalue
  class Tensor
        ^
          detected during:
            implicit generation of "dealii::Tensor<0, 1, Sacado::Rad::ADvar<double>> &dealii::Tensor<0, dim, Number>::operator=(dealii::Tensor<0, 1, Sacado::Rad::ADvar<double>> &&) [with dim=1, Number=Sacado::Rad::ADvar<double>]" at line 1506
            instantiation of class "dealii::Tensor<0, dim, Number> [with dim=1, Number=Sacado::Rad::ADvar<double>]" at line 1506
            implicit generation of "dealii::Tensor<1, 1, Sacado::Rad::ADvar<double>> &dealii::Tensor<rank_, dim, Number>::operator=(dealii::Tensor<1, 1, Sacado::Rad::ADvar<double>> &&) [with rank_=1, dim=1, Number=Sacado::Rad::ADvar<double>]" at line 1506
            instantiation of class "dealii::Tensor<rank_, dim, Number> [with rank_=1, dim=1, Number=Sacado::Rad::ADvar<double>]" at line 1506
            instantiation of "dealii::Tensor<rank, dim, dealii::ProductType<Number, dealii::EnableIfScalar<OtherNumber>::type>::type> dealii::operator*(const dealii::Tensor<rank, dim, Number> &, const OtherNumber &) [with rank=2, dim=1, Number=double, OtherNumber=Sacado::Rad::ADvar<double>]" at line 1530
            instantiation of "dealii::Tensor<rank, dim, dealii::ProductType<dealii::EnableIfScalar<Number>::type, OtherNumber>::type> dealii::operator*(const Number &, const dealii::Tensor<rank, dim, OtherNumber> &) [with rank=2, dim=1, Number=Sacado::Rad::ADvar<double>, OtherNumber=double]" at line 532 of "/home/qiaol/devel/dealii/source/fe/fe_values.cc"
            instantiation of "void dealii::FEValuesViews::internal::do_function_derivatives<order,dim,spacedim,Number>(const dealii::ArrayView<Number> &, const dealii::Table<2, dealii::Tensor<order, spacedim, double>> &, const std::vector<dealii::FEValuesViews::Scalar<dim, spacedim>::ShapeFunctionData, std::allocator<dealii::FEValuesViews::Scalar<dim, spacedim>::ShapeFunctionData>> &, std::vector<dealii::ProductType<Number, dealii::Tensor<order, spacedim, double>>::type,
                      std::allocator<dealii::ProductType<Number, dealii::Tensor<order, spacedim, double>>::type>> &) [with order=2, dim=1, spacedim=1, Number=const Sacado::Rad::ADvar<double>]" at line 1457 of "/home/qiaol/devel/dealii/source/fe/fe_values.cc"
            instantiation of "void dealii::FEValuesViews::Scalar<dim, spacedim>::get_function_hessians_from_local_dof_values(const InputVector &, std::vector<dealii::FEValuesViews::Scalar<dim, spacedim>::OutputType<InputVector::value_type>::hessian_type, std::allocator<dealii::FEValuesViews::Scalar<dim, spacedim>::OutputType<InputVector::value_type>::hessian_type>> &) const [with dim=1, spacedim=1, InputVector=std::vector<Sacado::Rad::ADvar<double>, std::allocator<Sacado::Rad::ADvar<double>>>]"
                      at line 24637 of "/home/qiaol/package_install/deal.II-git/build_devel/source/fe/fe_values.inst"
```

**Comment by jppelteret** [comment]
@QiaoLei-88 Can you please see what happens if you change [line 1506 in tensor.h](https://github.com/dealii/dealii/blob/5ad27a86c866dd9354c76c7736c5a5d71e1a210a/include/deal.II/base/tensor.h?utf8=%E2%9C%93#L1506) from
```c++
tt[d] = t[d] * factor;
```
to
```c++
{
  tt[d] = t[d];
  tt[d] *= factor;
}
```

**Comment by QiaoLei-88** [comment]
@jppelteret the patch doesn't for me.

Google leads to https://stackoverflow.com/questions/17771406/c-initial-value-of-reference-to-non-const-must-be-an-lvalue  and I reproduced the problem and fix in the link. I guess there might be something wrong in construction function of `Tensor`.

**Comment by bangerth** [comment]
I think @jppelteret 's suggestion is the right way to go.

**Comment by QiaoLei-88** [comment]
Shall we restrict `d==0` in such condition?

**Comment by bangerth** [comment]
No. We enforce this condition for all tensors because saying
```
  Tensor<2,2> t;
  t = 2;
```
is unclear -- is this supposed to mean that *all* entries should be equal to `2`, that the tensor should be 2 times the identity tensor, or what else?

But in the current case, we are considering
```
  Tensor<0,2> t;     // really just a single scalar -- a tensor of rank 0 has no indices
  t = 2;
```
Here, assigning `2` to a scalar is well defined. So we don't need to enforce the assertion we have elsewhere.

**Comment by QiaoLei-88** [comment]
I have just tested 7b31228c648b0122bf5695e3bf147cda06b771a8 and it doesn't fixed this issue.

**Comment by QiaoLei-88** [comment]
I still cannot figure out how the error message was triggered.
```
error: initial value of reference to non-const must be an lvalue

implicit generation of "dealii::Tensor<0, 1, Sacado::Rad::ADvar<double>> &dealii::Tensor<0, dim, Number>::operator=(dealii::Tensor<0, 1, Sacado::Rad::ADvar<double>> &&) [with dim=1, Number=Sacado::Rad::ADvar<double>]" at line 1506
```

The operator function template
```
Tensor<0,1,Number>&  Tensor<0,1,Number>::operator=(const Tensor<0,1,Number>& )
```
is explicitly defined.  And I see at nowhere that a reference to non-const is initialized by a rvalue.

**Comment by jppelteret** [comment]
@QiaoLei-88 I assume that you mean `2263ac72b63a99089a3adcd55cde5172c1fce1a8` (or that whole branch, rather than `7b31228`). Drats. Sorry, I don't have access to this compiler so I can only make a best guess as to how to correct the problem.

I think I have another idea though. Comparing [this problem line](https://github.com/dealii/dealii/blob/master/source/fe/fe_values.cc?utf8=%E2%9C%93#L532) in `dof_handler.cc` to others that compiler might be fine with, e.g. [this one](https://github.com/dealii/dealii/blob/master/source/fe/fe_values.cc?utf8=%E2%9C%93#L2895),  it looks like have missed out on some template parameters for the type of tensor that we're trying to cast between. I'll make another PR with a patch for this. Maybe that will help...

**Comment by QiaoLei-88** [comment]
This error could be fixed by patch  https://github.com/QiaoLei-88/dealii/commit/532271433c97407c6487f9fc28adc73501eff7f9 .

It's nothing more than an explicitly defined copy assignment operator. I don't know why the default one doesn't work.

Then, the code will trigger a such an error
```
/usr/include/c++/4.8.5/bits/unique_ptr.h(373) (col. 7): internal error: assertion failed: scan_routine: unexpected IL entry (shared/cfe/edgglue/edg_main.c, line 514)


compilation aborted for /home/qiaol/devel/dealii_git/source/fe/fe_tools_extrapolate.cc (code 4)
make[2]: *** [source/fe/CMakeFiles/obj_fe_release.dir/fe_tools_extrapolate.cc.o] Error 4
make[2]: *** Waiting for unfinished jobs....
```

So, I think it's time to abandon ICC 15 and turn to  GCC of a newer version. 

If anyone else thinks patch  https://github.com/QiaoLei-88/dealii/commit/532271433c97407c6487f9fc28adc73501eff7f9  worth a PR, I will glad to do so.
If not, we could just close this issue.


PS: previously I reported my gcc version as 4.4.6, that was missed with a remotely logined system.

**Comment by jppelteret** [comment]
Hmm... I'm happy that fixes the issue for you, but I'm not quite sure whether that is the *right* solution, since the other assignment operator should be general enough to catch this case.

Before you bail on this or `ICC 15`, may you please see if #5844 has any positive effect for you?

**Comment by bangerth** [comment]
I'd like to accept this patch if you make it into a pull request. It might fix the ambiguity found in #5844.

**Comment by QiaoLei-88** [comment]
@bangerth to the extend of my knowledge about CPP, I can't understand why this could be a fix.
The `Tensor<0,...>` class has only one non static data member `value`,  I think the patch gives nothing different with the default assignment operator.

**Comment by bangerth** [comment]
Because there are the other assignment operators, I believe that the default assignment operator is deleted. But you're right, you could implement your operator more simply if you wrote `=default` at the end of the declaration. Then you don't have to provide the implementation.

**Comment by jppelteret** [comment]
Like @QiaoLei-88, I would like to know where the compiler is getting the rvalue from...

I'm now reading through the error message again. In this message this line
```
instantiation of "dealii::Tensor<rank, dim, dealii::ProductType<Number, dealii::EnableIfScalar<OtherNumber>::type>::type> dealii::operator*(const dealii::Tensor<rank, dim, Number> &, const OtherNumber &) [with rank=2, dim=1, Number=double, OtherNumber=Sacado::Rad::ADvar<double>]" at line 1530
```
leads to this one
```
implicit generation of "dealii::Tensor<1, 1, Sacado::Rad::ADvar<double>> &dealii::Tensor<rank_, dim, Number>::operator=(dealii::Tensor<1, 1, Sacado::Rad::ADvar<double>> &&) [with rank_=1, dim=1, Number=Sacado::Rad::ADvar<double>]" at line 1506
instantiation of class "dealii::Tensor<rank_, dim, Number> [with rank_=1, dim=1, Number=Sacado::Rad::ADvar<double>]" at line 1506
```
ie. [this command](https://github.com/dealii/dealii/blob/1b57dc8bf945f5689b137f9cece8c892d424896a/include/deal.II/base/tensor.h?utf8=%E2%9C%93#L1506)
```c++
tt[d] = t[d] * factor;
```
So, again, where is the rvalue coming from? The return type from [`operator[]`](https://github.com/dealii/dealii/blob/1b57dc8bf945f5689b137f9cece8c892d424896a/include/deal.II/base/tensor.h?utf8=%E2%9C%93#L434) is a `Tensor&`. What I fail to see is how this, when sent to the recursive call to `operator*` results in the generation of a `dealii::Tensor<1, 1, Sacado::Rad::ADvar<double>> &&`. According to the error message, there's a call to `implicit generation of "dealii::Tensor<rank_, dim, Number>::operator=` that returns a `implicit generation of "dealii::Tensor<1, 1, Sacado::Rad::ADvar<double>> &`. Why?

**Comment by jppelteret** [comment]
Ok, [this line](https://github.com/dealii/dealii/blob/1b57dc8bf945f5689b137f9cece8c892d424896a/include/deal.II/base/tensor.h?utf8=%E2%9C%93#L483) answers my question above (the return type is correct). Question: Why does this assignement operator written as 
```
  template <typename OtherNumber>
Tensor &operator = (const Tensor<rank_,dim,OtherNumber> &rhs);
```
rather than
```
 template <typename OtherNumber>
Tensor<rank_,dim,Number> &operator = (const Tensor<rank_,dim,OtherNumber> &rhs);
      ^^^^^^^^^^^^^^^^^
```
?

**Comment by masterleinad** [comment]
That is the same type, isn't it?

**Comment by jppelteret** [comment]
@masterleinad Must be (although, since it bothers me that we're inconsistent here, I'm going to suggest us changing to the latter).

**Comment by jppelteret** [comment]
> I'd like to accept this patch if you make it into a pull request. It might fix the ambiguity found in #5844.

@QiaoLei-88 I'd support this patch as well. Would you be willing to make a PR for it?

**Comment by QiaoLei-88** [comment]
No problem, I will.

I tested around other several possibilities and the results are quite interesting.
Since I have no access to the ICC environment from home, I will post the results I got and the PR tomorrow.

**Comment by masterleinad** [comment]
Closed by #5865.
