### ISSUE TITLE
Failure to build with sundals-7.0.0

### ISSUE THREAD

**Issue by yurivict** [dealii/dealii#17136]
```
In file included from /wrkdirs/usr/ports/math/deal.ii/work/dealii-9.5.2/source/sundials/arkode.cc:20:
In file included from /wrkdirs/usr/ports/math/deal.ii/work/dealii-9.5.2/include/deal.II/sundials/arkode.h:46:
/wrkdirs/usr/ports/math/deal.ii/work/dealii-9.5.2/include/deal.II/sundials/sunlinsol_wrapper.h:63:36: error: unknown type name 'ATimesFn'
    SundialsOperator(void *A_data, ATimesFn a_times_fn, SUNContext linsol_ctx);
                                   ^
/wrkdirs/usr/ports/math/deal.ii/work/dealii-9.5.2/include/deal.II/sundials/sunlinsol_wrapper.h:84:5: error: unknown type name 'ATimesFn'
    ATimesFn a_times_fn;
    ^
/wrkdirs/usr/ports/math/deal.ii/work/dealii-9.5.2/include/deal.II/sundials/sunlinsol_wrapper.h:129:28: error: unknown type name 'PSolveFn'
                           PSolveFn   p_solve_fn,
                           ^
/wrkdirs/usr/ports/math/deal.ii/work/dealii-9.5.2/include/deal.II/sundials/sunlinsol_wrapper.h:158:5: error: unknown type name 'PSolveFn'
    PSolveFn p_solve_fn;
    ^
/wrkdirs/usr/ports/math/deal.ii/work/dealii-9.5.2/source/sundials/arkode.cc:80:7: error: no matching function for call to 'SUNContext_Create' 
      SUNContext_Create(mpi_communicator == MPI_COMM_SELF ? nullptr :
      ^~~~~~~~~~~~~~~~~
/usr/local/include/sundials/sundials_context.h:29:12: note: candidate function not viable: no known conversion from 'MPI_Comm *' (aka 'int *') to 'SUNComm' (aka 'int') for 1st argument; dereference the argument with *
SUNErrCode SUNContext_Create(SUNComm comm, SUNContext* sunctx_out);
           ^
/wrkdirs/usr/ports/math/deal.ii/work/dealii-9.5.2/source/sundials/arkode.cc:248:7: error: no matching function for call to 'SUNContext_Create'
      SUNContext_Create(mpi_communicator == MPI_COMM_SELF ? nullptr :
      ^~~~~~~~~~~~~~~~~
```

Version: 9.5.2
clang-18
FreeBSD 14.1

**Comment by marcfehling** [comment]
This should have been fixed upstream on the master branch. Can you please try and compile the current master branch, and report back here? Thank you!

**Comment by yurivict** [comment]
Are you planning to make a release with these fixes?

**Comment by bangerth** [comment]
Yes, eventually of course. SUNDIALS 7.0 made incompatible changed but came out after deal.II 9.5 -- we track these on our own master branch, we we could not foresee their changes at the time we made the 9.5 release.

The next deal.II release should come out within the next few months.

**Comment by marcfehling** [comment]
@yurivict Does it work for you on the master branch?

**Comment by drwells** [comment]
Now that the release is out I don't think there is anything else for us to do here.
