### ISSUE TITLE
step-61 fails to compile with clang 3.9

### ISSUE THREAD

**Issue by dangars** [dealii/dealii#8114]
Step-61 fails to compile with clang 3.9. It is not related to #8055. It is related to #8035. If I revert the commit fb1353b1ae0cfdacb760b36e38a9e4fb3392b88e then step-61 compiles. Below you can find the errors:

```
/home/daniel/repositories/dealii/examples/step-61/step-61.cc:135:19: error: no matching function for call to 'unit_symmetric_tensor'
      values[p] = unit_symmetric_tensor<dim>();
                  ^~~~~~~~~~~~~~~~~~~~~~~~~~
/home/daniel/repositories/dealii/examples/step-61/step-61.cc:440:21: note: in instantiation of member function 'Step61::Coefficient<2>::value_list' requested here
        coefficient.value_list(fe_values.get_quadrature_points(),
                    ^
/home/daniel/repositories/dealii/examples/step-61/step-61.cc:957:5: note: in instantiation of member function 'Step61::WGDarcyEquation<2>::assemble_system' requested here
    assemble_system();
    ^
/home/daniel/repositories/dealii/examples/step-61/step-61.cc:976:16: note: in instantiation of member function 'Step61::WGDarcyEquation<2>::run' requested here
      wg_darcy.run();
               ^
/home/daniel/repositories/dealii/include/deal.II/base/symmetric_tensor.h:917:3: note: candidate template ignored: couldn't infer template argument 'Number2'
  unit_symmetric_tensor();
  ^
1 error generated.
examples/CMakeFiles/step-61.debug.dir/build.make:62: recipe for target 'examples/CMakeFiles/step-61.debug.dir/step-61/step-61.cc.o' failed
make[2]: *** [examples/CMakeFiles/step-61.debug.dir/step-61/step-61.cc.o] Error 1
CMakeFiles/Makefile2:12008: recipe for target 'examples/CMakeFiles/step-61.debug.dir/all' failed
make[1]: *** [examples/CMakeFiles/step-61.debug.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....
```

**Comment by masterleinad** [comment]
is this fixed by #8112?

**Comment by dangars** [comment]
It does not seems to solve the problem. I'm building deal.ii again in order to submit the built to CDash. It should appear in one hour in CDash.

**Comment by kronbichler** [comment]
I guess we do not know for sure yet that #8112 really fixed the problem, do we @masterleinad? But in any case it looks like #8112/#8082 is our best bet. @dangars does step-42 compile for you? Did it between #8082 came in and before #8112?

**Comment by masterleinad** [comment]
https://cdash.kyomu.43-1.org/buildSummary.php?buildid=9738 doesn't report anything, yet.

**Comment by kronbichler** [comment]
In any case, #8112 did fix the issues we saw on our clang-4.0 machine regarding a very similar `unit_symmetric_tensor<dim>()` scenario. Please re-evaluate the newest master branch with clang-3.9 if possible in order for us to consider it for the 9.1 release.

**Comment by dangars** [comment]
I compiled deal.ii using the last version of the repository, which includes #8112 and it works.

I don't know why https://cdash.kyomu.43-1.org/buildSummary.php?buildid=9738 didn't report anything. In any case, now it compiles.

I close the issue.
