### ISSUE TITLE
TPetra linker errors

### ISSUE THREAD

**Issue by tjhei** [dealii/dealii#19392]
We are seeing the following linker errors in ASPECT with deal.II master:
```
/usr/bin/ld: /opt/deal.II-master/lib/libdeal_II.g.so.9.8.0-pre: undefined reference to `dealii::LinearAlgebra::TpetraWrappers::SparseMatrix<float, dealii::MemorySpace::Default>::set(unsigned int, unsigned int, unsigned int const*, float const*, bool)'
```

is this caused by #19389? (I have no time to dig into this right now)

**Comment by masterleinad** [comment]
Maybe, we don't see issues anywhere else, though. Are you actually using `Tpetra`?

**Comment by tjhei** [comment]
No, we are not.

**Comment by bangerth** [comment]
Not sure what *exactly* is going on, but the error message shows a template argument `Number = float`. But we don't instantiate anything for `float` in the .cc file.

**Comment by tamiko** [comment]
It probably means we forgot to instantiate the variant expliclty. Due to implicit instantiation the symbol might have been visible before. Then, any amount of reshuffling code can lead to some local changes / inlining / etc. and the symbol is no longer visible.
